### ISSUE TITLE
Install imdb-api dependency , getting errors when using webpack

### ISSUE THREAD

**Issue by Mandersen21** [AngularClass/angular-starter#1015]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)
- **I'm submitting a ...**
  [x ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository

Trying to install a dependency (imdb-api) https://www.npmjs.com/package/imdb-api

I have installed imdb-api, and can see it in my node-modules.
Using the newest webpack.

My package json file looks like this:
**package.json file**
    "ie-shim": "^0.1.0",
    "imdb-api": "^2.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "~0.6.17"

Then In a component, I have tried to import it or require it, but none seem to work.

**What i have tried:**
import { imdb } from 'imdb-api';
then made a console.log(imdb); in the constructor. 

and

var imdb = require('imdb-api');
console.log(imdb) in the constructor. 

All this gives alot of errors which I can google myself to. Have tried imdb-api in another solution (not webpack) and here it works.

_Errors:_

ERROR in ./~/forever-agent/index.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\Mikkel\Documents\Programmering\angular2-webpack-starter\node_modules\forever-agent'
 @ ./~/forever-agent/index.js 6:10-24
 @ ./~/request/request.js
 @ ./~/request/index.js
 @ ./~/request-promise/lib/rp.js
 @ ./~/imdb-api/lib/imdb.js
 @ ./src/app/about/about.component.ts
 @ ./src/app/about/index.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main

ERROR in ./~/tunnel-agent/index.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\Mikkel\Documents\Programmering\angular2-webpack-starter\node_modules\tunnel-agent'
 @ ./~/tunnel-agent/index.js 3:10-24
 @ ./~/request/lib/tunnel.js
 @ ./~/request/request.js
 @ ./~/request/index.js
 @ ./~/request-promise/lib/rp.js
 @ ./~/imdb-api/lib/imdb.js
 @ ./src/app/about/about.component.ts
 @ ./src/app/about/index.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main

ERROR in ./~/tough-cookie/lib/cookie.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\Mikkel\Documents\Programmering\angular2-webpack-starter\node_modules\tough-cookie\lib'
 @ ./~/tough-cookie/lib/cookie.js 32:10-24
 @ ./~/request/lib/cookies.js
 @ ./~/request/index.js
 @ ./~/request-promise/lib/rp.js
 @ ./~/imdb-api/lib/imdb.js
 @ ./src/app/about/about.component.ts
 @ ./src/app/about/index.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main

ERROR in ./~/forever-agent/index.js
Module not found: Error: Can't resolve 'tls' in 'C:\Users\Mikkel\Documents\Programmering\angular2-webpack-starter\node_modules\forever-agent'
 @ ./~/forever-agent/index.js 7:10-24
 @ ./~/request/request.js
 @ ./~/request/index.js
 @ ./~/request-promise/lib/rp.js
 @ ./~/imdb-api/lib/imdb.js
 @ ./src/app/about/about.component.ts
 @ ./src/app/about/index.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main

ERROR in ./~/tunnel-agent/index.js
Module not found: Error: Can't resolve 'tls' in 'C:\Users\Mikkel\Documents\Programmering\angular2-webpack-starter\node_modules\tunnel-agent'
 @ ./~/tunnel-agent/index.js 4:10-24
 @ ./~/request/lib/tunnel.js
 @ ./~/request/request.js
 @ ./~/request/index.js
 @ ./~/request-promise/lib/rp.js
 @ ./~/imdb-api/lib/imdb.js
 @ ./src/app/about/about.component.ts
 @ ./src/app/about/index.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main

ERROR in ./~/request/lib/har.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\Mikkel\Documents\Programmering\angular2-webpack-starter\node_modules\request\lib'
 @ ./~/request/lib/har.js 3:9-22
 @ ./~/request/request.js
 @ ./~/request/index.js
 @ ./~/request-promise/lib/rp.js
 @ ./~/imdb-api/lib/imdb.js
 @ ./src/app/about/about.component.ts
 @ ./src/app/about/index.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main

**Comment by no-more** [comment]
Hi,

I have the same issue with forerunnerdb. I don't know if it's related to webpack2 but it used to work when this project was based on webpack 1.13.x

Thanks.
