### ISSUE TITLE
Best practices on keeping angular2-webpack-starter code up to date after commiting your own app code to repository?

### ISSUE THREAD

**Issue by drag0** [AngularClass/angular-starter#1025]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ x] question about the decisions made in the repository

This is more of a general question on git + Angular2 development practice with this starter. How should one keep angular2-webpack-starter code up to date when you start commiting your own app code to pulled repository? I've never used a 'starter' code before from another repository to build my app on top of it so I'm wondering how to keep commiting your own app code and keep pulling all new updates of angular2-webpack-starter's code?

**Comment by bkbooth** [comment]
I just completed doing this recently. Our app code had deviated quite a way before we started upgrading so merging was going to be too much of a pain. We basically just wanted to get updates to the webpack build setup, not so much with the actual app code. It was time consuming but I ended up just walking through the commit history to `master`, and either cherry-picking or re-implementing any relevant changes.

**Comment by eddedd88** [comment]
I use  Beyond Compare to compare both repos (compare by folders), it nicely tells me what are the differences and just manually merge the diffs into my repo and commit.

**Comment by sbehun** [comment]
I'm currently doing this successfully for several projects this way:

1. Clone this repo
2. Change the origin to your own git repo
3. Add angularclass origin ```git remote add angularclass https://github.com/AngularClass/angular2-webpack-starter.git```
4. Fetch/Merge angularclass/master into your project as updates come in.
5. Profit
