### ISSUE TITLE
Uncaught Error: Unexpected value '[object Object]' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by aavelyn** [AngularClass/angular-starter#1067]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**

Bug
- **What is the current behavior?**

Loading a custom Module from our sdk throws

zone.js:269 Uncaught Error: Unexpected value '[object Object]' imported by the module 'AppModule'
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

This is the custom Module in our SDK.

``` js
@NgModule({
    providers:SELFBITS_PROVIDERS,
    imports:[HttpModule]
})

export class SelfbitsAngularModule{
    static initializeApp(config:SelfbitsAppConfig):ModuleWithProviders{
        return {
            ngModule:SelfbitsAngularModule,
            providers:[
                { provide: SELFBITS_CONFIG, useValue: config }
            ]
        }
    }
}
```

loading it in app.module.ts throws the error above, which seems to originate from missing the @NgModule Decorator. The SDK works fine in ng2-admin from akveo which is build on the angular2-webpack-starter. If I comment out the @NgModule Decorator, then ng2-admin also throws the same error, hence the suspicion that somehow it gets lost during (maybe) bundling.
- **What is the expected behavior?**

Initialize sdk without error
- **Please tell us about your environment:**
- Angular version: 2.0.0

**Comment by zeqk** [comment]
maybe related to this https://github.com/AngularClass/angular2-webpack-starter/issues/908#issuecomment-251108356

**Comment by Sri276286** [comment]
@aavelyn Did you find solution?

**Comment by mariohmol** [comment]
@zeqk seems to not be related.. tested her some tips from there but didnt work.

Anyone has other solutions?

in my case i'm using angular universal with express, so i dont know if is related to that..

Here is explaining more https://github.com/robwormald/ng-universal-demo/issues/21
