### ISSUE TITLE
Unexpected value 'MyCustomModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by Renaud009** [AngularClass/angular-starter#1114]
Today I had trouble importing an external component with Application NgModule. Following this issue https://github.com/angular/angular/issues/11438 it led me to consider it had to do with Webpack configuration.

``` javascript
Unexpected value 'MyCustomModule' imported by the module 'AppModule'
(anonymous function)    @   metadata_resolver.js:293
CompileMetadataResolver.getNgModuleMetadata @   metadata_resolver.js:280
RuntimeCompiler._compileComponents  @   runtime_compiler.js:142
RuntimeCompiler._compileModuleAndComponents @   runtime_compiler.js:80
RuntimeCompiler.compileModuleAsync  @   runtime_compiler.js:71
PlatformRef_._bootstrapModuleWithZone   @   application_ref.js:321
PlatformRef_.bootstrapModule    @   application_ref.js:303
main    @   main.browser.ts:18
ZoneDelegate.invokeTask @   zone.js:236
Zone.runTask    @   zone.js:136
ZoneTask.invoke @   zone.js:304
```

If it happens to anyone else, note that changing this line in webpack.common.js of current project worked well for me:

``` javascript
modules: [helpers.root('src'), helpers.root('node_modules')],
```

**Comment by BioSin** [comment]
+1, I had the same problem, changing
`modules: [helpers.root('src'), 'node_modules']` 
to
`modules: [helpers.root('src'), helpers.root('node_modules')],`
helped me

**Comment by anil1712** [comment]
I am getting below error while running AoT. I am using `System.js`.

<code>
 ngc -p tsconfig-aot.json

Error: Unexpected value 'NgSemanticModule' imported by the module 'AppModule'
    at F:\project_web\node_modules\@angular\compiler\bundles\compiler.umd.js:13996:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (F:\project_web\node_modules\@angular\compiler\bundles\compiler.umd.js:13981:46)
    at F:\project_web\node_modules\@angular\compiler\bundles\compiler.umd.js:12801:47
    at Array.forEach (native)
    at analyzeModules (F:\project_web\node_modules\@angular\compiler\bundles\compiler.umd.js:12800:17)
    at OfflineCompiler.analyzeModules (F:\project_web\node_modules\@angular\compiler\bundles\compiler.umd.js:12826:18)
</code>

Please help me to out of it

**Comment by jmbarbier** [comment]
Solved same problem while using v6 with @Renaud009 solution.

**Comment by sachanacar** [comment]
Hey @anil1712, I'm also having the same problem and I also use SystemJS. All answers I see online are for Webpack sadly :(

**Comment by tom10271** [comment]
Same error and I use SystemJs too

**Comment by sachanacar** [comment]
@tom10271 I've been trying to use [systemjs-builder](https://github.com/systemjs/builder) to bundle files together. 

However, I'm getting "TypeError: Cannot read property 'annotations' of undefined" in the console when I try to load the bundle.

I know Webpack has a plugin to automatically load the bundle in the browser, does SystemJS have that too?

**Comment by d3viant0ne** [comment]
@sachanacar - This is definitely the wrong place to inquire about SystemJS

**Comment by sachanacar** [comment]
@d3viant0ne true, I'm just desperate for answers!

**Comment by d3viant0ne** [comment]
I started using systemjs, the best advice I could give you at this point is bite the bullet, convert whatever project you are running to Webpack and save yourself the aggravation.

Future specs aside, Webpack ended up with all of the community support which is what eventually got me to make the switch about 6 months ago. I haven't regretted that decision personally or professionally.

**Comment by sachanacar** [comment]
@d3viant0ne thanks, I'll try to convince the team!
