### ISSUE TITLE
[Feature Request] Stylesheet Vendor Imports

### ISSUE THREAD

**Issue by Daeluse** [AngularClass/angular-starter#1122]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**
  Feature Request
- **What is the current behavior?**
  Import statements in entry points for CSS and SASS are not currently working,
- **What is the expected behavior?**
  Adding an Import statement in any of the entry points (IE Vendor) for a SASS (.scss) or a CSS (.css) file should result in that stylesheet being bundled into the global css for the application.
- **What is the motivation / use case for changing the behavior?**
  Some modules, such as Bootstrap V4, require stylesheets to be imported into the application to enable certain features, such as the flex grid. There are current workarounds in place, but they are bulky and bloated. This method of importing stylesheets used to work in the original builds of this seed project.\*

**Comment by Daeluse** [comment]
Using the following loaders in the mean time, no guarantee they will work in everyone's case, but they provide the temporary fix until we can get some vetted support for this.

```
{
  test: /\.scss$/,
  exclude: helpers.root('node_modules'),
  loaders: ['raw-loader', 'sass-loader']
},

{
  test: /\.scss$/,
  include: helpers.root('node_modules'),
  loaders: ["style", "css", "sass"]
},

{
  test: /\.css$/,
  exclude: helpers.root('src', 'app'),
  loader: ExtractTextPlugin.extract({ fallbackLoader: 'style-loader', loader: ['css', 'postcss']})
},

{
  test: /\.css$/,
  include: helpers.root('src', 'app'),
  loader: 'raw!postcss'
},
```

**Comment by davidalee** [comment]
Can't seem to get this to work. Where did you import your stylesheets into to get this working?

**Comment by davidalee** [comment]
Any reason why importing css/scss files worked in previous builds but is no longer working in the current build?

**Comment by shlomiassaf** [comment]
@davidalee Works for me...

Component resources does not work with AOT (styleUrls, templateUrl) since they don't go through the loader chain.

It will be fixed in a short period I believe.

**Comment by davidalee** [comment]
@shlomiassaf  I'm having issues with importing global styles into the vendor bundle

**Comment by shlomiassaf** [comment]
Vendor bundle was removed...

**Comment by d3viant0ne** [comment]
See #1304

**Comment by davidalee** [comment]
#1304 resolves this issue for me

**Comment by d3viant0ne** [comment]
For all those in this thread, the proposed solution is outline in the PR #1304 from @colinskow. If you want a say in how this is implemented, now would be the time to do so. If nobody objects, i'll be landing that by e.o.d

**Comment by Daeluse** [comment]
#1304 Does not provide the loader for SASS files in test environments. Other than that, the PR takes care of the issue in the current version of the repo.

**Comment by colinskow** [comment]
Generally Karma doesn't need external stylesheets, and unit tests probably shouldn't be dependent on them. So I purposely left it out of the test config. Tests will launch faster.

**Comment by d3viant0ne** [comment]
Unit test definitely shouldn't be dependent on style sheets any more than they should depend on data. @colinskow is correct in his test implementation.

**Comment by Daeluse** [comment]
Karma will not launch without error unless I add a null loader for SASS in my environment. The purpose is not to incorporate them but to ensure that the file types will be handled appropriately when encountered.
