### ISSUE TITLE
Build fail : optimizationError in bail mode: [default] /node_modules/@types/core-js/index.d.ts:21:13 Duplicate identifier 'PropertyKey'.

### ISSUE THREAD

**Issue by pierred69** [AngularClass/angular-starter#1159]
Hi,

I meet this error when I try to build my app (npm run build) : 

> optimizationError in bail mode: [default] /node_modules/@types/core-js/index.d.ts:21:13 Duplicate identifier 'PropertyKey'.

I tried to remove from package.json the line "typescript": "2.0.3", because there was a conflict between this and "@types/core-js", but now the builder doesn't find my modules defined in "src" with aliases I defined.

> optimizationError in bail mode: [default] /server/backelite/odigo/front/src/app/app.component.ts:3:28
> Cannot find module 'services/user.service'

The root "service" is aliased (to avoid `import ../../services/user.service` for exemple)

> var path = require('path');
> 
> var utils_aliases = [
>     'app',
>     'components',
>     'services',
>     'style',
>     'fonts',
>     'constants'
> ].reduce(function (acc, dir) {
>     acc[dir] = path.resolve('src', dir);
>     console.log("define alias for " + dir + " => " + acc[dir]);
>     return acc;
> }, {});
> 
> utils_aliases['packageJson'] = path.join(__dirname, 'package.json');
> 
> module.exports = utils_aliases;

Here's my resolver in my webpack.config.js :

> var aliases = require('./aliases');

> config.resolve = {
>     // only discover files that have those extensions
>     extensions: ['.ts', '.js', '.json', '.css', '.scss', '.html'],
>     descriptionFiles: ["package.json"],
>     modules: [path.resolve(__dirname, 'src'), 'node_modules' ],
>     alias: aliases
> };

And the rules for typescript files : 

 

> var atlOptions = '';
>     if (isTest && !isTestWatch) {
>     // awesome-typescript-loader needs to output inlineSourceMap for code coverage to work with source maps.
>     atlOptions = 'inlineSourceMap=true&sourceMap=false';
>  }

> config.module = {
>     rules: [
>       // Support for .ts files.
>       {
>         test: /\.ts$/,
>         loaders: ['awesome-typescript-loader?' + atlOptions, 'angular2-template-loader', '@angularclass/hmr-loader'],
>         exclude: [isTest ? /\.(e2e)\.ts$/ : /\.(spec|e2e)\.ts$/, /node_modules\/(?!(ng2-.+))/]
>       },
>       ...
>    ],
>    ...
> };

Would you have an idea for the solution ? :) 

Thx a lot !!

**Comment by timdang** [comment]
College of mine had a similar issue. He was using "directory junction" shortcut - rather than accessing directory directly. Perhaps that helps?
