### ISSUE TITLE
error list comes up when try to npm start

### ISSUE THREAD

**Issue by OdaiTu** [AngularClass/angular-starter#1170]
every thing in okay with npm i
but when i`m trying to write npm start , the a list of errors comes up !!
![capture](https://cloud.githubusercontent.com/assets/12837840/20245513/e16d703a-a9ab-11e6-9ec7-990da07d6c0c.PNG)

**Comment by EvaldasVasiliauskas** [comment]
Same here

**Comment by lordzero83** [comment]
Same here too

**Comment by Luchillo** [comment]
Is that Windows? getting support for Windows is hard.

**Comment by bykewrench** [comment]
I had the same issue running node-v7.1.0 on Windows 10.  I reverted to node-v6.9.1.  This resolved the above error.  Be warned that other errors occur as /src/app/index.ts is unnecessary  and AppModule should be imported directly from './app/app.module' in main.browser.ts.
