### ISSUE TITLE
Can you provide smaller Examples (Feature Request)

### ISSUE THREAD

**Issue by squadwuschel** [AngularClass/angular-starter#1207]
Hi,

The project is great, but I am new to webpack and the hole thing and its really hard to understand such complex examples and even harder when you want to implent only some use cases in your own Project.

It would be great If you could provide multiple simple examples for multiple Problems like

- How to resolve Angular 2 TemplateUrls with Webpack 2
- Write code into your destination index.html with Webpack  2
- Compile css/less with Webpack 2
- Compile TypeScript with Webpack 2
- ....

that would be a great Improvement in Understanding the hole development better.

thx 
 SquadWuschel

**Comment by d3viant0ne** [comment]
@squadwuschel - Have you looked at the new Webpack2 documentation? https://webpack.js.org/

**Comment by squadwuschel** [comment]
@d3viant0ne Yes the documentation is good so far, but small complete working examples are helping more than the documentation. The documentation is cool to get a more specific overview and you can extend the simple example with some more configuration.

Or Examples for some ng2 specific problems like TemplateUrls (I try to get this working since two days now and I can't get it to work) or how to compile TypeScript, ....
