### ISSUE TITLE
webpack.test.js is missing angular2-template-loader

### ISSUE THREAD

**Issue by elaijuh** [AngularClass/angular-starter#1224]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**

`webpack.test.js` is missing `angular2-template-loader` which makes templateUrl failed to load

* **What is the expected behavior?**

`angular2-template-loader` should be included

* **What is the motivation / use case for changing the behavior?**
Bug fix

* **Please tell us about your environment:**

- Angular version: 2.2.1
- Browser: [ PhantomJS ]

**Comment by pezza3434** [comment]
You'll also need a scss loader in test too, if you're referring to any sass files.
