### ISSUE TITLE
  Uncaught TypeError: Reflect.getMetadata is not a function

### ISSUE THREAD

**Issue by apulgupta** [AngularClass/angular-starter#1238]
I was writing unit test cases to test a simple service but while running test case, I am getting following error:

`Uncaught TypeError: Reflect.getMetadata is not a function`

Please suggest something to fix it.

**Comment by heqiang421** [comment]
i faced same error

**Comment by apulgupta** [comment]
I solved this issue by adding `import 'reflect-metadata'` on the top of my test specifications code file.

**Comment by leolanese** [comment]
that works for me too.

**Comment by kaitlynekdahl** [comment]
Worked for me too, but can anyone explain why this is needed? I ran into this issue trying to incorporate preboot with Angular Universal, so I'm not sure why the problem occurred in the first place.
