### ISSUE TITLE
Load time issues after prod build

### ISSUE THREAD

**Issue by kresogalic8** [AngularClass/angular-starter#1286]
Hey guys, I have a weird problem with initial load after I build the app for production.

I have a huge gap between loading all assets, below you can see that gap... At first, it loads all js files which is okay, but then comes that gap and then loads all SVG's and images... 

Do you know maybe what's the problem there?

![load](https://cloud.githubusercontent.com/assets/7289406/21386640/06c8ed42-c774-11e6-9051-bb63b7ea9203.jpg)

**Comment by d3viant0ne** [comment]
This isn't by any chance a public project I can go look at is it?

**Comment by kresogalic8** [comment]
Hm no it isn't. But did you have those issues before? This is a really big issue for me because it's a huge app and load time is really important. 

Is there any chance to share that with you somewhere?

**Comment by d3viant0ne** [comment]
I asked only because application performance can be effected by a huge number of variables and thus is extremely difficult to trouble shoot without being able to dig into the code / build.

I'm happy to help but without code to look at there really isn't anything someone could do besides guess.

**Comment by kresogalic8** [comment]
Yes, you're totally right... I will inspect more and see what's there that maybe affect on load time.

**Comment by gdi2290** [comment]
if you can reproduce it in a repo then we can help otherwise there is nothing we can do

**Comment by BamiGorengo** [comment]
I got exactly the same problem... But on Mobile Device it loads really much longer than in Desktop. I Upload a test version: http://mywebexile.devmonkeys.de/#/blog
