### ISSUE TITLE
e2e not working in HTML5 mode

### ISSUE THREAD

**Issue by JonnyBGod** [AngularClass/angular-starter#1306]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**

```npm run e2e``` and ```npm run ci``` do not work with angular2 HTML5 mode.
When your test asks for a route other than root it get a 404 error:

```
[Wed Dec 28 2016 18:55:01 GMT+0000 (WET)] "GET /about" Error (404): "Not found"
```

* **What is the expected behavior?**

* **Other information**

https://github.com/indexzero/http-server/issues/80

**Comment by Chuvisco88** [comment]
Same here, would be nice if http-server is dropped and something with pushState would be used instead
