### ISSUE TITLE
watchOptions - webpack have to be changed.

### ISSUE THREAD

**Issue by czegarram** [AngularClass/angular-starter#1364]
Lines:

`      watchOptions: {
        aggregateTimeout: 300,
        poll: 1000
      }`

have to be replaced by:

`      watchOptions: {
        aggregateTimeout: 300,
        poll: false
      }`

In file: (line 220)

[Webpack Dev](https://github.com/AngularClass/angular2-webpack-starter/blob/master/config/webpack.dev.js)

Because is generating a cpu problem in development environments that have Windows as Operating System.  

My specs:

- Windows 7
- Intel core i7 6600U 2.80
- 8GB Ram.

Cpu has 95% of use when i run 'npm start'. But, when I change that configuration option, it seems to start to work correctly.

**Comment by colinskow** [comment]
This is a good idea. `poll: false` won't work inside VirtualBox and a few other situations, but we can leave a commented note for those folk. This will improve performance for everybody else. In addition we could probably further improve watch performance with `ignored: /node_modules/`.

https://webpack.js.org/configuration/watch/

**Comment by d3viant0ne** [comment]
@colinskow May as well roll this into the webpack config rework and make it a configurable option for the user.

I'll rework them later this evening

**Comment by colinskow** [comment]
@d3viant0ne definitely add `ignored: /node_modules/` since that will definitely improve performance on lower end systems for everyone.

**Comment by colinskow** [comment]
I discovered an issue with `awesome-typescript-loader` that is related to this and contributing to poor performance. It is also preventing me from being able to separately watch and reload the Main and Renderer processes in my Electron Branch.

https://github.com/s-panferov/awesome-typescript-loader/issues/351
