### ISSUE TITLE
Discussion: Drop Node 5 Support?

### ISSUE THREAD

**Issue by colinskow** [AngularClass/angular-starter#1368]
Protractor `^5.0.0` dropped support Node 5. If we want to upgrade Protractor further we will need to drop support for Node 5. Other deps will likely do the same in order to use ES6 code natively.

In my opinion we should focus on Node versions from LTS to latest.

**Comment by d3viant0ne** [comment]
Touchy subject as many people are for a reason I honestly can't understand still using node 4.x.

I personally agree, support LTS + Next with a grace period for the previous LTS & dev version. If we are going to do this, we need to put out a warning via pretty much every way possible and give it a few weeks to soak in before we pull the trigger imo.

**Comment by shlomiassaf** [comment]
ohhh no, winter is coming :)

I would go LTS... 

This is a starter project, it should use the latest and greatest with responsibility... so LTS sound good.

**Comment by katallaxie** [comment]
👍

**Comment by d3viant0ne** [comment]
To be clear, I completely agree with the current LTS + Next approach we just need to be ready for the torches & pitch forks from the slow adopters when we drop 4.x support :)

**Comment by colinskow** [comment]
Angular 2 (and thus we) dropped support for 4.x some time ago. Node 5 passed quickly, so I don't expect many people stuck with it.

The reason 6 is important is because it has full ES6 support. That's why things are breaking on previous versions. I expect future versions should be stable for a while until Node starts adding ES 2016/17 support perhaps in 8.

**Comment by shlomiassaf** [comment]
Just a side note, we can still run < LTS with some scripting before running...
Something like running removing protractor 5 installing 4 and just running the build & tests w/o e2e...

This makes < LTS support limited but there...

**Comment by JonnyBGod** [comment]
I agree with the LTS + Next version. Node already defines road map for versions.

A simple version pairing note on readme should do the trick for the less informed.
