### ISSUE TITLE
Compodoc / TypeDoc / Nothing ?

### ISSUE THREAD

**Issue by d3viant0ne** [AngularClass/angular-starter#1370]
@vogloblinsky Dropped a comment in another issue in regards to switching from TypeDoc to Compodoc and was kind enough to spin up a demo - https://compodoc.github.io/angular2-webpack-starter/

The options are ...

- Keep TypeDoc.
- Switch to Compodoc.
- Drop doc generation and let users add what they will.

Personally I don't run docs on my applications currently, though [Compodoc](https://github.com/compodoc/compodoc) is the first offering that has the potential to drive enough value to warrant the addition.

//cc @colinskow @katallaxie @shlomiassaf

**Comment by shlomiassaf** [comment]
I Don't have much to contribute on this...

I saw the product that `TypeDoc` produces, didn't seem to be impressive.
But this is just theming... 

The Compodoc looks better, I must admit. 

If we consider things that does not belong to the starter, docs can easily fit in...
That said, promoting a doc system might help people document their OS code so it's good for the community.

I'm on board :)

If I need to choose, I would go with Compodoc, that's totally intuition nothing to back it up with :)

**Comment by colinskow** [comment]
I don't generate docs at the moment, so I don't have an opinion here. But it is definitely something useful to have a demo of in the repo, and I may consider using it if there is a good example.

**Comment by d3viant0ne** [comment]
Currently TypeDoc is part of the project and I know at least some people use it. It has consistently had maintenance issues so we either need to remove it and let people manage their own docs or switch to Compodoc.

Personally I'm leaning towards the latter, we need a good doc generation tool and it's by far the best to come down the pipe. Can't hurt to support a new lib, particularly one with as much promise as it holds for utility.

**Comment by vogloblinsky** [comment]
@d3viant0ne 
Yes compodoc is at the beginning, with some features which needs to be enhanced.
The target release 0.1.0 will add the last missing features for a matured tool.
I will update this discussion when it will be ready.

**Comment by DyckGerman** [comment]
Wait for the following Compodoc's roadmap point to be done:
 - handle external markdown files as "functional" documentation

For now my modular app has some "library modules" that i get via npm, and store in "node_modules/@my-project-scope/some-isolated-functionality-module"
Unfortunately compodoc cant include documentation for them and i have only documentation for my app skeleton

**Comment by d3viant0ne** [comment]
@DyckGerman - I'm in the same boat there. I do much the same thing for my ui platform at work and have run into the same issue.

**Comment by vogloblinsky** [comment]
Hi @d3viant0ne & @DyckGerman,

Version 1.0.0 of compodoc just landed yesterday. https://github.com/compodoc/compodoc/blob/master/CHANGELOG.md#100-beta1-2017-04-03

There are great new features : 
- routing graph
- component DOM tree graph
- watch flag
- etc...
- and also the one @DyckGerman was waiting, additional documentation.

Have a look, and feedbacks are always welcome 😄

**Comment by vogloblinsky** [comment]
Any news guys about the choice ?

**Comment by vogloblinsky** [comment]
@gdi2290 Just saw you close this issue.
I have generate an example of outputed documentation for angular-starter if you want to test what's Compodoc can generate : https://compodoc.github.io/angular-starter/

**Comment by gdi2290** [comment]
Nice, yeah we should use it

**Comment by vogloblinsky** [comment]
@gdi2290 PR created  : https://github.com/AngularClass/angular-starter/pull/1877
