### ISSUE TITLE
Unable to Run Test command

### ISSUE THREAD

**Issue by yvChauhan** [AngularClass/angular-starter#1377]
I'm submitting a Bug. Not able to run command  "npm run test" 
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
* **What is the current behavior?**
Npm run test getting failed on windows, not sure about Mac. 

![image](https://cloud.githubusercontent.com/assets/11193564/21961733/015ff882-db38-11e6-9668-9efdc284d84b.png)

I am using latest code in master

**Comment by colinskow** [comment]
Grrr... Non-stop problems with TypeScript on Windows builds! I just tested master the other day on Windows 10 and everything was fine. What Node version are you using?

Try downgrading to typescript 2.0.10 in you package.json, run `npm update` and let me know if this resolves it.

**Comment by colinskow** [comment]
Works for me after cloning master on Windows 10, Node 6.9.2.

**Comment by yvChauhan** [comment]
Hi @colinskow , yeah upgrading to latest node solve this issue, moreover, how can I get help related to unit tests setup as I am facing some issue like while running test command I got errors like "Cannot find the name 'describe'."  and also some global variables from custom typing.

**Comment by colinskow** [comment]
@yvChauhan make sure you have the latest `tsconfig.json` and `tsconfig.webpack.json` with Jasmine types installed.
