### ISSUE TITLE
Unit Test Sourcemap Missing

### ISSUE THREAD

**Issue by adstep** [AngularClass/angular-starter#1392]
I'm submitting a...
[*] bug report
[ ] feature request
[ ] question about the decisions made in the repository

What is the current behavior?

Sourcemapped files aren't being served when debugging unit tests.

1. Run ```npm run watch:test```
2. Open Karma in Chrome
3. Open debugger tools.
4. Files are missing from the sources tab.

**Comment by Aaltuj** [comment]
@adstep did you resolve this? I'm having the same issue. Breakpoints are hit but i can only debug the compiled JS file. See screenshot
![image](https://cloud.githubusercontent.com/assets/1876081/22326733/2a205328-e3b4-11e6-94c3-ffb2589bff5f.png)

**Comment by adstep** [comment]
No, I am still seeing this issue.

**Comment by dsebastien** [comment]
We face the same issue and couldn't find a working solution so far:
* no correct sourcemaps
* no way to actually debug the unit tests from the IDE..

**Comment by adstep** [comment]
Anyone figure out a workaround?

**Comment by Aaltuj** [comment]
No still no progress on my end

**Comment by greglarson** [comment]
The issue is with the istanbul-instrumenter-loader plugin. See this example to conditionally load when not running in 'auto-watch'.
http://stackoverflow.com/questions/39131809/karma-webpack-sourcemaps-not-working

**Comment by dsebastien** [comment]
@greglarson is right. At work we have duplicated the webpack test and karma configs to have one for developers without any code instrumentation (Istanbul, coverage) and another one for our CI and Sonar.

It works and now we're able to debug our tests in IntelliJ/Webstorm and Chrome.

**Comment by Aaltuj** [comment]
For the completeness i will explain what i've done. For a project i've used a webpack-starter version from around october last year. There the unit-test are minimized and not readable. I have tried that already. This will only resolve the code to be readable and debuggable JS compiled from TS. The issue still remains with a new version of the webpack-starter only now i don't have to disable the istanbul coverage to see readable and debuggable JS compiled from TS

**Comment by talamaska** [comment]
I still see compiled ts code not minimised in devtools even with istanbul-instrumenter-loader commented out. When it it is not commented out I can see that the coverage produced is correct. The html correctly navigates me to typescript code where I can see something is not tested.

**Comment by talamaska** [comment]
does this mean that it won't be fixed somehow? It seems that I just disabled some stuff and now I can see TS in dev tools, I thing it's the coverage stuff

**Comment by gdi2290** [comment]
@talamaska can you make a PR? I was closing issues because I plan on doing a huge refactor of the repo

**Comment by talamaska** [comment]
I applied the logic from angular2-webpack-starter
