### ISSUE TITLE
Can't bind to 'formGroup' since it isn't a known property of 'form'

### ISSUE THREAD

**Issue by ozknemoy** [AngularClass/angular-starter#1399]
first of all i have all needed imports
    ` import { FormsModule,ReactiveFormsModule } from '@angular/forms';`
and 
   ```
 @NgModule({
    bootstrap: [AppComponent],
    ....
    imports: [ 
        ...
        ReactiveFormsModule,
        FormsModule,
```
and stack 
```
<form [ERROR ->][formGroup]="myGroup">

</form>
```

in another angular 2 repo this works fine

**Comment by karolmie1** [comment]
I think the problem may be caused by camelcase. Can you try to use mygroup instead of myGroup. I had similar problems, and that fixed it.

**Comment by ozknemoy** [comment]
just tried. same issue

**Comment by RashmiNalwad** [comment]
Tried. Facing Same issue.

**Comment by chivandikwa** [comment]
Having same problem. Anyone with a solution so far?

**Comment by gowthamrodda** [comment]
I got the same problem. As I was using <form [FormGroup]="myForm">. Then I changed it to <form [formGroup='myForm']>
It solved the issue.

**Comment by ozknemoy** [comment]
@gowthamrodda    hmmm...  Failed to execute 'setAttribute' on 'Element': '[formGroup' is not a valid attribute name

**Comment by mertsincan** [comment]
Please see; http://stackoverflow.com/questions/39152071/cant-bind-to-formgroup-since-it-isnt-a-known-property-of-form

**Comment by ozknemoy** [comment]
@mertsincan  thanks but pref 'directives' do not exist in @Component now

**Comment by paulwalker** [comment]
Any luck on this? I am experiencing the same thing.

**Comment by Sumei1009** [comment]
Any solutions? facing same issue

**Comment by nilaysaha** [comment]
Same issue here....

**Comment by tsureshpandi** [comment]
After upgrading angular2 to new version i face similar issue.

After lot of changes i got it to work by updating the followings in src/polyfills.ts file.
(by default new angular cli commented these lines, i compare with my old project & update required.)

import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';

**Comment by ozknemoy** [comment]
also updated angular to 2.4.9 and the issue gone

**Comment by gowthamrodda** [comment]
Hy in your AppModule, do this.

import { FormsModule, ReactiveFormsModule } from '@angular/forms';

and add  ReactiveFormsModule to imports Array

**Comment by bhvreddy** [comment]
import 
    FormsModule,
    ReactiveFormsModule,
in modules where that component exists ..

**Comment by raviurlams** [comment]
add "ReactiveFormsModule" in your component as well.

import { FormGroup, FormArray, FormBuilder, Validators,ReactiveFormsModule } from '@angular/forms';

**Comment by guna1404** [comment]
import below module its working fine :) Thank you gowthamrodda 

import { FormsModule, ReactiveFormsModule } from '';

and add ReactiveFormsModule to imports Array

imports: [
FormsModule,
ReactiveFormsModule
]

**Comment by dumitruaxentii** [comment]
still facing this issue.

i tried all the solutions above.

**Comment by usha77** [comment]
Hi im also facing same error

login.html
<h1 align="center"><strong>Welcome to login</strong></h1>

<div class="container">
  <div class="row">
      <div class="col-md-4">
      <form  [FormGroup]="loginForm" (Submit)="onSubmit()">
          <div class="form-group">
              <label for="username">Username</label>
            <input type="text" class="form-control"  placeholder="username" name="username" FormControlName="username" required=""/>
          </div>
          <div class="form-group">
              <label for="password">Password</label>
            <input type="password" class="form-control"  placeholder="password" name="password"FormControlName="password" required=""/>
          </div>
          <div class="form-group">
              <button [disabled]="loading" class="btn btn-primary">Login</button>
              <a  class="btn btn-link">Register</a>
          </div>
      </form>
    </div>
</div>
</div> 

login.module.ts

import { NgModule } from "@angular/core";
import { ReactiveFormsModule, FormsModule } from '@angular/forms';
import { LoginComponent } from './login.component';

@NgModule({
    imports: [
      ReactiveFormsModule,
      FormsModule
      
    ],
    declarations: [
     LoginComponent
    ]
  })
export class LoginModule{

}

app.module.ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';
import { CommonModule } from '@angular/common';
import { LoginModule } from './login/login.module';
import { AppRoutingModule } from './app-routing.module';



@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    CommonModule,
    BrowserModule,
    LoginModule,
    AppRoutingModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

**Comment by himanshutecstub** [comment]
problem solve by import `ReactiveFormsModule`
`import { FormsModule, ReactiveFormsModule } from '@angular/forms';`
Here must use below from where you declare login module.

**Comment by shalinimandal** [comment]
import
FormsModule,
ReactiveFormsModule,

in shared.module.ts

and import SharedModule in your core-feature.module.ts, feature-module.module.ts, etc.
