### ISSUE TITLE
Error on pug rendering routerLink

### ISSUE THREAD

**Issue by CarlosV89** [AngularClass/angular-starter#1424]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Added pug support and when I try to do 
`a('[routerlink]'=" ['./'] " routerlinkactive='active')`
it gives me 
"Template parse errors:↵Can't bind to 'routerlink' since it isn't a known property of 'a'.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
Base starter proyect with added pug support only

* **What is the expected behavior?**
should work

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
The only thing I have changed or added from the repo is pug support.

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by d3viant0ne** [comment]
`[routerLink]="['./']"`

**Comment by CarlosV89** [comment]
I had already tried that, to even try to do this, the pug-ng-plugin has to be installed to the loader. But it is still not working

**Comment by d3viant0ne** [comment]
You have all the proper routing modules imported? Outside of the binding syntax, that error denotes you have a `ngModule` issue.

Paste in the component & the module it that declares it.

**Comment by CarlosV89** [comment]
If that were true, wouldn't that same error happen even if I used an html template? That's not happening.

https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/app/app.module.ts
https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/app/app.component.ts

I grabbed the template from the app.component.ts and created 2 files, one html and the other pug. I changed the components template to templateUrl and directed it to them both to observe both use cases, it works with html template, it doesn't work with the pug template

**Comment by d3viant0ne** [comment]
Fair enough. Not to ask insulting questions but you did add `pug-html-loader` to `webpack.common.js`?

**Comment by CarlosV89** [comment]
😂  Yes sir, I did 
`,

        {
          test: /\.pug/,
          use:{
            loader: 'pug-html-loader?{"pretty":true,"exports":false}',
            query: {
              doctype: 'html',
              plugins: ['pug-plugin-ng']
            },
          }
        }`

**Comment by d3viant0ne** [comment]
You tried stripping the optional params being passed to `pug-html-loader`?

**Comment by CarlosV89** [comment]
Yes.

**Comment by d3viant0ne** [comment]
Officially out of good ideas. @shlomiassaf @katallaxie - Either of you ever mess around with pug? I know this worked at some point but i've never done anything with pug / jade

**Comment by gizm0bill** [comment]
Why don't you just use the default [pug-loader](https://github.com/pugjs/pug-loader) plugin?
Works fine for me: `a( [routerLink]="['./']", routerLinkActive='active' ) testing`


One issue though, you can't use `templateUrl` in your components, only `template: require('tpl.pug')` or `import * as tpl from './tpl.pug'` and `template: tpl()`

**Comment by CarlosV89** [comment]
I tried but its giving me all sort of errors... 
` Error in ./AppComponent class AppComponent - inline template:0:225 caused by: Failed to execute 'add' on 'DOMTokenList': The token provided ('md- ['./'] ') contains HTML space characters, which are not valid in tokens.`

**Comment by CarlosV89** [comment]
Its because of extra commas needed, thats why I was using pug-plugin-ng

**Comment by gizm0bill** [comment]
are you sure you tried on a clean install? It looks like some actual pug compilation bug

**Comment by CarlosV89** [comment]
pug-loader returns a function, on imports you must call that function, ie
`template: require('./template.pug')();'`

You must take in consideration that you need to write some angular expressions with '' take this snippet of code for example. 

`md-card('(click)'= 'functionCall(data.param)')`
if the call to (click) and the call to the function are not in '', they will not work. 
This is exactly what I've been trying to avoid, using pug-plugin-ng + pug-html-loader https://www.npmjs.com/package/pug-plugin-ng

**Comment by gizm0bill** [comment]
Actually you only need to provide the `templateUrl` with a string, `angular-template-loader` or whatever it's called transforms it into a `require` call and `apply-loader` calls the function.
And regarding the template you can simply write `md-card( (click)="functionCall(data.param)", [attr.something]="something?.else" )`

**Comment by CarlosV89** [comment]
Great! Thank you very much!!! Do you know of a way to use pug without having to use the extra commas?

**Comment by gizm0bill** [comment]
I forked the repository, here: https://github.com/gizm0bill/angular2-webpack-starter/commit/925646924865aa5821424231b44644e51f29c6b3
