### ISSUE TITLE
__WEBPACK_IMPORTED_MODULE_19_zone_js_dist_long_stack_trace_zone__ is not a function

### ISSUE THREAD

**Issue by KhaledElAnsari** [AngularClass/angular-starter#1425]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

The error is from the `polyfill.browser.ts` file, the bundler is not recognizing `longStackTrace` that is imported as the following

```ts
import * as longStackTrace from 'zone.js/dist/long-stack-trace-zone';
.
.
.
if ('production' === ENV) {
  // Production

} else {

  // Development
  Error.stackTraceLimit = Infinity;
  longStackTrace(); // it's not a function for the bundler

}
```

I'm not sure exactly what's the solution but I did what you guys used to do in a previous version of this kit

```ts
if ('production' === ENV) {
  // Production

} else {

  // Development
  Error.stackTraceLimit = Infinity;
  require('zone.js/dist/long-stack-trace-zone');

}
```

I'm using the latest kit but with the wepback2 RC (I started the project two weeks before the official release of it! sigh)

**Comment by ronydj** [comment]
I am having the same issue here

**Comment by chinmoyDebnath** [comment]
+1
