### ISSUE TITLE
Adding a font question

### ISSUE THREAD

**Issue by TeodorKolev** [AngularClass/angular-starter#1429]
How I am suppose to add webfont?
I have made folder called "fonts" in assets and I have put my fonts there.
fonts.scss
```
@font-face {
  font-family: 'Lato';
  src: url('../assets/font/Lato-Regular.eot');
  src: url('../assets/font/Lato-Regular.eot?#iefix') format('embedded-opentype'),
  url('../assets/font/Lato-Regular.woff2') format('woff2'),
  url('../assets/font/Lato-Regular.woff') format('woff'),
  url('../assets/font/Lato-Regular.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}
```
Also I have added configuration for fonts and add it to app.modules.ts
`import '../styles/fonts.scss';`
My questions what code should I add to webpack to make it work.?
Thank you

**Comment by TeodorKolev** [comment]
How I am suppose to add webfont?
I have made folder called "fonts" in assets and I have put my fonts there.
fonts.scss
```
@font-face {
  font-family: 'Lato';
  src: url('../assets/font/Lato-Regular.eot');
  src: url('../assets/font/Lato-Regular.eot?#iefix') format('embedded-opentype'),
  url('../assets/font/Lato-Regular.woff2') format('woff2'),
  url('../assets/font/Lato-Regular.woff') format('woff'),
  url('../assets/font/Lato-Regular.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}
```
Also I have added configuration for fonts and add it to app.modules.ts
`import '../styles/fonts.scss';`
My questions what code should I add to webpack to make it work.?
Thank you

**Comment by klihelp** [comment]
on this.
