### ISSUE TITLE
Module resolution of shared folder modules. Typescript rootDirs

### ISSUE THREAD

**Issue by ktersius** [AngularClass/angular-starter#1439]
For the following directory structure:

    ..src/frontend/...
    ..src/frontend/src/...
    ..src/frontend/config/webpack.common.js
    ..src/shared/src/models/User.ts

I've got my Typescript setup using [rootDirs][1]. This is quite handy because I can have a shared folder for front- and back-end.

This allows me to rewrite an long ugly import statement

    import {User} from "../../../shared/src/models/User";

to this 

    import {User} from "../models/User";

This works well and my TypeScript service is happy and able to resolve all modules etc. The problem comes in with Webpack.

It doesn't seem to look at the tsconfig file for module resolution. So going to the [Webpack 2 documentation][2]. I found the following for resolve.modules.

> Tell webpack what directories should be searched when resolving
> modules.
> 
> Absolute and relative paths can both be used, but be aware that they
> will behave a bit differently.

I have tried configuring the modules :

     modules: [helpers.root('src'), helpers.root('node_modules') , helpers.root( '../shared/src')]

This allows me to use an import statement: 

     import {User} from "models/User"; //Note the missing ../

But now TypeScript doesn't know what type it is any longer, since it breaks away from the rootDirs config. Ideally I would want Webpack and Typescript to be in sync. If I use the long relative import path then webpack and typescript are both happy.

See my [gist][3] of my config files.

Error I get when using '../models/User'

> ERROR in ./src/app/environment.ts Module not found: Error: Can't
> resolve '../models/User' in
> '/home/tersiusk/WebstormProjects/pinkdot2/src/frontend/src/app'  @
> ./src/app/environment.ts 4:0-38  @ ./src/main.browser.ts

  [1]: https://www.typescriptlang.org/docs/handbook/module-resolution.html#virtual-directories-with-rootdirs
  [2]: https://webpack.js.org/configuration/resolve/#resolve-modules
  [3]: https://gist.github.com/ktersius/4deaa6dc55b4bdd22b5f3dc933b77b33

**Comment by Dante-101** [comment]
Did you find a solution to this? 

Ideally the ts compiler should output JS files with import statements containing the correct relative paths from rootDirs.

**Comment by ktersius** [comment]
I got to a reasonable point. I'll show the two tsconfig files. 

Frontend
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "noEmit": true,
    "noEmitHelpers": true,
    "importHelpers": true,
    "strictNullChecks": false,
    "baseUrl": "./",
    "rootDirs": [
      "./src",
      "../shared/src"
    ],
    "paths": {
      "ajv": [
        "node_modules/ajv"
      ],
      "rxjs/Observable": [
        "node_modules/rxjs/Observable"
      ],
      "shared/*" : ["../shared/src/*"],
      "tslib": [ "node_modules/tslib" ]
    },
    "lib": [
      "es2015",
      "dom"
    ],
    "typeRoots": [
      "node_modules/@types"
    ],
    "types": [
      "hammerjs",
      "node"
    ]
  },
  "exclude": [
    "node_modules",
    "dist",
    "src/**/*.spec.ts",
    "src/**/*.e2e.ts"
  ],
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useWebpackText": true
  },
  "angularCompilerOptions": {
    "genDir": "./compiled",
    "skipMetadataEmit": true
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```
shared tsconfig
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "noEmit": true,
    "noEmitHelpers": true,
    "importHelpers": true,
    "strictNullChecks": false,
    "baseUrl": "./",
    "rootDirs": [
      "./src",
      "../frontend"
    ],
    "paths": {
      "ajv": [
        "../frontend/node_modules/ajv"
      ],
      "lodash": [
        "../frontend/node_modules/lodash"
      ],
      "rxjs/*": [
        "../frontend/node_modules/rxjs"
      ],
      "tslib": [ "../frontend/node_modules/tslib" ]
    },
    "lib": [
      "dom",
      "es6"
    ],
    "typeRoots": [
      "node_modules/@types"
    ],
    "types": [
      "hammerjs",
      "jasmine",
      "node",
      "source-map",
      "uglify-js",
      "webpack"
    ]
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules",
    "dist"
  ],
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useWebpackText": true
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}

```

**Comment by Dante-101** [comment]
Thanks for the quick response!

Can you also provide your webpack config? More specifically, how does it resolves rootDirs?

**Comment by ktersius** [comment]
https://pastebin.com/dqkBfcYB

I only added  alias: {'shared': helpers.root('../shared/src')

**Comment by Dante-101** [comment]
Thanks! That worked for now!

**Comment by karolmie1** [comment]
Do karma tests work for you?
I really hate to use  ugly paths like `../../../../../../../`, and I love to use something better, like `app/shared/module`.

The only problem is, that with current config karma don't understand baseUrl, and makes such imports impossible. Do you have any way to work around it?

**Comment by AKlaus** [comment]
Currently, I experience a similar issue. When I replace a reference to a file 
from relative to the current folder: `import { MatterListModel }	from '../models';`
to relative to the root: `import { MatterListModel }	from 'app/models';`
I get error:
```
ERROR in [at-loader] ./src/app/matter/matter.service.ts:16:21
    TS2304: Cannot find name 'MatterListModel'.
```
In the "Process Monitor" I could clearly see that the path is attempting to be resolved into the following:

1. `node_modules/app/models` (_failed_)
2. `node_modules/@types/app/models` (_failed_)
3. `node_modules/app/models` (_failed_)
4. `src/app/models` (_successful!_)

And these four attempts are absolutely expected according to the WebPack config.

What puzzles me is why it fails with `ERROR in [at-loader]`? **Is there a place I need to fix in order to use paths relative to the root?**
