### ISSUE TITLE
It's no longer allowed to omit the '-loader' suffix when using loaders. You need to specify 'css-loader' instead of 'css

### ISSUE THREAD

**Issue by soumyagangamwar** [AngularClass/angular-starter#1444]
I am getting this error while including [bootstrap3] with less support,
Please help me to solve this issue
![css loader](https://cloud.githubusercontent.com/assets/16099491/22420642/638f9ae4-e709-11e6-98db-6d6fbf2890b3.png)

**Comment by mbenzenhoefer** [comment]
What is your less loader definition looking like? As the error says, add "-loader" to the css like it is in config/webpack.common.js. 

```js
{
  test: /\.less$/,
  use: ['to-string-loader', 'css-loader', 'less-loader']
}
```

**Comment by soumyagangamwar** [comment]
Even I add loader in webpack.coomon.js still I am getting error
