### ISSUE TITLE
css sourcemap

### ISSUE THREAD

**Issue by m3l7** [AngularClass/angular-starter#1460]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

hello,
my webpack is configured for css as follows:

        {
          test: /\.css$/,
          loaders: ['to-string-loader', 'css-loader?sourceMap']
        },

however, in the browser I can't see any references to the source files:

![img-2017-02-02-114705](https://cloud.githubusercontent.com/assets/1064749/22546468/751b3224-e93d-11e6-84e2-36c426c9691c.png)

the same happens with the sass-loader

**Comment by Marc-Hansen** [comment]
same happens for me. The sourcemaps for the main styles work but not for the styles from the components. Seems like angular is not putting them to the style tags

**Comment by asadsahi** [comment]
@gdi2290 any reason if it was closed? Is there a way to enable sourcemaps for global and component styles?
