### ISSUE TITLE
Webcomponents/Polymer

### ISSUE THREAD

**Issue by ITServicesAM** [AngularClass/angular-starter#1463]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
I´m not sure if it is a bug or a feature reqquest.

* **What is the current behavior?**
The current behavior is, that webcomponents on browsers where the polyfills kick in are not working.
Can you give me a advise how to change the configuration of the project to load the main module just after the Webcomponentsready Event?

* **What is the expected behavior?**
I can bundle my application with webcomponents/polymer for development and for production. Even with aot enabled.

* **What is the motivation / use case for changing the behavior?**
Webcomponents/polymer are just so much nicer components to build a state of the art web application and don´t have to to the boilerplet again and again.

* **Please tell us about your environment:**

- Angular version: 2.4.3
- Browser: [all browsers that do not natively support webcomponents ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by katallaxie** [comment]
@ITServicesAM Have not tested that yet, could you provide some code? So, could your share a repo?

**Comment by ITServicesAM** [comment]
Here is my repo: [Repo](https://github.com/ITServicesAM/angular_2_polymer)

the webpack.common.js is changed to load a new main.ts if not aot
the main.ts loads the main.browser.ts when the event "webcomponentsready" occurs.

This is just a try to get it working. If you have a better idea to get this working, I would love to here it.

In the app.module.ts, index.html and home.component.html are the changes for polymer
([Polymer Docs](https://vaadin.com/docs/-/part/elements/angular2-polymer/ng-cli-webpack.html))

In the quick start section of the readme of the repo you can find instructions how to install this project

**Comment by otiteca** [comment]
Hi,

I do have Polymer elements working fine.

1. create a main-polymer.ts that contains: document.addEventListener('WebComponentsReady', () => {require('./main.browser.ts')});
2. your webpack.config.ts or webpack.common.ts may then contain:    entry: {

      'polyfills': './src/polyfills.browser.ts',
      'vendor':    './src/vendor.browser.ts',
      'main':      './src/main-polymer.ts'
    },

That's it.
Then you're sure that your polymer elements are loaded and working before your app get loaded.
I hop that's what you where looking for.

**Comment by shlomiassaf** [comment]
@otiteca We don't have a vendor file anymore.

@ITServicesAM You are setting up the polyfil in https://github.com/ITServicesAM/angular_2_polymer/blob/master/src/main.browser.aot.ts which is for AOT only.

You should also set it here: https://github.com/ITServicesAM/angular_2_polymer/blob/master/src/main.browser.ts

Using `require` might lead to unexpected AOT compilation result, its not 100% but it's not a good practice anyway.

If my suggestion isn't working it means that the main file can init before polymer is ready, even if  bootstrap not initialized...

lets see

**Comment by ITServicesAM** [comment]
do you have a code example for me? I set the polyfil for the main.browser.ts not directly, I set it in the webpack.common.ts there I have a entry point for non aot builds which requires the main.browser.ts but this is not working.
