### ISSUE TITLE
Change config folder structure and npm task related

### ISSUE THREAD

**Issue by michaeljota** [AngularClass/angular-starter#1468]
* **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [x] question about the decisions made in the repository

* **What is the current behavior?**

The config folder has config files for every component in it. Also, some task in npm scripts are repetitive, and can be handle in a better way using webpack env argument. 

* **What is the wanted/proposed behavior?**

I fork this project to add some custom things, but in the way I manage to structure in a more scalable way (according to me). And I would like to propose that change in for the config folder in this project. I would made a pull request, but I want to know if this is something you would like. 

`config structure`

![captura de pantalla 72](https://cloud.githubusercontent.com/assets/10507776/22598199/045561dc-ea09-11e6-8cba-aea44e6997e3.png)

The webpack folders have an index that resolve and return the proper configuration.

* **What is the motivation / use case for changing the behavior?**

Adding additional build scenarios aren't intuitive and it's hard to think how exactly do it.

* **Please tell us about your environment:**

- Angular version: 2.4.x
- Browser: [all]
- Node: 6.9.4
- npm: 3.10.10

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by JoniJnm** [comment]
I think some refactor should be done too:

# Rename webpack.*.ts files

Webpack should have 3 config files:

1. webpack.dev.js: development mode: no minimize files, create sourcemap...)
2. webpack.test.js: for unit testing
3. webpack.build.js: build aot or jit

The file webpack.common.js should be renamed too because it's not used in webpack.dev.js. It could be webpack.helpes.js or webpack.utils.js and it should have functions that could be used in the other config files to inject some plugin, config or whatever.

# Create real eviroment config files

The project should have different enviroment config files:

* config.dev.js
* config.pre.js
* config.pro.js
* config.github.js

In these files the user could set the API URL, the domain used, the color of the topbar or what they want.

DefinePlugin should add these config to use in .ts files. Something like:

```
//save config from process.env in a dictionary (function in webpack.utils.js)

const keys = ['ENV', 'API_URL', 'PUBLIC_KEY', 'USE_SOME_FEATURE'];
let config = {};
for (var i=0; i<keys.length; i++) {
	let key = keys[i]
	try {
		config[key] = JSON.parse(process.env[key]);
	}
	catch(e) {
		config[key] = process.env[key];
	}
}
// TODO: merge config with a base enviroment config (dev, pre, prod...)


// set defineplugin

new DefinePlugin({
  'ENV': config['ENV'],
  'process.env': Object.keys(config).reduce((acum, key) => {
	  acum[key] = JSON.stringify(config[key]);
	  return acum;
  }, {})
})
```

And the project should have one config.ts file. The user should not use `process.env`. A config.ts file that could be:

```
export const ENV: string = process.env.ENV;
export const API_URL: string = process.env.API_URL;
export const PUBLIC_KEY: string = process.env.PUBLIC_KEY;
export const USE_SOME_FEATURE: boolean = process.env.USE_SOME_FEATURE;
```

**Comment by michaeljota** [comment]
I like your suggest about the management of the ENV variable. However, I think instead of using `process.env` it would be better to use Webpack own `env` variable. It's setteable alike, and I think it's better to understand. Also, you would not need to parse anything, cause Webpack can handle that itself. 

My current workflow works with the `env` variable. 

`Webpack folders` 
![captura de pantalla 74](https://cloud.githubusercontent.com/assets/10507776/22648076/336abe42-ec4b-11e6-901f-76211aedea02.png)

`config/webpack/index.js`: Resolves the `target` for webpack build according to env variable. 
![captura de pantalla 75](https://cloud.githubusercontent.com/assets/10507776/22648077/37c63a2a-ec4b-11e6-8d81-b4c834977550.png)

**Comment by michaeljota** [comment]
An structure like this, would also have some benefits over current implementation. See this function for example:

```js
function getWebpackConfigModule(options) {
  if (options.githubDev) {
    return require('../webpack.dev.js');
  } else if (options.githubProd) {
    return require('../webpack.prod.js');
  } else {
    throw new Error('Invalid compile option.');
  }
}
```

If the production flag, it's set in the env, or even using npm config scripts, it would just be requesting to `webpack/browser`, and it would resolve itself to the most apropiarte config regardless the request.

**Comment by michaeljota** [comment]
@JoniJnm I made a PR about this. I took your idea about separate the options for the Webpack. Also, the configuration it's being setting with the `env` variable. (I try the NPM script config, but Webpack does not get along with this, see: webpack/webpack#4221).
