### ISSUE TITLE
Vanilla Install: Errors Starting NPM

### ISSUE THREAD

**Issue by brandonMetro** [AngularClass/angular-starter#1472]
info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@4.1.2
3 info using node@v6.9.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular2-webpack-starter@5.4.1~prestart: angular2-webpack-starter@5.4.1
6 silly lifecycle angular2-webpack-starter@5.4.1~prestart: no script for prestart, continuing
7 info lifecycle angular2-webpack-starter@5.4.1~start: angular2-webpack-starter@5.4.1
8 verbose lifecycle angular2-webpack-starter@5.4.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-webpack-starter@5.4.1~start: PATH: C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Administrator\Source\Repos\SPAngular2\angular2-webpack-starter\node_modules\.bin;C:\Program Files (x86)\Parallels\Parallels Tools\Applications;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft Office Servers\15.0\Bin\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Microsoft SQL Server Migration Assistant for MySQL\bin\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\Administrator\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Administrator\AppData\Roaming\npm
10 verbose lifecycle angular2-webpack-starter@5.4.1~start: CWD: C:\Users\Administrator\Source\Repos\SPAngular2\angular2-webpack-starter
11 silly lifecycle angular2-webpack-starter@5.4.1~start: Args: [ '/d /s /c', 'npm run server:dev' ]
12 silly lifecycle angular2-webpack-starter@5.4.1~start: Returned: code: 1  signal: null
13 info lifecycle angular2-webpack-starter@5.4.1~start: Failed to exec start script
14 verbose stack Error: angular2-webpack-starter@5.4.1 start: `npm run server:dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular2-webpack-starter@5.4.1
16 verbose cwd C:\Users\Administrator\Source\Repos\SPAngular2\angular2-webpack-starter
17 error Windows_NT 6.3.9600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.5
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error angular2-webpack-starter@5.4.1 start: `npm run server:dev`
22 error Exit status 1
23 error Failed at the angular2-webpack-starter@5.4.1 start script 'npm run server:dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-webpack-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run server:dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-webpack-starter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-webpack-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by indiecore-fm** [comment]
I am having this same issue
