### ISSUE TITLE
Is it possible to show code coverage as Zero for files for which spec files are not even created.

### ISSUE THREAD

**Issue by VivekPMenon** [AngularClass/angular-starter#1482]
* **I'm submitting a ...**
[ ] bug report
[X ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Test coverage doesn't show files for which specs are not written. When team members don't create specs for new files, it don't get caught in coverage report.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
Not a bug

* **What is the expected behavior?**
If the file for which specs are not written are also shown in the coverage with 0 coverage, that would be nice.

* **What is the motivation / use case for changing the behavior?**
[https://github.com/karma-runner/karma-coverage/issues/125](url). I tried to implement this on my own, but had no luck with it. Any help/advice would be greatly appreciated. 

* **Please tell us about your environment:**

- Angular version: 2.4.6
- Browser: [all]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by antonovicha** [comment]
https://github.com/gotwarlost/istanbul/issues/112

> The --include-all-sources option is an option for the command cover. You can see this by typing in istanbul help cover and it will list the options for this command.

May be this helps?

**Comment by abierbaum** [comment]
@VivekPMenon Based upon what I saw here: https://github.com/webpack-contrib/istanbul-instrumenter-loader

It looks like the key is to make the spec-bundle import all the other modules you want to get coverage on.  I tried this out in our project by adding the following lines to the spec-bundle.js:

```
var sourceModules = require.context('../src', true, /\.module\.ts/);
var code_modules = requireAll(sourceModules);
```

This worked pretty well for us because we use a naming pattern of xxx.module.ts for all of our NgModule classes.  Those files in turn pretty much import every other ts module code file that we want to get coverage on. 

Hope this helps.

**Comment by VivekPMenon** [comment]
thanks much for the suggestions @antonovicha @abierbaum . I am going to try this one out today and let you folks know..

**Comment by nottinhill** [comment]
We need a solution that works for Ionic 3+ AoT as well.

**Comment by kopach** [comment]
Hi there. For anyone still interested in this topic, Here is a tool, which helps to add untested files to coverage report. It works fine with both JavaScript and TypeScript files. https://github.com/kopach/karma-sabarivka-reporter
