### ISSUE TITLE
404

### ISSUE THREAD

**Issue by ileler** [AngularClass/angular-starter#1484]
Failed to load resource: the server responded with a status of 404 (Not Found)
main.browser.ts:25Failed to load home.component.html

**Comment by DanielMcAssey** [comment]
Getting this as well, seems like raw-loader isnt working with the newest changes.

**Comment by DanielMcAssey** [comment]
Related issue https://github.com/TheLarkInn/angular2-template-loader/pull/51

**Comment by antonovicha** [comment]
@DanielMcAssey Thank you. Fixing version of "angular2-template-loader" package to "0.6.0" solved that issue for us.

**Comment by ileler** [comment]
@DanielMcAssey Thanks. solved...

**Comment by jano42** [comment]
I still have problem.

To reproduce, just build and start developement version.

This problem do not appear in prod version

**Comment by zaalion** [comment]
Thanks. Resolved!

**Comment by shlomiassaf** [comment]
This should be automatically fixed by greenkeepr once the new version of the loader is out
