### ISSUE TITLE
tslint-loader: disable for node_modules

### ISSUE THREAD

**Issue by sentika** [AngularClass/angular-starter#1505]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
tslint-loader show warnings for node_modules folder

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
Install any deps with tslint warnings. 

I suggest exclude node_modules for tslint-loader in webpack.dev.js file via

`exclude: [/\.(spec|e2e)\.ts$/, helpers.root('node_modules')]`

**Comment by sebelga** [comment]
Thanks for the fix! Had a lot of tslint warnings! :)

**Comment by yhermans** [comment]
You can also exclude the node-modules folder in the lint property in the .angular-cli.json file.
Source: [https://github.com/angular/angular-cli/wiki/angular-cli](https://github.com/angular/angular-cli/wiki/angular-cli)
example:
"lint": [
    {
      "project": "src/tsconfig.app.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "src/tsconfig.spec.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "e2e/tsconfig.e2e.json",
      "exclude": "**/node_modules/**"
    }
  ],

**Comment by TheOriginalJosh** [comment]
for any one referenceing this I found that you need to exclude to bee in this format 

```
	"lint": [
		{
			"project": "src/tsconfig.app.json",
			"exclude": "**/node_modules/**/*"
		},
		{
			"project": "src/tsconfig.spec.json",
			"exclude": "**/node_modules/**/*"
		},
		{
			"project": "e2e/tsconfig.e2e.json",
			"exclude": "**/node_modules/**/*"
		}
```
