### ISSUE TITLE
Env metadata cannot be accessed in index.html

### ISSUE THREAD

**Issue by pawelkondraciuk** [AngularClass/angular-starter#1506]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
I am reporting bug.

* **What is the current behavior?**
Metadata from another environment can't be accessed inside index.html.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via

1. Clone repository
2. Inside webpack.dev.js add key to METADATA section, for example:
```javascript
const METADATA = webpackMerge(commonConfig({env: ENV}).metadata, {
  host: HOST,
  port: PORT,
  ENV: ENV,
  HMR: HMR,
  MYKEY: 'MYVALUE'
});
```
3. Inside index.html replace
```javascript
<app>
    Loading...
  </app>
```
with
```
  <%= htmlWebpackPlugin.options.metadata.isDevServer %>
  <%= htmlWebpackPlugin.options.metadata.MYKEY %>
```
4. run `npm start` - it should use dev environment

As you can see only isDevServer is displayed as true.  If you add MYKEY inside `webpack.common.js` it works fine but you are limited to one config per project.

Also following statement is always false because HMR is placed inside webpack.dev.ts that cannot be referenced here

```
        <% if (htmlWebpackPlugin.options.metadata.isDevServer && htmlWebpackPlugin.options.metadata.HMR !== true) { %>
            <script src="/webpack-dev-server.js"></script>
        <% } %>
```

* **What is the expected behavior?**
It should use metadata values from proper environment.

* **What is the motivation / use case for changing the behavior?**
Providing different API keys across different environments inside index.html

* **Please tell us about your environment:**
`git clone https://github.com/AngularClass/angular2-webpack-starter`

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
To "fix" that issue I need to copy HtmlWebpackPlugin from common and paste it inside each environment config.

**Comment by gizm0bill** [comment]
`commonConfig({env: ENV}).metadata` is actually `undefined`, and actually webpack config doesn't have any metadata property. no idea why it's there...
