### ISSUE TITLE
As can I show errors on overlay in the browser?

### ISSUE THREAD

**Issue by phenrigomes** [AngularClass/angular-starter#1509]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by tytskyi** [comment]
@phenrigomes you need to update `webpack-dev-server` and tweak 2 files.

Details:

Install webpack-dev-server@2.3.0 or higher,

In `webpack.dev.js`: 

```
devServer: {
    overlay: true,
    // options that you already have
}
```


In `webpack.common.js`:

```
{
  loader: 'awesome-typescript-loader',
  options: {
    silent: true,
     // options that you already have
  }
}
```

**Comment by phenrigomes** [comment]
Great! Thanks @tytskyi.

**Comment by yaroslavya** [comment]
Doesnt work for me. Made a fresh clone of the repo. Then changed the 2 files mentioned by @tytskyi and made sure my version of the webpack-dev-server is 2.4.1. Can see the error if I open the console but dont see the overlay. Tried with both, throwing the error from the ngOnInit and doing something disruptive in the template. Does anyone have the example of AngularClass with the overlay configured?

**Comment by yaroslavya** [comment]
Sorry, my bad, was the other issue that prevented it from working. With this setup its working.

**Comment by tytskyi** [comment]
@phenrigomes please close an issue. I believe this will continue to work. 

However theoretically it slows down build time And here is why (it makes type checking synchronous): https://github.com/s-panferov/awesome-typescript-loader/issues/365#issuecomment-277596135
