### ISSUE TITLE
TreeShaking is not exporting services when creating a npm library

### ISSUE THREAD

**Issue by acostaf** [AngularClass/angular-starter#1540]
Hi Guys

I am creating a shared library using this library but a I found that when services are left out by the TreeShaking since there are not used neither imported or declared on my ngModule.

How Can I exclude a folder from the treeShaking code.

Best Regards

**Comment by shlomiassaf** [comment]
This repository is not intended for library creation.

Webpack can only create UMD bundles but angualr2 libraries require ESM modules as well, for AOT compilation.

This is done by TS and the angular compiler-cli

See [this](https://github.com/shlomiassaf/ngc-webpack/issues/7#issuecomment-279292758) for more detailed explanation.
