### ISSUE TITLE
TS2346: Supplied parameters do not match any signature of call target.

### ISSUE THREAD

**Issue by mafina1984** [AngularClass/angular-starter#1549]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)
Hi,

I've tried to access the angularclass.com support links to make sure before i post this one if this is a bug or not but with no success.

I wonder why when i clone this repository and do npm intall and then when i try to inject any simple service 
into the home or about component I get this error 
"
[at-loader] Checking finished with 1 errors
[at-loader] compiled\src\app\home\home.component.ngfactory.ts:36:20
    TS2346: Supplied parameters do not match any signature of call target.
"

here is my test.service.ts file 
"
import { Injectable } from '@angular/core';

@Injectable()
export class Test {
    constructor() {

    }
}
"
this is the home.component.ts modification i make
import { Test } from '../services/test.service';

  providers: [    
    AppState,
    Title,
    Test
  ],

  // TypeScript public modifiers
  constructor(     
    public appState: AppState,    
    public title: Title,
    private test:Test
  ) {}
"
and simply i cannot get away from the error I'm getting.

when i take a look at the compiled\src\app\home\home.component.ngfactory.ts:36:20 file
i see this :
"
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.HomeComponent(p0,p1);
  }
"
So obviously the constructor parameter signature is not right and I cannot find the spot where I can fix this and I wonder if this is some sort of a bug or something else ?

**Comment by bobrosoft** [comment]
Have the same issue. I found it related to `@angularclass/hmr` package and custom bootstrapping app has because of HMR. Looks as it require `public appState: AppState` to be passed there always. In my project I'm using `@ngrx/store` and not require HMR in a way AngularClass have it by default, so removed.
