### ISSUE TITLE
Import 3rd party css dependency

### ISSUE THREAD

**Issue by avkonst** [AngularClass/angular-starter#1551]
This is minor issue, but you may find it important to track it. The docs importing external css https://github.com/AngularClass/angular2-webpack-starter#external-stylesheets should change "@import 'bootstrap/scss/bootstrap.scss';" to "@import '~bootstrap/scss/bootstrap.scss';". It does not compile without this ~ mark, at least for leaflet.css dependency.

Regards,
Andrey

**Comment by brianrt** [comment]
This works, but there seems to be a pathing issue with font-awesome when it tries to resolve the *fonts* folder.

**Comment by fmontes** [comment]
Shouldn't 

```import "../../node_module/xxx/xxx.css"```

in ```app.module.ts``` works out of the box? it's not working for me.
