### ISSUE TITLE
Possibility to translate title

### ISSUE THREAD

**Issue by kresogalic8** [AngularClass/angular-starter#1554]
Hey guys, I'm just wondering is there any possibility to translate page title? I am using [ng2-translate](https://github.com/ngx-translate/core)

This is what I need translated 

`<title><%= htmlWebpackPlugin.options.title %></title>`

**Comment by glendaviesnz** [comment]
@kresogalic8  - have a look at https://angular.io/docs/ts/latest/cookbook/set-document-title.html - you will need to use the title service in one of your components or services to do this, so something like

```javascript
import { TranslateService } from '@ngx-translate/core';
export class AppComponent {
    public constructor(
        private titleService: Title,
        private translate: TranslateService
    ) {
        translate.get('APP_TITLE').subscribe((newTitle: string) => {
            this.titleService.setTitle(newTitle);
        });
    }
}
```
Haven't tested this at all though so may need some tweaking.
