### ISSUE TITLE
sass-loader: Build AoT Module build failed: No input specified: provide a file name or a source string to process

### ISSUE THREAD

**Issue by vincent-cm** [AngularClass/angular-starter#1555]
[X] bug report

ERROR in ./~/css-loader!./~/sass-loader/lib/loader.js!./config/resource-override.js
Module build failed: No input specified: provide a file name or a source string to process
 @ ./src/app/components/home/xxxxxx.scss 2:21-134 (After removing this file, I got same issue for another scss)
 @ ./src/app/components/home/home.ts
 @ ./compiled/src/app/app.module.ngfactory.ts
 @ ./src/main.browser.aot.ts

Build AoT success but on checking resources in the final process, the npm quit with this error. Now sass-loader is 6.0.0. Changed to 4.1.1 fixed the problem.

The ExtractTextPlugin may be the problem in some google search but after hiding the relative config in webpack.prod.js, the issue exits.

**Comment by MangeshPimpalkar** [comment]
+1

**Comment by admosity** [comment]
Can confirm that changing back to 4.1.1 fixes the problem.

**Comment by MangeshPimpalkar** [comment]
The issue is raised on sass-loader also
https://github.com/webpack-contrib/sass-loader/issues/373

**Comment by DBosley** [comment]
Adding a note here, I get this error if the scss file is empty. If I add something like `body {}` to the file, the compilation works fine

**Comment by vincent-cm** [comment]
which file you are referring to?

**Comment by DBosley** [comment]
@vincent-cm The errors I get point to the scss files referenced in the styleUrls property of the Component class decorator. When those scss files are empty, I can't even start up the webpack dev server. When I add `body {}` (or any styles at all) to the file, the webpack dev server compiles everything fine and it runs. But AOT does not work at all. All scss files error when building for AOT.

**Comment by DBosley** [comment]
After trying a few things out I started looking at the angular2-template-loader. I removed it from my *.ts file loaders and now my AOT build works just fine. I don't see anything affected by this change.

Original .ts file loader config:
```
{
    test: /\.ts$/,
    use: [{
            loader: '@angularclass/hmr-loader',
            options: {
                pretty: !isProd,
                prod: isProd
            }
        },
        { // MAKE SURE TO CHAIN VANILLA JS CODE, I.E. TS COMPILATION OUTPUT.
            loader: 'ng-router-loader',
            options: {
                loader: 'async-import',
                genDir: 'pkg/compiled',
                aot: AOT
            }
        },
        {
            loader: 'awesome-typescript-loader',
            options: {
                configFileName: 'tsconfig.webpack.json'
            }
        },
        {
            loader: 'angular2-template-loader'
        }
    ],
    exclude: [/\.(spec|e2e)\.ts$/]
},
````

new config:
```
{
    test: /\.ts$/,
    use: [{
            loader: '@angularclass/hmr-loader',
            options: {
                pretty: !isProd,
                prod: isProd
            }
        },
        { // MAKE SURE TO CHAIN VANILLA JS CODE, I.E. TS COMPILATION OUTPUT.
            loader: 'ng-router-loader',
            options: {
                loader: 'async-import',
                genDir: 'pkg/compiled',
                aot: AOT
            }
        },
        {
            loader: 'awesome-typescript-loader',
            options: {
                configFileName: 'tsconfig.webpack.json'
            }
        }
    ],
    exclude: [/\.(spec|e2e)\.ts$/]
},
```

**Comment by Daeluse** [comment]
I've also noticed that this error only occurs on UNIX systems. My build will compile in Windows without issue, but will throw this error on a Mac or Linux Box.

**Comment by DBosley** [comment]
@Daeluse I'm on Windows and having this issue.

**Comment by Daeluse** [comment]
@DBosley Interesting, on Windows I do get the error if the SASS file is blank, but on Mac/Linux I get the error no matter what.

**Comment by M1strall** [comment]
Upgrading to 6.0.5 fixed problem for me as well
