### ISSUE TITLE
fresh repo build:prod not working

### ISSUE THREAD

**Issue by lxp1991** [AngularClass/angular-starter#1556]
## **[X] bug report**

I download a fresh copy and try to build it without any modification, then I opened the index.html under dist folder, it showed me bunch of ERR_FILE_NOT_FOUND errors in the console. I can see it's pointing to C:/assets to find its static contents. It should be finding content under current directory.

I also tried other building commands (build:dev, build:aot), it still gave me the same error.

## **Steps to reproduce:**
1. git clone this repo
2. npm install
3. npm run build:prod
4. open index.html under dist folder
5. page not loading and FILE_NOT_FOUND errors in console

## **Environment:**
Chrome:	56.0.2924.87 (Official Build) (32-bit)
Nodejs: 6.9.1
npm: 3.10.8

**Comment by AndreaFox93** [comment]
Got it working by searching into index.html
 **<base href="<%= htmlWebpackPlugin.options.metadata.baseUrl %>">** and add a dot like this <base href=".<%= htmlWebpackPlugin.options.metadata.baseUrl %>">
