### ISSUE TITLE
Watch files compile error (TypeError: Cannot convert undefined or null to object)

### ISSUE THREAD

**Issue by raphaelluchini** [AngularClass/angular-starter#1558]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ *] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Report a Bug

* **What is the current behavior?**
I've tried a fresh install and ran ``npm run start:dev:hmr``. When I edit a file, the watcher throw a error

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
```
git clone --depth 1 https://github.com/angularclass/angular2-webpack-starter.git

cd angular2-webpack-starter

npm install

npm run server:dev:hmr
```

* **What is the expected behavior?**
Watch the files and provide a updated version on the browser

* **Please tell us about your environment:**

- OSX Sierra
- Node v6.9.5
- NPM 3.10.10
- Angular version: 2.4.6
- Browser: [all ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

```
webpack: Compiling...
webpack: wait until bundle finished: /vendor.dll.js
webpack: wait until bundle finished: /polyfills.bundle.js
webpack: wait until bundle finished: /vendor.bundle.js
webpack: wait until bundle finished: /main.bundle.js
DLL: Checking if DLLs are valid.
DLL: All DLLs are valid.
TypeError: Cannot convert undefined or null to object
at Compiler.<anonymous> (/Users/raphaelluchini/workplace/app/node_modules/awesome-typescript-loader/src/instance.ts:334:37)
at next (/Users/raphaelluchini/workplace/app/node_modules/tapable/lib/Tapable.js:140:14)
at Compiler.compilerInvalid (/Users/raphaelluchini/workplace/app/node_modules/webpack-dev-middleware/lib/Shared.js:144:5)
at next (/Users/raphaelluchini/workplace/app/node_modules/tapable/lib/Tapable.js:140:14)
at Compiler.compiler.plugin (/Users/raphaelluchini/workplace/app/node_modules/webpack/lib/CachePlugin.js:32:5)
at next (/Users/raphaelluchini/workplace/app/node_modules/tapable/lib/Tapable.js:140:14)
at /Users/raphaelluchini/workplace/app/node_modules/src/DllBundlesPlugin.ts:73:20
at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by raphaelluchini** [comment]
Seems has been fixed! 

It was a bug on awesome-typescript-loader dependency!

See: https://github.com/s-panferov/awesome-typescript-loader/pull/379

**Comment by margaris23** [comment]
Yes it does. Nice!
