### ISSUE TITLE
vendor.dll.js.map

### ISSUE THREAD

**Issue by gviligvili** [AngularClass/angular-starter#1571]
* **I'm submitting a ...**
[ X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**

Can't find vendor.dll.js.map, I don't know why it wasn't created.

* **Please tell us about your environment:**

- Angular version: 5.4.1
- Browser: [Chrome 56 ]
- OS: OSX El Capitan

* **Other information**
I've built a project on top of your seed, and I keep updated it.
Most of the config (and the environment) are the same, with small tweaks.

When updating to ver 5.4.1 (current ver), The repo works just fine.
But after updating my project, I rn npm run server and I get this error :  
```
Html Webpack Plugin:
  Error: HtmlWebpackPlugin: could not load file /Users/talgvili/Desktop/ATN/mySeed/Angular-2-Redux-Webpack-Seed/dll/vendor.dll.js.map
  
  - index.js:313 
    [Angular-2-Redux-Webpack-Seed]/[html-webpack-plugin]/index.js:313:27
  
  - util.js:16 tryCatcher
    [Angular-2-Redux-Webpack-Seed]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:510 Promise._settlePromiseFromHandler
    [Angular-2-Redux-Webpack-Seed]/[bluebird]/js/release/promise.js:510:31
  
  - promise.js:567 Promise._settlePromise
    [Angular-2-Redux-Webpack-Seed]/[bluebird]/js/release/promise.js:567:18
  
  - promise.js:612 Promise._settlePromise0
    [Angular-2-Redux-Webpack-Seed]/[bluebird]/js/release/promise.js:612:10
  
  - promise.js:687 Promise._settlePromises
    [Angular-2-Redux-Webpack-Seed]/[bluebird]/js/release/promise.js:687:18
  
  - async.js:133 Async._drainQueue
    [Angular-2-Redux-Webpack-Seed]/[bluebird]/js/release/async.js:133:16
  
  - async.js:143 Async._drainQueues
    [Angular-2-Redux-Webpack-Seed]/[bluebird]/js/release/async.js:143:10
  
  - async.js:17 Immediate.Async.drainQueues
    [Angular-2-Redux-Webpack-Seed]/[bluebird]/js/release/async.js:17:14
  
```

I noticed that at the AngularClass project, at ./dll/ there is a vendor.dll.js, and **vendor.dll.js.map**

But in my project, **there is only vendor.dll.js**.

What I need to do so it will create the .map file?  I tried to investigate it but couldn't find out why I can't get to work.
(All dependencies in package.json are the same version as the the AngularClass project, node and npm version can't be the problem because it's already working in the original project).

**Comment by perara** [comment]
Having this issue aswell

**Comment by waylander47** [comment]
when I comment this two lines 
{ filepath: helpers.root(`dll/${DllBundlesPlugin.resolveFile('polyfills')}`) },
{ filepath: helpers.root(`dll/${DllBundlesPlugin.resolveFile('vendor')}`) }
in webpack.dev.js I can run the application without error but nothing is showing.

Any suggestions to point me in the right direction ? I'm new to Angular 2

**Comment by AymenSlimi** [comment]
Hi,

I solve it by creating emty files 'polyfills.dll.js.map' and 'vendor.dll.js.map' in dll folder and it works

Regards

**Comment by FredBesterwitch** [comment]
Same error , when running npm start

ERROR in   Error: HtmlWebpackPlugin: could not load file ..\ng2-admin\dll\vendor.dll.js  .map

  - index.js:313
    [ng2-admin]/[html-webpack-plugin]/index.js:313:27

  - util.js:16 tryCatcher
    [ng2-admin]/[bluebird]/js/release/util.js:16:23

  - promise.js:510 Promise._settlePromiseFromHandler
    [ng2-admin]/[bluebird]/js/release/promise.js:510:31

  - promise.js:567 Promise._settlePromise
    [ng2-admin]/[bluebird]/js/release/promise.js:567:18

  - promise.js:612 Promise._settlePromise0
    [ng2-admin]/[bluebird]/js/release/promise.js:612:10

  - promise.js:687 Promise._settlePromises
    [ng2-admin]/[bluebird]/js/release/promise.js:687:18

  - async.js:133 Async._drainQueue
    [ng2-admin]/[bluebird]/js/release/async.js:133:16

  - async.js:143 Async._drainQueues
    [ng2-admin]/[bluebird]/js/release/async.js:143:10

  - async.js:17 Immediate.Async.drainQueues
    [ng2-admin]/[bluebird]/js/release/async.js:17:14

**Comment by FredBesterwitch** [comment]
fixed as suggested by AymenSlimi 

Thanks Bro

**Comment by waylander47** [comment]
Thanks @AymenSlimi ! :)

**Comment by acostaf** [comment]
+1

**Comment by loxy** [comment]
The problem is a wrong configuration of add-asset-html-webpack-plugin (https://github.com/SimenB/add-asset-html-webpack-plugin)
So, either you generate some source maps or turn it off (parameter: includeSourcemap, default: true)

**Comment by gam80** [comment]
includeSourcemap default: true, set false can solve this issue. Thanks @loxy
