### ISSUE TITLE
Issue with bootstrap 4

### ISSUE THREAD

**Issue by sparrowonfire** [AngularClass/angular-starter#1580]
I have been following the guide for how to install bootstrap 4 and i have been getting an error every time i try to install it. I have followed this guide https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-use-Bootstrap-4-and-Sass-(and-jQuery) from start to finish 4 times with a unmodified version of the repo.

The error i am getting is

```
ERROR in ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js
Module not found: Error: Can't resolve 'postcss-loader' in 'C:\Users\whunt\Documents\code\Angular2\payclaims-v4\node_modules\bootstrap-loader'
 @ ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js 1:21-1143
 @ ./~/bootstrap-loader/loader.js
 @ multi (webpack)-dev-server/client?http://localhost:3000 bootstrap-loader

ERROR in ./src/styles/styles.scss
Module build failed: 
/* this file will be extracted to main dist folder and is imported in index.html */
/* This file is for setting global styles  */
@import 'variables';

nav {
  margin-top: 16px;
}

nav a {
  background-color: $nav-button-color;
  color: white;
  padding: 8px 16px;
  margin: 8px;
  vertical-align: middle;
  line-height: 1.25;
  text-align: center;
  text-decoration: none;
  border-radius: 4px;
}
^
      Invalid CSS after "...load the styles": expected 1 selector or at-rule, was "var content = requi"
      in C:\Users\whunt\Documents\code\Angular2\payclaims-v4\src\styles\styles.scss (line 1, column 1)
 @ ./src/app/app.module.ts 21:0-31
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts

```

I'm not sure if i'm missing something in the guide or if this is an actual issue.

**Comment by simonmcl** [comment]
@sparrowonfire I just went through the same. I ran:

`npm install --save postcss-loader`

Which resolved that issue. I ran into a further issue which required I remove the `raw-loader` for css files. This fixed my bootstrap css, but the latest webpack starter seems to have broken my component css. I'm about to open an issue, would be great if you could test to see if you see the same
