### ISSUE TITLE
missing image files in npm plugins if build with aot

### ISSUE THREAD

**Issue by vincent-cm** [AngularClass/angular-starter#1587]
It should change the file name to something like "77aeaa52715b898b73c74d68c630330e.png" and bundled in final js without aot flag.
With aot flag, the file is missing from dist/ folder but final js bundle still referencing those files.

Those files are coming from ng2-* plugins or external js plugins which CSS file is imported directly to components such as ng2-ui-switch, icheck.js, bootstrap colorpicker...

The issue may be fixed by omitting aot and copy the generated images to the aot dist folder as a temporary workaround.

**Comment by bmayen** [comment]
Perhaps related to https://github.com/AngularClass/angular2-webpack-starter/issues/1406

Try using `"ngc-webpack": "^1.2.0"`.
