### ISSUE TITLE
How to include jQuery UI

### ISSUE THREAD

**Issue by skol-pro** [AngularClass/angular-starter#1588]
[Chat: AngularClass.slack](http://angularclass.com/member-join/) not found...

* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Ask a question

* **What is the current behavior?**
I'd like to integrate jQuery UI to my project, but I can't find any solutions.

**Comment by astroanu** [comment]
I think its better to ditch jquery components altogether, there are so many non jquery, angular directives that does the job for you.

**Comment by skol-pro** [comment]
Well actually I need it to integrate a angular component that uses jQuery UI... :-(

**Comment by zigzag95** [comment]
Please stop using jQuery. It makes no sense with ng

**Comment by skol-pro** [comment]
I totally agree, but sometimes there is no other practical and fast solutions... And that's not the point of the question.

**Comment by astroanu** [comment]
Well, what you CAN do is include ui components needed by that particular plug in to your project and use it. 

This shouldn't be a feature request coz it will mess up this boilerplate repo.

**Comment by zigzag95** [comment]
This will have side effects on AOT and won't work on Universal.
