### ISSUE TITLE
How do I setup global variables that are going to work on all my components?

### ISSUE THREAD

**Issue by CarlosV89** [AngularClass/angular-starter#1590]
Variables defined in the _variables.scss file are not being propagated to my components, am I doing something wrong or is there something Im not doing?

Ive tried importing styles/styles on my app components styles, I've tried 
`import '../styles/styles.scss';` on app.module.ts

**Comment by jmandreslopez** [comment]
I'm using [https://github.com/shakacode/sass-resources-loader](https://github.com/shakacode/sass-resources-loader)

Here's my webpack config:

webpack.common
```
{
    test: /\.scss$/,
    use: [
        'raw-loader',
        'sass-loader',
        {
             loader: 'sass-resources-loader',
             options: {
                 resources: [
                     helpers.root('src/assets/sass/variables.scss'),
                     helpers.root('src/assets/sass/mixins.scss')
                 ]
            },
        },
    ],
    exclude: [helpers.root('src', 'styles')]
},
```

webpack.dev
```
{
    test: /\.scss$/,
    use: [
        'raw-loader',
        'sass-loader',
        {
             loader: 'sass-resources-loader',
             options: {
                 resources: [
                     helpers.root('src/assets/sass/variables.scss'),
                     helpers.root('src/assets/sass/mixins.scss')
                 ]
            },
        },
    ],
    include: [helpers.root('src', 'styles')]
},
```

With that the variables.scss and mixins.scss will be injected into every .scss file and you will have this variables and mixins available.
