### ISSUE TITLE
Load custom js file in angular2-webpack

### ISSUE THREAD

**Issue by kenadet** [AngularClass/angular-starter#1592]
I am trying to load a custom js file so that my app can use it...so how can I load a js file so that it becomes available to my application and also recognize dependent files like jquery and tether?

**Comment by josephserrano15** [comment]
+ 1

**Comment by josephserrano15** [comment]
@kenadet I just did it the old way by adding them to the index.html and copy them manually...

**Comment by gdi2290** [comment]
just add it to the index.html as you normally would and place your static js in the assets folder
