### ISSUE TITLE
Issue with debugging in chrome

### ISSUE THREAD

**Issue by Debanjan123** [AngularClass/angular-starter#1593]
when i try to debug it in chrome browser ..debugging doesn't happen correctly ..

**Comment by gizm0bill** [comment]
I second this: 
![mar-07-2017 23-45-03](https://cloud.githubusercontent.com/assets/189533/23679290/22ce1000-0390-11e7-94e3-2882246b357e.gif)

**Comment by gizm0bill** [comment]
and by the way, how do you guys usually debug, using that VSCode extension?

**Comment by gaurav2887** [comment]
@Debanjan123 - Can you try changing   devtool: 'source-map' to 'eval' in your dev environment and try debugging?

**Comment by gizm0bill** [comment]
don't change it to `eval` your build and rebuild time will skyrocket!
make it `eval-source-map` or simply `source-map` (didn't yet find a difference between the two...)

**Comment by gaurav2887** [comment]
I disagree. I see it much faster with eval in my local dev environment and also if you go over this webpack doc it also confirms build re rebuild speed fastest in eval.

http://webpack.github.io/docs/configuration.html#devtool

**Comment by gizm0bill** [comment]
ah yes the speed thing might be right, but the original code is not shown, going by the docs as well.
<img width="595" alt="screen shot 2017-03-16 at 9 07 02 pm" src="https://cloud.githubusercontent.com/assets/189533/24014299/0f8eabb8-0a8d-11e7-9448-1dacf28cf593.png">

**Comment by Debanjan123** [comment]
@gaurav2887 thank you for your help .Now it is working fine.

**Comment by xaclincoln** [comment]
@Debanjan123 , how did you solve it? Source map is almost broken on my chrome, i'm not able to step through breakpoints.

**Comment by Debanjan123** [comment]
change  'cheap-module-source-map', to eval in  webpack.dev.js

**Comment by Andrey-Pavlov** [comment]
Same problem. It was fixed when I change:  devtool: 'cheap-module-source-map', to devtool: 'source-map',
