### ISSUE TITLE
angular-in-memory-web-api is not working !

### ISSUE THREAD

**Issue by hitoz** [AngularClass/angular-starter#1594]
I tried to add angular-in-memory-web-api package into this project.. and follow the instruction completely.. but i don't know it keeps error 404 not found when access the api..

I have been created a angular 2 project with angular-in-memory-web-api package.. and its work fine.. when i implemented into this project.. it doesn't work..

Please guide me..

Thanks

**Comment by Ryan-7** [comment]
Same problem.
