### ISSUE TITLE
Adding css loader

### ISSUE THREAD

**Issue by TeodorKolev** [AngularClass/angular-starter#1597]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository

Is there a chance to add some css loader instead of that text "Loading..."? If it is which is the proper place to add those css?

**Comment by klihelp** [comment]
You can add the css file or inline css to you index.html

**Comment by gdi2290** [comment]
as mentioned you can do this already with the index.html file
