### ISSUE TITLE
AOT build leaves component templates in the final bundle

### ISSUE THREAD

**Issue by lukaszsamson** [AngularClass/angular-starter#1604]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
AOT build inludes every component template two times making the bundle much bigger than needed as templates are included as strings which cannot be minified by UglifyJS.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

In freshly cloned repo
`npm i`
`npm run build:aot:prod`
`grep -o "WebPack Angular 2 Starter by" dist/main.*.js`
returns 2 lines matching:
one in ngc compiled component code (`this._text_30=this.renderer.createText(this._el_29,"WebPack Angular 2 Starter by ",null),this._el_31=s.createRenderElement(`)
other in bundled template (`\n\n    <footer>\n      <span>WebPack Angular 2 Starter by <a [href]="url">@AngularClass</a></span>\n `)

* **What is the expected behavior?**
Component templates are not included as strings. They are already handled by ngc and built into compiled components

**Comment by gdi2290** [comment]
we need something else to remove the decorators. I'll close this unless you know of a way to remove them or know of a module that will do it
