### ISSUE TITLE
Getting JavaScript to work in Angular 2-webpack

### ISSUE THREAD

**Issue by kenadet** [AngularClass/angular-starter#1612]
How can I get javascript or jquery in my html or app component to work, noticed they are not working. The javascript in this page were not detected.

```
import { Component } from '@angular/core';

@Component({
    selector: 'header',
    styleUrls: [ 'app.scss'],
    templateUrl: 'topnav.component.html',
})

export class NavComponent {

constructor(){}     

    gettheme(color: string): void {
        var link: any = $('<link>');
        link
            .appendTo('head')
            .attr({type : 'text/css', rel : 'stylesheet'})
            .attr('href', 'themes/app-'+color+'.css');
    }

}
```

**Comment by pradeepgill007** [comment]
Hi @kenadet 

This can be done by pure Javascript, Please find below code may help you.

`    
export class NavComponent {

constructor(){}     

ngOnInit(){
let css_link = 'http://abc.com/css/abc.css'
this.getDynamicThemingCSS(css_link);
}
getDynamicThemingCSS(cssLink){
        let linkTag = document.createElement('link');
        linkTag.type = 'text/css';
        linkTag.rel = 'stylesheet';
        linkTag.href = cssLink;
        document.head.appendChild(linkTag);
    }

}
`

**Comment by kenadet** [comment]
This is great
