### ISSUE TITLE
TSLint in common config instead of dev?

### ISSUE THREAD

**Issue by bmayen** [AngularClass/angular-starter#1614]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[X ] feature request
[ X] question about the decisions made in the repository

* **What is the current behavior?**
TSLint is only run for Dev builds

* **What is the expected behavior?**
What is the rationale for only linting dev builds? Seems preferable to add the linting to the common config so it can be run in CI for prod builds as well.

**Comment by gdi2290** [comment]
yeah sounds good
