### ISSUE TITLE
How to dont show warning log messages in browser console，just show that in terminal？

### ISSUE THREAD

**Issue by LeeChingYin** [AngularClass/angular-starter#1616]
There are so many warning log messages in browser console. And  these log messages is the same in the terminal. I just want to show the warning and the error messages in the terminal and show the error messages in the browser console.How can I do that.I looking for a long time, but i dont know how to do that. Can someone help me about that?
![image](https://cloud.githubusercontent.com/assets/6385937/23932619/325bbeac-0974-11e7-8720-34932c824def.png)

**Comment by gmareater** [comment]
the easiest way is to filter console output:
![image](https://cloud.githubusercontent.com/assets/6206777/24862700/ec6f6fe8-1e12-11e7-9744-915bbbe8e057.png)

**Comment by LeeChingYin** [comment]
@gmareater I know this，but there is much info to output and I dont want to show too much. I think that can be setting some config in webpack. Until now I‘m not found.

**Comment by jeatime6** [comment]
- In 'config/webpack.dev.js', just remove 'tslint-loader'.

![_20170504165405](https://cloud.githubusercontent.com/assets/6733968/25696626/724c19ec-30ea-11e7-8835-58657f55df6f.png)

- If you want to disable 'tslint-loader', maybe you can modify 'tslint-loader' souce code. In my project, I add  'canEmit' property (boolean) to emit errors and warning. 

[jeatime6/tslint-loader@b0d0d22](https://github.com/jeatime6/tslint-loader/commit/b0d0d22c0ac6026b134b77e4515473e1dd3b5305) 
[jeatime6/tslint-loader@475c480](https://github.com/jeatime6/tslint-loader/commit/475c480b3e4c220692935a74251ccb6265c388bf)

![image](https://cloud.githubusercontent.com/assets/6733968/25697472/a2e14ea8-30ed-11e7-8037-2d74ae0ad9ef.png)

Hope it works for you.

**Comment by sajeerzeji** [comment]
Got a better solution for this.
On your `main.ts`, add this
```
if (environment.production) {
  enableProdMode();
  if (window) {
    window.console.log = () => {};
  }
}
```
