### ISSUE TITLE
how can i load sass files both for component style and the global style

### ISSUE THREAD

**Issue by ghbakhtiari** [AngularClass/angular-starter#1647]
* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
I cant load sass files both for component style and the global style.
the component's style:
```
@Component({
    selector: 'my-app',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss']
})
```
global style: (imported inside app.component.ts)
`import '../assets/sass/styles.scss';`

i have found this rule for loading component sass styles and it works, but only for component's style:
```
{
        test: /\.scss$/,
        exclude: /node_modules/,
        loaders: ['raw-loader', 'sass-loader'] // sass-loader not scss-loader
}
```
also i've found this rule which can load the global sass file (the import statement), but doesn't load the component style:
```
{
        test: /\.scss$/,
        use: [
            {
                loader: "style-loader" // creates style nodes from JS strings
            }, {
                loader: "css-loader" // translates CSS into CommonJS
            }, {
                loader: "sass-loader" // compiles Sass to CSS
            }
        ]
}
```

also, when i put both of them inside the rules array, i get this error:
```
ERROR in ./src/assets/sass/styles.scss
Module build failed: 
h1 {
^
      Invalid CSS after "...load the styles": expected 1 selector or at-rule, was "var content = requi"
      in C:\xampp\htdocs\FaraneshFront\src\assets\sass\styles.scss (line 1, column 1)
 @ ./src/app/app.component.ts 12:0-37
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/main.ts
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 286 bytes [entry] [rendered]
webpack: Failed to compile.
```

ofcourse i can work around it by specifying the regex parts inside rules like this, and it works:

```
{
    test: /\ .component.scss$/,
    exclude: /node_modules/,
    loaders: ['raw-loader', 'sass-loader'] // sass-loader not scss-loader
},
{
    test: /styles.scss$/,
    use: [
        {
            loader: "style-loader" // creates style nodes from JS strings
        }, {
            loader: "css-loader" // translates CSS into CommonJS
        }, {
            loader: "sass-loader" // compiles Sass to CSS
        }
    ]
}
```

but it's not a good way at all.(considering the fixed file names)

so, what should i do?

* **Please tell us about your environment:**

- Angular version: 2.4.5
- npm version: 3.10.10
- node version: 6.9.5

**Comment by tytskyi** [comment]
@ghbakhtiari styles that you put into `src/styles` are importable as you wanted

**Comment by herohoner** [comment]
Where is this configuration file? global styles config?
