### ISSUE TITLE
Webworkers?

### ISSUE THREAD

**Issue by bmayen** [AngularClass/angular-starter#1655]
Has anybody had any success getting webworkers to work in this repo?

**Comment by bmayen** [comment]
I've added another entry point for my worker bundle. In `main.browser.ts` I load the worker via `bootloader(bootstrapWorkerUi('worker.bundle.js'))`. This works but I get `webpackJsonpac__name_ is not defined` thrown from the worker bundle at runtime. The problem as I understand it is that the webpack manifest sets up some methods on `window` and these are not available to the webworker. 

Would duplicating the webpack manifest in the worker bundle fix this? Any ideas on how to do that?

**Comment by tobek** [comment]
I got it to work using [`worker-loader`](https://github.com/webpack-contrib/worker-loader) and then calling it like so:

    const WorkerLoader = require('worker-loader?name=name-of-output-file.[hash].js!path/to/your/worker.ts');
    const worker = new WorkerLoader();
    worker.onmessage = ...

I didn't have to modify any of the config files, and the build automagically creates built JS file replacing `[hash]` with content-dependent hash in it (e.g. `name-of-output-file.1234567890abcdef.js`).

However, if you want to split out common chunks between the worker and your main scripts (e.g. loading a vendor bundle from within the worker with `importScripts()`) then it's more complicated and will involve updating the configs and I'd love to know what you come up with! I couldn't get it to work.

**Comment by bmayen** [comment]
Thanks @tobek. I'll try out this approach this week and report back.

**Comment by bmayen** [comment]
While this will work if you are using webworkers directly as in you example, it won't work with Angular's webworker strategy. Looking into `angular-worker-loader` for this, but one of the listed TODOs is "Workflow with bundles, especially hashed", so this might be a non-starter for me.

**Comment by bmayen** [comment]
This looks like a good, clean approach. https://stackoverflow.com/questions/43276044/angular-cli-generated-app-with-web-workers

**Comment by oskvortsov-bmt** [comment]
@bmayen you solved this problem?

**Comment by bmayen** [comment]
Basically used the approach described in the stackoverflow link I posted. Our company is currently working on a contribution to Angular-CLI to support webworkers out of the box there, so that's where our focus is now. General principles should work with this starter though as well.

**Comment by paistipoikka** [comment]
@bmayen How your team go with this? Did you manage to successfully submit the contribution to the Angular-Cli project?

**Comment by bmayen** [comment]
This approach is not the one preferred by the Angular-CLI team, so we never submitted the a PR for it. There's an open issue for it but it is only prioritized as a "nice-to-have". I've requested higher priority but it hasn't gotten traction yet. https://github.com/angular/angular-cli/issues/2305

**Comment by KhanaevRoman** [comment]
@bmayen Good day! Did you manage to introduce web workers into this repo??? Can you get me example or solution of it?

**Comment by adrian-mitangi** [comment]
I'd also like to see this happen.

**Comment by bmayen** [comment]
@KhanaevRoman, I followed the example in the link above

**Comment by KhanaevRoman** [comment]
@bmayen shlomiassaf solution? But it is not this repo based project...

**Comment by bmayen** [comment]
> Basically used the approach described in the stackoverflow link I posted. Our company is currently working on a contribution to Angular-CLI to support webworkers out of the box there, so that's where our focus is now. General principles should work with this starter though as well.

**Comment by yzhe554** [comment]
@bmayen Can I ask how did you get rid of 'window is undefined' error message with the solution in the stackoverflow link?

**Comment by bmayen** [comment]
Would need more information. That error could be caused by any number of things. What does the error stack look like?
