### ISSUE TITLE
Unsupported OS

### ISSUE THREAD

**Issue by TeodorKolev** [AngularClass/angular-starter#1660]
Any ideas how to fix that?
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by bmayen** [comment]
Are you actually running on Linux as suggested by the message? If so, fsevents is not needed there. It's an optional dependency required by OSX.
