### ISSUE TITLE
Error 404 Angular Material Branch Not Found

### ISSUE THREAD

**Issue by hiteshsahu** [AngularClass/angular-starter#1688]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
 bug report
In the readme link to Angular Material Branch is broken
https://github.com/AngularClass/angular2-webpack-starter/tree/material2

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Error 404 Angular Material Branch Not Found

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1) Go to Readme guide
2) Go the FAQ
> If you're looking to add Angular 2 Material Design
> check out the material2 branch

3) click on material2
4) Error 404

* **What is the expected behavior?**

Link should redirect to https://github.com/angular/material2

* **What is the motivation/use case for changing the behavior?**
Improve document quality

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
NA

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, gitter, etc)
NA

**Comment by karolmie1** [comment]
It looks like reference to material2 branch is already removed from FAQ.
