### ISSUE TITLE
Check DEBUG mode in TypeScript code (similar to checking isDevServer flag in index.html)

### ISSUE THREAD

**Issue by AKlaus** [AngularClass/angular-starter#1700]
## Question
**How can I check in the TypeScript code that I'm debugging the app and it is NOT running in the production mode?**

The `webpack.common.js` file has `isDevServer` flag, which indicates running local dev server and can be used in HTML files (it's used in the default `index.html`). Is there an option to use this flag in the TypeScript code (Angular classes)? Or maybe there is something similar.

## Longer rant
A very simple app has no backend and is using Azure AppInsight for logging. I don't want to pollute the log with messages generated during debugging the app locally (those records could be filtered out, but I'm better off preventing them).
Of course, there are alternative options:

- One would be a URL check (if it's http://localhost, then not to log), but in some cases it could be http://0.0.0.0. 
 - Then I thought to check the port number, but it will become vulnerable to future port changes (happened once in the past), as such dependency on the port would be not obvious.

Maybe there are other options, but I see handling the "_debug_" mode as the most intuitive for future developers.

Last addition, the logging is done in a service, which gets injected. Hence, maybe a good practice would be to wire up a different service in the debug mode, but again, what's the best way to do that.

**Comment by admosity** [comment]
You can add this entry in your DefinePlugin in prod/dev environments:

`'IS_DEV': helpers.isWebpackDevServer(),`

and then you can reference `IS_DEV` in your code.
