### ISSUE TITLE
How to use the appState service?

### ISSUE THREAD

**Issue by KhaledElAnsari** [AngularClass/angular-starter#1708]
Hello, I just want to ask about the right way for using appState? and what benefits we get from it?

**Comment by admosity** [comment]
https://angular-2-training-book.rangle.io/handout/state-management/ngrx/component_architecture.html

It's for decoupling state from your components and makes your app more manageable. Also with hot module reload, the state of your app can be persisted while your components are reloaded. The link above goes into a bit more detail with a more fully fledged global app state management library called ngrx, which you can use to swap out the current app state that's in the starter.

**Comment by gdi2290** [comment]
it's only meant as an example
