### ISSUE TITLE
Issues in installing Bootstrap 4 to project

### ISSUE THREAD

**Issue by aishabadar** [AngularClass/angular-starter#1710]
I have been following wiki [https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-use-Bootstrap-4-and-Sass-(and-jQuery) to install bootstrap 4 to project but getting this error:

     ERROR in ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js
     Module build failed: Error: Could not resolve module 'bootstrap-sass' which must be installed when 
     bootstrap version is   configured to v3.
     You must install 'bootstrap' for bootstrap v4 or 'bootstrap-sass' for bootstrap v3.
     You can also specify the location manually by specifying 'bootstrapPath' in bootstrap-loader's query 
     string.
     See https://github.com/shakacode/bootstrap-loader/blob/master/README.md#usage.
     at Object.module.exports.pitch (C:\Users\SYED KAMRAN HUSSAIN\Documents\GitHub\angular2-crud-app\node_modules\bootstrap-loader\lib\bootstrap.loader.js:147:11)
      @ ./~/bootstrap-loader/loader.js 2:17-61
      @ multi (webpack)-dev-server/client?http://localhost:3000 bootstrap-loader

       ERROR in ./src/styles/styles.scss
       Module build failed:
        /* this file will be extracted to main dist folder and is imported in index.html */
        ^
       Invalid CSS after "...load the styles": expected 1 selector or at-rule, was "var content = requi"
       in C:\Users\SYED KAMRAN HUSSAIN\Documents\GitHub\angular2-crud-app\src\styles\styles.scss (line 1, column 1)
       @ ./src/app/app.module.ts 21:0-31
       @ ./src/app/index.ts
       @ ./src/main.browser.ts
       @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts

        ERROR in ./~/css-loader!./~/raw-loader!./src/app/app.component.css
         Module build failed: Unknown word (1:1)

          > 1 | module.exports = "html, body{\r\n  height: 100%;\r\n  font-family: Arial, Helvetica, sans-serif\r\n}\r\n\r\na.active {\r\n  background-color: gray;\r\n}\r\n"
           | ^

           @ ./src/app/app.component.css 2:21-131
           @ ./src/app/app.component.ts
           @ ./src/app/app.module.ts
           @ ./src/app/index.ts
           @ ./src/main.browser.ts
           @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts

           ERROR in ./~/css-loader!./~/raw-loader!./src/app/home/home.component.css
           Module build failed: Unknown word (1:1)

          > 1 | module.exports = "/*styles for home content only*/"
          | ^

          @ ./src/app/home/home.component.css 2:21-138
          @ ./src/app/home/home.component.ts
          @ ./src/app/home/index.ts
          @ ./src/app/app.module.ts
          @ ./src/app/index.ts
          @ ./src/main.browser.ts
          @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts

Please help me what is wrong here? I am newbie to angular2 and trying to create a simple dashboard and a CRUD application. Your help and suggestions will be highly appreciated.

Thank you.

**Comment by SherlockStd** [comment]
@aishabadar If you're still having issues with Bootstrap 4 installation please let me know I can help you

**Comment by aishabadar** [comment]
Yes, I am still having issues. I tried all possible things but its giving error on css loader. I committed css loader and tried without it but the scss or css file I imported in app.module.ts is not showing the stylings on specific page. If you need more information, please let me know. Thank you.

**Comment by SherlockStd** [comment]
@aishabadar what do you mean by 

> not showing the stylings on specific page

**Comment by SherlockStd** [comment]
The resource https://github.com/AngularClass/angular-starter/wiki/How-to-use-Bootstrap-4-and-Sass-(and-jQuery) was not working for me neither, so I tried my way and it worked, but instead of jQuery I used `ng-bootstrap` for a better integration with Angular 2/4

**Comment by aishabadar** [comment]
Ok I got it. I am also thinking to go for it. I tried bootstrap integration with angular/cli and its working great. I should go with ng-bootstrap. I will give it a try and get back to you if I face any issues. Thank you for the response.

**Comment by SherlockStd** [comment]
Here is the only SCSS related line in my webpack.common.js:
```javascript
/*
 * to string and sass loader support for *.scss files (from Angular components)
 * Returns compiled css content as string
 *
 */
{
  test: /\.scss$/,
  use: ['to-string-loader', 'css-loader', 'sass-loader'],
  exclude: [helpers.root('src', 'styles')]
},
```
and then I placed my Bootstrap 4 scss lib in a `src/bootstrap` folder, and I include it on `app.module.ts` like this: 
```javascript
import '../styles/bootstrap/bootstrap.scss' // Bootstrap entry point
import '../styles/styles.scss' // Custom styles
```

**Comment by SherlockStd** [comment]
`ng-bootstrap` don't handle the style part, only the jQuery based operations

**Comment by SherlockStd** [comment]
You can take a look on my repo (https://github.com/SherlockStd/ME4N-Starter/tree/master/src) for more details (the `src` folder is based on this repo), and for `ng-bootstrap` see my [bootstrap demo component](https://github.com/SherlockStd/ME4N-Starter/tree/master/src/app/bootstrap)

**Comment by SherlockStd** [comment]
Let me know if you have any more problem

**Comment by aishabadar** [comment]
Thanks for such detailed response. It will definitely help. I am going to try it soon and get back to you. Thanks again.
