### ISSUE TITLE
Module parse failed: ..\node_modules\@ionic\app-scripts\dist\webpack\loader.js! You may need an appropriate loader to handle this file type 

### ISSUE THREAD

**Issue by krile2822** [AngularClass/angular-starter#1713]
Hi!

I created ionic project with ionic start --v2 --ts. I use Canvas.js for displaying a chart. 
When i put some sample data, example:
```
data: [{
             	type: "line",
             	dataPoints: [
 				{ label: "apple",  y: 15  }
 			]
             }]
```

it works perfectly. But when i want to use Date in property, like this: 

```
 data: [{
             	type: "line",
             	dataPoints: [
 				{ label: "apple",  y: new Date(1992,08,22)  }
 			]
             }]

```
i got an error : 

> Runtime Error
> Module parse failed: d:\...\node_modules\@ionic\app-scripts\dist\webpack\loader.js!d:\...\src\pages\canvas-chart\canvas-chart.ts Invalid number (42:60) You may need an appropriate loader to handle this file type. | type: "line", | dataPoints: [ | { label: "apple", y: new Date(1992, 08, 22) } | ] | }]

**Comment by Sanafan** [comment]
Why was this closed? I have the same error, what was the solution?
