### ISSUE TITLE
Make a source folder location and output folder configurable.

### ISSUE THREAD

**Issue by skorunka** [AngularClass/angular-starter#1720]
* **I'm submitting a ...**
[ ] bug report
[x ] feature request
[ ] question about the decisions made in the repository

Do not hardcode the Angular source files to "src" folder, rather make it configurable. Same goes for bundle output folder. I would like to use this template with asp.net core as a host and having both folders configurable would make my life easier ;)

**Comment by gdi2290** [comment]
that makes sense
