### ISSUE TITLE
AOT + Lazy loading modules from npm not working

### ISSUE THREAD

**Issue by maciejtreder** [AngularClass/angular-starter#1721]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[x] question about the decisions made in the repository

I would like to have my project in multiple repositories (I want to create microservices architecture wich would look like:

- module1-service //back-end service
- module1-UI //front-end written in angular and loaded as an lazy module
- module2-service
- module2-UI
- UI-entry //entry-point, written in angular and lazy-loading another modules

When I am running my project with ```npm start``` everything works. Same with compilation with ```npm run build:prod```. Problem starts when I want to compile to final version, for publishing in the web ```npm run build:aot```.

* **What is the current behavior?**
```
ERROR in ./compiled/src/app/app.module.ngfactory.ts
Module build failed: Error: Cannot find module '/path_to_my_project/compiled/node_modules/my-project-home/src/app/home.module.ngsummary.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Loader.trackSymbolRootDecl '/path_to_my_project/node_modules/src/Loader.ts:157:23)
    at Loader.trackSymbolRootDecl ('/path_to_my_project/node_modules/src/Loader.ts:168:19)
    at '/path_to_my_project/node_modules/src/Loader.ts:120:29
 @ ./src/main-routing.module.ts 8:61-174
 @ ./src/main.module.ts
 @ ./src/main.browser.aot.ts
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via

I got following routing:

This is how I am importing external modules to my application (package.json):

```
"account-settings": "git+ssh://git@gitlab.com/my-project/home-module.git",
```

```
const routes: Routes = [
  { path: '', component: AppComponent, children: [
    { path: '',  redirectTo: 'home', pathMatch: 'full' },
    {path: 'home', loadChildren: '../../node_modules/my-package-home/src/app/home.module#HomeModule' },
    {path: 'account-settings', loadChildren: '../../node_modules/my-package-account-settings/src/app/account-settings.module#AccountSettingsModule' }
  ]}
];
```

* **Please tell us about your environment:**

- Angular version: 4.0.3

I am publishing to GIT non-compiled sources. Maybe that's the point? Should I compile them with AOT and attach the 'compiled' catalog to the repo?

**Comment by thinkingmedia** [comment]
You shouldn't have to include `node_modules` in the path for the routes. Node modules should be auto discovered.

```
const routes: Routes = [
  { path: '', component: AppComponent, children: [
    { path: '',  redirectTo: 'home', pathMatch: 'full' },
    {path: 'home', loadChildren: 'my-package-home/src/app/home.module#HomeModule' },
    {path: 'account-settings', loadChildren: 'my-package-account-settings/src/app/account-settings.module#AccountSettingsModule' }
  ]}
];
```

I've never tried what you're doing. Since you're lazy modules from an outside project there might be more things required to get it to work.

**Comment by HipsterZipster** [comment]
This is a great question, can you please share how you got this working? Specifically lazy loading modules from an outside project in your npm modules

**Comment by lohiarahul** [comment]
Following

**Comment by shlomiassaf** [comment]
This is not how it should be done, the setup will cause a lot of headaches.
It assumes the same webpack configuration for all projects, importing types is a nightmare and optimization from webpack will be a problem... really don't do it that way.

A package should be properly bundled and compiled and then consumed from a repository (npm) or github (release based)  using a proper build, [this is how its done](https://github.com/shlomiassaf/angular-library-starter)

If you don't want to publish libraries the next best option is using git submodules or other form of external repo within a repo.

Now, in you case why it doesnt work:
While creating an AOT build the angular compiler (compiler-cli) saves all of it's output (ngfactory.ts, ngsummary.ts etc...) in a designated directory.

The files that the compiler create contains references to the original source code...
For example, if I have a component called `MyComp` in a module file named `my-comp.ts` then the compiler create a file `my-comp.ngfactory.ts` and inside that file there will be an import from the `my-comp.ts` module. (relative path)

To create this imports the compiler resolves the filename it creates and the path to it against the original files and creates a relative path.

This is all done with the current directory as base and typescript configuration such as `paths`, `baseUrl` etc affecting the path resolution.

So probably something there is not suitable for resolving paths the are outside of the root path defined.

It might also be something in other packages such as ng-router-loader or the ngc-webpack plugin, who knows... it might be in those or in the angular compiler itself.

All of them were not built to support that setup

**Comment by lohiarahul** [comment]
> This is a great question, can you please share how you got this working? Specifically lazy loading modules from an outside project in your npm modules

Anything on this? Trying to make it work too.

**Comment by lohiarahul** [comment]
@maciejtreder could you find a way to get around it?

**Comment by lohiarahul** [comment]
> This is not how it should be done, the setup will cause a lot of headaches.
> It assumes the same webpack configuration for all projects, importing types is a nightmare and optimization from webpack will be a problem... really don't do it that way.
> 
> A package should be properly bundled and compiled and then consumed from a repository (npm) or github (release based) using a proper build, this is how its done
> 
> If you don't want to publish libraries the next best option is using git submodules or other form of external repo within a repo.
> 
> Now, in you case why it doesnt work:
> While creating an AOT build the angular compiler (compiler-cli) saves all of it's output (ngfactory.ts, ngsummary.ts etc...) in a designated directory.
> 
> The files that the compiler create contains references to the original source code...
> For example, if I have a component called MyComp in a module file named my-comp.ts then the compiler create a file my-comp.ngfactory.ts and inside that file there will be an import from the my-comp.ts module. (relative path)
> 
> To create this imports the compiler resolves the filename it creates and the path to it against the original files and creates a relative path.
> 
> This is all done with the current directory as base and typescript configuration such as paths, baseUrl etc affecting the path resolution.
> 
> So probably something there is not suitable for resolving paths the are outside of the root path defined.
> 
> It might also be something in other packages such as ng-router-loader or the ngc-webpack plugin, who knows... it might be in those or in the angular compiler itself.
> 
> All of them were not built to support that setup

All the modules that were supposed to be different npm packages are a part of the same code base. Also there is a lot of gulp tasks involved. How is this better?

**Comment by shlomiassaf** [comment]
This is how packages are built.

Look at the way the angular team builds their packages... angular core,common, http etc...

All in the same repo.

**Comment by shlomiassaf** [comment]
This is an advanced scenario that requires knowledge in webpack and TypeScript.

More specifically how to configure webpack aliases properly and how to configure TypeScript paths properly

**Comment by rkolec** [comment]
Possible workaround is to create a small lazy loaded 'wrapper' module that imports module from node_modules.
