### ISSUE TITLE
how to running with AOT?

### ISSUE THREAD

**Issue by gieboyz** [AngularClass/angular-starter#1722]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

i try to using AOT when first time download this angular-starter, but there only have build:aot, not for running server:aot like server:dev or server:prod,

and i try to modify like this
    "server:dev:aot": "webpack-dev-server --config config/webpack.dev.js --open --progress --profile --watch --content-base src/",

but only looping forever like image bellow
![tes](https://cloud.githubusercontent.com/assets/9793593/25790432/9eecf278-33e2-11e7-94c5-da617ac1dad6.png)

can you give me solution for this?? 
* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: ~4.0.3
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by SherlockStd** [comment]
it's not a feature, it's a bug

**Comment by colinskow** [comment]
AoT will not work with the dev server. AoT is for making your production build. If you want to use the dev server, just type `npm start`.

**Comment by kamil-kielczewski** [comment]
As far i knwo to run AoT you must execute below commands:

```
npm run build:aot
npm run server:prod
```

**Comment by akashbiz** [comment]
@kamil-kielczewski  @colinskow Can I enable AoT for dev build too?

**Comment by colinskow** [comment]
@akashbiz no, AoT does not allow HMR or incremental rebuilds, compiles slow, and is much harder to debug.

**Comment by kamil-kielczewski** [comment]
@akashbiz I don't know this is possible or not, however Im interested why you need AoT for dev build?

**Comment by akashbiz** [comment]
@colinskow & @kamil-kielczewski , Thanks for your response. @kamil-kielczewski  I want to use AoT for both dev and prod build but for local live server run I want to use the JIT only.
I need AoT for dev because the application I am developing is quite big so it generate large size of main.bundle.js aound 4.6MB which is too large. So I have to start using AoT here onward for dev environment.

Thanks.

**Comment by akashbiz** [comment]
Also can you guide me where can I store the environmental stuff? like, If I am using S3 bucket so where can I define the different bucket names for different environments?

**Comment by kamil-kielczewski** [comment]
@akashbiz 
Support for env will be in future (I hope) https://github.com/AngularClass/angular-starter/pull/1736

Why 4.6MB is too large?
