### ISSUE TITLE
I just downloaded this starter project. Upon "npm install", I am getting the following error.

### ISSUE THREAD

**Issue by anuramesh1** [AngularClass/angular-starter#1725]
![image](https://cloud.githubusercontent.com/assets/28538061/25811520/902ef552-33e1-11e7-9b2b-27d88d598eaf.png)

Any help would be appreciated. Thanks !

**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by zxqian1991** [comment]
i have the same problem to
```javascript
[10:08:34] I/update - geckodriver: setting permissions to 0755 for /Users/qianzhixiang/test/angular2/study-4/node_modules/webdriver-manager/selenium/geckodriver-v0.16.1
[10:08:34] I/update - geckodriver: geckodriver-v0.16.1 up to date
/Users/qianzhixiang/test/angular2/study-4/node_modules/webdriver-manager/built/lib/files/downloader.js:53
                                    error.msg = 'Error: corrupt download for ' + fileName +
                                              ^

TypeError: Cannot set property 'msg' of null
    at fs.stat (/Users/qianzhixiang/test/angular2/study-4/node_modules/webdriver-manager/built/lib/files/downloader.js:53:47)
    at FSReqWrap.oncomplete (fs.js:123:15)

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "webdriver:update"
npm ERR! node v6.10.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
```

**Comment by thinkingmedia** [comment]
What is `192.30.253.117`?

That is a local area network IP address (maybe your workstation). Maybe sure your firewall allows port 443. The build script for Selenium has failed. 

Also, you are running the development build of NodeJS (7.x). Uninstall and download the LTS version 6.x and give that a try.

**Comment by thinkingmedia** [comment]
@zxqian1991 delete your npm cache and try again.

     npm cache clean

https://docs.npmjs.com/cli/cache

**Comment by zxqian1991** [comment]
thanks,it works.

**Comment by anuramesh1** [comment]
Thanks !!. I tried in my work laptop, which has NodeJS 7.0.4. I guess I will have to try that in my personal laptop with 6.x NodeJS version. 

Thank you again.

**Comment by gdi2290** [comment]
npm cache clean

**Comment by JLNNN** [comment]
I'm getting the same error, npm cache clean doesn't resolve it.

**Comment by thinkingmedia** [comment]
@JLNNN this is a build error for one of the testing libraries. What OS platform are you on?

**Comment by JLNNN** [comment]
macOS Sierra, but I just "found" a walkaround: Deleted the node_modules folder and npm install'ed again.

Thx for your help :)
