### ISSUE TITLE
METADATA is not a WebPack configuration.

### ISSUE THREAD

**Issue by thinkingmedia** [AngularClass/angular-starter#1727]
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

`webpack.dev.js` and `webpack.prod.js` both use METADATA with the `DefinePlugin`. Which is fine but each file attempts to merge METADATA from the `webpack.common.js` file.

```
var METADATA = webpackMerge(commonConfig({env: ENV}).metadata, {
  host: HOST,
  port: PORT,
  ENV: ENV,
  HMR: HMR
});
```

This does not appear to be correct. First, the `webpack.common.js` does not export a configuration with a `metadata` property, and second `metadata` is not a valid Webpack configuration option.

Using the `webpackMerge` function here appears to be a mistake. This METADATA object is just a dictionary and not a WebPack configuration. The function appears to just yield the merge target if passed `undefined` for the first argument. If you attempt to add `metadata` to `commonConfig` then it will fail with an error about the configuration being invalid.

**Comment by gdi2290** [comment]
can you create a PR?

**Comment by thinkingmedia** [comment]
@gdi2290 Yes, I'll open a PR later today.

**Comment by gdi2290** [comment]
thanks

**Comment by didlich** [comment]
Is there a PR?
I didn't found it.

**Comment by thinkingmedia** [comment]
@didlich no, sorry. I forgot.

**Comment by gdi2290** [comment]
I removed it here https://github.com/AngularClass/angular-starter/commit/54f2d1317af5638f2c45cdf74777126795288347
