### ISSUE TITLE
is html-loader still needed?

### ISSUE THREAD

**Issue by DBosley** [AngularClass/angular-starter#1733]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ X ] question about the decisions made in the repository

Is html-loader still necessary? I removed the LoaderOptionsPlugin configuration for it in my own project to see if anything changed and I'm not noticing any problems. I don't even see it used in any of the loader configurations. If it's not necessary, there's a good chance the LoaderOptionsPlugin isn't necessary anymore.

**Comment by colinskow** [comment]
Right now we are using `raw-loader` and `html-loader` appears to be a dead dependency.

The advantage of `html-loader`is that it can minify code to make the build smaller.

We have a couple choices to resolve this:
1) Remove `html-loader` from package.json
2) Replace `raw-loader` with `html-loader` to save a few bytes each build
