### ISSUE TITLE
Replace `app.service` with @ngrx/store?

### ISSUE THREAD

**Issue by colinskow** [AngularClass/angular-starter#1737]
I propose replacing the existing `app.service.ts` with a very basic implementation of @ngrx/store.

Reasons:
1) @ngrx/store is the golden standard of state management for Angular
2) It is complicated to get it plugged in correctly to HMR in this module, but I have it working perfectly
3) It doesn't add any additional complexity to the repo and shows best practices

If there's interest from the maintainers I can do a PR. It is working well in my fork.
https://github.com/colinskow/angular-electron-dream-starter

**Comment by gdi2290** [comment]
seems like everyone is doing it. I might do so in a refactor
