### ISSUE TITLE
getting error for the resolve

### ISSUE THREAD

**Issue by savaj** [AngularClass/angular-starter#1738]
service like this and not working the resolve
import { Injectable } from '@angular/core';
import { Hero } from './hero';
import { HEROES } from './mock-heroes';

@Injectable()
export class HeroService {
  getHeroesSlowly(): Promise<Hero[]> {
	  return new Promise(resolve => {
	    // Simulate server latency with 2 second delay
	    setTimeout(() => resolve(this.getHeroes()), 2000);
	  });
    }
}

**Comment by SherlockStd** [comment]
your method `this.getHeroes()` isn't declared

**Comment by SherlockStd** [comment]
This should work:
```javascript
import { Injectable } from '';
import { Hero } from './hero';
import { HEROES } from './mock-heroes';

@Injectable()
export class HeroService {
  
  getHeroesSlowly(): Promise<Hero[]> {
    return new Promise(resolve => {
      // Simulate server latency with 2 second delay
      setTimeout(() => resolve(this.getHeroes()), 2000);
    });
  }

  getHeroes(): Promise<Hero[]> {
    return new Promise(resolve => {
      resolve(HEROES)
    })
  }
}
```

**Comment by SherlockStd** [comment]
btw please respect the issue template.
