### ISSUE TITLE
Not able to an AOT build. Getting the error on

### ISSUE THREAD

**Issue by ChinmoyDn** [AngularClass/angular-starter#1740]
> Project@5.4.1 build:aot /Users/chinmoyz/myProjects/Project/webApp/webservices
> npm run build:aot:prod

> Project@5.4.1 build:aot:prod /Users/chinmoyz/myProjects/Project/webApp/webservices
> npm run clean:dist && npm run clean:aot && npm run ngc -- --webpack config/webpack.prod.js && webpack --config config/webpack.prod.js  --progress --profile --bail

> Project@5.4.1 clean:dist /Users/chinmoyz/myProjects/Project/webApp/webservices
> npm run rimraf -- dist

> Project@5.4.1 rimraf /Users/chinmoyz/myProjects/Project/webApp/webservices
> rimraf "dist"

> Project@5.4.1 clean:aot /Users/chinmoyz/myProjects/Project/webApp/webservices
> npm run rimraf -- compiled

> Project@5.4.1 rimraf /Users/chinmoyz/myProjects/Project/webApp/webservices
> rimraf "compiled"

> Project@5.4.1 ngc /Users/chinmoyz/myProjects/Project/webApp/webservices
> ngc-w -p tsconfig.webpack.json "--webpack" "config/webpack.prod.js"

TypeError: Cannot read property 'options' of undefined
    at new WebpackChainModuleResolutionHostAdapter (/Users/chinmoyz/myProjects/Project/webApp/webservices/node_modules/src/webpack-chain-module-resolution-host-adapter.ts:12:119)
    at /Users/chinmoyz/myProjects/Project/webApp/webservices/node_modules/src/main.ts:19:46
    at Object.main (/Users/chinmoyz/myProjects/Project/webApp/tools/@angular/tsc-wrapped/src/main.ts:60:12)
    at runInternal (/Users/chinmoyz/myProjects/Project/webApp/webservices/node_modules/src/main.ts:25:10)
    at main (/Users/chinmoyz/myProjects/Project/webApp/webservices/node_modules/src/main.ts:45:10)
    at Object.<anonymous> (/Users/chinmoyz/myProjects/Project/webApp/webservices/node_modules/src/main.ts:66:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
Compilation failed

npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/chinmoyz/.nvm/versions/node/v6.10.1/bin/node" "/Users/chinmoyz/.nvm/versions/node/v6.10.1/bin/npm" "run" "ngc" "--" "--webpack" "config/webpack.prod.js"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! Project@5.4.1 ngc: `ngc-w -p tsconfig.webpack.json "--webpack" "config/webpack.prod.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Project@5.4.1 ngc script 'ngc-w -p tsconfig.webpack.json "--webpack" "config/webpack.prod.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ngc-w -p tsconfig.webpack.json "--webpack" "config/webpack.prod.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Project
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Project
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chinmoyz/myProjects/Project/webApp/webservices/npm-debug.log

npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/chinmoyz/.nvm/versions/node/v6.10.1/bin/node" "/Users/chinmoyz/.nvm/versions/node/v6.10.1/bin/npm" "run" "build:aot:prod"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! Project@5.4.1 build:aot:prod: `npm run clean:dist && npm run clean:aot && npm run ngc -- --webpack config/webpack.prod.js && webpack --config config/webpack.prod.js  --progress --profile --bail`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Project@5.4.1 build:aot:prod script 'npm run clean:dist && npm run clean:aot && npm run ngc -- --webpack config/webpack.prod.js && webpack --config config/webpack.prod.js  --progress --profile --bail'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean:dist && npm run clean:aot && npm run ngc -- --webpack config/webpack.prod.js && webpack --config config/webpack.prod.js  --progress --profile --bail
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Project
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Project
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chinmoyz/myProjects/Project/webApp/webservices/npm-debug.log

npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/chinmoyz/.nvm/versions/node/v6.10.1/bin/node" "/Users/chinmoyz/.nvm/versions/node/v6.10.1/bin/npm" "run" "build:aot"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! Project@5.4.1 build:aot: `npm run build:aot:prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Project@5.4.1 build:aot script 'npm run build:aot:prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:aot:prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Project
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Project
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chinmoyz/myProjects/Project/webApp/webservices/npm-debug.log

**Comment by SherlockStd** [comment]
Duplicated of #1741, @ChinmoyDn please close one of the two issues.
