### ISSUE TITLE
Serving address on LAN with I.S.S

### ISSUE THREAD

**Issue by BusbyActual** [AngularClass/angular-starter#1748]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
No support for LAN access. Angular cli can build a folder that can be hosted with tools like Internet Information Services.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Run angular-starter on windows.
Open IIS and add project folder as a website and it doesn't run.
ng build will solver this

* **What is the expected behavior?**
Website works across LAN without deployment.

* **What is the motivation / use case for changing the behavior?**
Easy access to LAN serving

* **Please tell us about your environment:**
 Version: Angular version 4.1.2,
 Browser: Chrome  58.0.3029.110 (64-bit),
Windows Server 2012 R2 64bit

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
Alternatives are running angular cli and doing a build to server the files. Angular CLI isn't supported in this repo from what I gather.

**Comment by gdi2290** [comment]
when I redo the repo I'll make sure to add this like the cli
