### ISSUE TITLE
Font-awesome failed to decode

### ISSUE THREAD

**Issue by dcods22** [AngularClass/angular-starter#1750]
When I include font-awesome I am able to get it referenced but I get an error 
'Failed to decode downloaded font: http://localhost:3000/df8e7d5dd3892400cdfaf86d729ed97d.woff2'

What is the fix for this.

In my web pack.common I have the following loaders:

/*
           * Font loaders, required for font-awesome-sass-loader and bootstrap-loader
           */
          {
              test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
              loader: "url-loader?limit=10000&mimetype=application/font-woff"
          },
          {
              test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
              loader: "file-loader"
          },
          { test: /\.(png|gif|woff|woff2|eot|ttf|svg)(\?|$)/, loader: 'url-loader?limit=100000' },

**Comment by pitama** [comment]
I had that problem, but the i solve. The woff loader was duplicated. Try it.
