### ISSUE TITLE
How can make the checkbox automatically change by value

### ISSUE THREAD

**Issue by hieunguyen336** [AngularClass/angular-starter#1751]
Hi guys, I just started learn angular 2. I would like to make a checkbox automatically checked or unchecked by following values 0 & 1 ? How I can do it ? Thanks

**Comment by SherlockStd** [comment]
@hieunguyen336 This have no reason to be here, one google request like "angular 2 checkboxes binding values" send you here: http://stackoverflow.com/questions/40214655/angular-2-checkbox-two-way-data-binding
