### ISSUE TITLE
Can we add https://prepack.io/ for webpack.prod.js

### ISSUE THREAD

**Issue by itranga** [AngularClass/angular-starter#1761]
Can we add https://prepack.io/ for webpack.prod.js ?

prepack's webpack plugin 

https://github.com/gajus/prepack-webpack-plugin

**Comment by SherlockStd** [comment]
> Prepack is still in an early development stage and not ready for production use just yet.

**Comment by gdi2290** [comment]
prepack isn't ready for production. When it is I will

**Comment by itranga** [comment]
Thanks
