### ISSUE TITLE
Question: How to let istanbul coverage ignore folders?

### ISSUE THREAD

**Issue by andorfermichael** [AngularClass/angular-starter#1763]
Since the slack link is not working I am asking my question here.

I am trying to force istanbul coverage reporter to ignore some folders.

For example, I would like to ignore _./src/app/tests_ folder.

What I tried so far is to add the path in config/webpack.test.js:

```
//**
 * Instruments JS files with Istanbul for subsequent code coverage reporting.
 * Instrument only testing sources.
 *
 * See: https://github.com/deepsweet/istanbul-instrumenter-loader
 */
{
  enforce: 'post',
  test: /\.(js|ts)$/,
  loader: 'istanbul-instrumenter-loader',
  include: helpers.root('src'),
  exclude: [
    '/tests/',
    /\.(e2e|spec)\.ts$/,
    /node_modules/
  ]
}
```
I thought it would be as simple as adding _'/tests/'_ to exclude section, however it was not.
I also tried _'/tests/**/*'_, _'/src/app/tests/'_ and some other variations.

Any suggestions?

**Comment by SherlockStd** [comment]
Hi,

I use `nyc` for the istanbul coverage, it let you do this into your [package.json](https://github.com/SherlockStd/ME4N-Starter/blob/master/package.json#L142-L148):
```
"nyc": {
    "exclude": [
      "folder1/file.js",
      "folder1/subfolder",
      "folder2"
    ]
  }
```

**Comment by SherlockStd** [comment]
Have you tried without any `/` ?

**Comment by andorfermichael** [comment]
Hi,

yes I tried without any `/` but it did not work.

I have had a look at nyc but I do not exactly understand what the benefit should be over using the already integrated _istanbul-instrumenter-loader_ ;)

**Comment by SherlockStd** [comment]
You run your tests from `npm` or `yarn`, I don't see why you use a loader for `istanbul`, `nyc` and `istanbul` works fine in cli ...
What I see is that without the webpack loader and launching from the cli, the result is the same, but it works in that case :smile:

**Comment by andorfermichael** [comment]
@SherlockStd I have had a second look at `nyc` yet. I understand now what the benefits are. [nyc](https://github.com/istanbuljs/nyc) provides a wide range of easily applicable settings. I will use `nyc` from now on and recommend others to do so if problems with istanbul configurations occur.

Thanks @SherlockStd. :)

**Comment by SherlockStd** [comment]
@andorfermichael always a please :smile:
