### ISSUE TITLE
Want to create single js file in build instead of three polifills, main and vendor js files

### ISSUE THREAD

**Issue by bankimatglobant** [AngularClass/angular-starter#1764]
Hi,

Is it possible to generate only single js file in generated build. Is it possible? What changes required to achieve this.

**Comment by karolmie1** [comment]
Just from top of my head: import polyfils in your main.browser.ts file, remove polyfills entry point from webpack.common.config, and remove CommonChunksPlugin instances, where it references vendors of pollyfils.
Be wary though, this distinction exists for a reason. Notably for developement speed, and user side-caching. Why do you want only a single file?
