### ISSUE TITLE
Feature request: remove ControlFlow from e2e tests

### ISSUE THREAD

**Issue by karolmie1** [AngularClass/angular-starter#1766]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

ControlFlow will be disabled in the future: https://github.com/SeleniumHQ/selenium/issues/2969

Also it's cumbersome to use it with helper functions, and it breaks with newest typings.

Instead native async/await functions should be used. 

Example tests with async/await:

```
  it('should wait to grab the WebElement until a method is called', async function() {
    // These should throw no error before a page is loaded.
    const usernameInput = element(by.model('username'));
    const name = element(by.binding('username'));

    await browser.get('index.html#/form');

    await expect(name.getText()).toEqual('Anon');

    await usernameInput.clear();
    await usernameInput.sendKeys('Jane');
    await expect(name.getText()).toEqual('Jane');
});
```

If you think it is a good idea, I can prepare pull request"

**Comment by gdi2290** [comment]
can you make a PR?

**Comment by karolmie1** [comment]
Done, please check it out.
