### ISSUE TITLE
PreloadWebpackPlugin Configuration Causing Build issues

### ISSUE THREAD

**Issue by rmeans** [AngularClass/angular-starter#1767]
The recent addition of PreloadWebpackPlugin in commit https://github.com/AngularClass/angular-starter/commit/cd27c8d594067b2d9f66524e905920c86bf1e9ea is causing issues building the project. I am not getting the following error.

`[at-loader] Checking finished with 1 errors
[at-loader] ./src/main.browser.aot.ts:23:14
    TS1252: Function declarations are not allowed inside blocks in strict mode when targeting 'ES3' or 'ES5'. Modules are automatically in strict mode.`

**Comment by mahcr** [comment]
Same here. `npm run server` isn't working neither

**Comment by chetski** [comment]
I'm getting the following error when I execute "npm run server".

`ERROR in   TypeError: regex.test is not a function

  - index.js:77 options.fileBlacklist.every.regex
    [angular-starter-master]/[preload-webpack-plugin]/index.js:77:66

  - Array.every

  - index.js:77 extractedChunks.filter.entry
    [angular-starter-master]/[preload-webpack-plugin]/index.js:77:45`


I'm on Windows 10 and presume this is the same problem?

**Comment by gdi2290** [comment]
I commented it out for now
https://github.com/AngularClass/angular-starter/blob/master/config/webpack.common.js

**Comment by wicaksana** [comment]
I am not sure if it is related or not, but when I run `npm run server`, it only shows 'Loading..' without displaying any error messages.
