### ISSUE TITLE
Stop committing on master

### ISSUE THREAD

**Issue by SherlockStd** [AngularClass/angular-starter#1770]
@gdi2290 hi, is this possible to protect your master branch ?

I ask this because I'm watching this repo to keep [mine](https://github.com/SherlockStd/ME4N-Starter) up to date, and this is a really complicated job if you don't use a good Git workflow (branch and PR for each feat, fix or whatever), because we (540 watchers) needs to look manually everyday at commit on master branch, which is an annoying, complicated and time-eating task.

Thanks in advance

**Comment by SherlockStd** [comment]
Moreover, you're breaking the stability of the master branch:
- https://travis-ci.org/AngularClass/angular-starter/builds/237627712
- https://travis-ci.org/AngularClass/angular-starter/builds/237628958

**Comment by gdi2290** [comment]
alright, switching workflow
<img width="780" alt="screen shot 2017-05-31 at 2 32 14 pm" src="https://cloud.githubusercontent.com/assets/1016365/26647650/f8f1d2a6-460d-11e7-9bd8-319895a4f57f.png">

**Comment by SherlockStd** [comment]
Thank you very much !
