### ISSUE TITLE
Angular2 router issue 

### ISSUE THREAD

**Issue by itranga** [AngularClass/angular-starter#1771]
Normally in the angular 2 routing with dash we can separate the argument but I am facing a issue if the route as not separated. How will i be handling that situation.

example :-   http://localhost:3000/online-success&conf=first&PAID=N&BID=0&PRN=E-2017-531-1424-9

Please help me as soon as possible.

**Comment by karolmie1** [comment]
Stackoverflow is the place to go in cases like this. You will receive help much faster than here, especially since your question is not repo related.

Remember to flesh out your problem a bit more, because "I'm facing an issue" dont' help much.

**Comment by gdi2290** [comment]
@karolmie1 is correct stackoverflow is way better since this question requires a lot more context to understand what you're trying to do.

do you mean that you can't use the`?` in your url to use the query string?
http://localhost:3000/online-success?conf=first&PAID=N&BID=0&PRN=E-2017-531-1424-9
