### ISSUE TITLE
Npm install fails after install with the `npm run webdriver:update` command

### ISSUE THREAD

**Issue by theAlchemist-dev** [AngularClass/angular-starter#1777]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
I am trying to get the repository setup on my system.
The steps I took:
1. git clone https://github.com/angular-class/angular2-webpack-starter.git 
2. cd angular2-webpack-starter
3. npm install

* **Please tell us about your environment:**
- FreeBSD 10.3 RELEASE p12
- Angular version: 2.0.0-beta.X
- Node 7.8.0
- npm 4.6.1

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

The bug report of npm states:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'webdriver:update' ]
2 info using npm@4.6.1
3 info using node@v7.8.0
4 verbose run-script [ 'prewebdriver:update',
4 verbose run-script   'webdriver:update',
4 verbose run-script   'postwebdriver:update' ]
5 info lifecycle angular2-webpack-starter@6.0.0~prewebdriver:update: angular2-webpack-starter@6.0.0
6 silly lifecycle angular2-webpack-starter@6.0.0~prewebdriver:update: no script for prewebdriver:update, continuing
7 info lifecycle angular2-webpack-starter@6.0.0~webdriver:update: angular2-webpack-starter@6.0.0
8 verbose lifecycle angular2-webpack-starter@6.0.0~webdriver:update: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-webpack-starter@6.0.0~webdriver:update: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/data/node_root/angular-webpack-starter/node_modules/.bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/home/bart/bin
10 verbose lifecycle angular2-webpack-starter@6.0.0~webdriver:update: CWD: /data/node_root/angular-webpack-starter
11 silly lifecycle angular2-webpack-starter@6.0.0~webdriver:update: Args: [ '-c', 'webdriver-manager update' ]
12 silly lifecycle angular2-webpack-starter@6.0.0~webdriver:update: Returned: code: 1  signal: null
13 info lifecycle angular2-webpack-starter@6.0.0~webdriver:update: Failed to exec webdriver:update script
14 verbose stack Error: angular2-webpack-starter@6.0.0 webdriver:update: `webdriver-manager update`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular2-webpack-starter@6.0.0
16 verbose cwd /data/node_root/angular-webpack-starter
17 verbose FreeBSD 10.3-RELEASE-p11
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "webdriver:update"
19 verbose node v7.8.0
20 verbose npm  v4.6.1
21 error code ELIFECYCLE
22 error errno 1
23 error angular2-webpack-starter@6.0.0 webdriver:update: `webdriver-manager update`
23 error Exit status 1
24 error Failed at the angular2-webpack-starter@6.0.0 webdriver:update script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

It seems to be an issue with webdriver.

I am new to npm and node, so I am probably doing something wrong.

Any idea how to fix this?

**Comment by karolmie1** [comment]
This may be very basic thing and I'm sorry if you've already done that.
Remove node_modules, clean npm cache and try again. 
Most of issues I had with npm are weird caching issues.

**Comment by theAlchemist-dev** [comment]
@karolmie1 Thank you for your input.
I have tried these steps, but to no avail.

It keeps failing on the `npm run webdriver:update` cmd

**Comment by karolmie1** [comment]
This might be connected to your operating system.

If for now you can live without selenium server you can simply delete line containing webdriver from package.json. Protractor can directly control browser without need for it with option `directConnect: true`.

You can always install and start selenium server independently, I see there is a package for that: http://portsmon.freebsd.org/portoverview.py?category=www&portname=selenium

I hope someone else will be able to provide you with better solution. I highly recommend creating a stackoverflow question, as it attracts much more trafic and experts attention than this humble repository.

**Comment by theAlchemist-dev** [comment]
Thank you @karolmie1, I will start without the Selenium part and post a issue there!
