### ISSUE TITLE
What is alternative to old vendor.browser.ts ?

### ISSUE THREAD

**Issue by vazham** [AngularClass/angular-starter#1780]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository

Hi. I using angular-starter repository as boilerplate very much time and prevoiusly here are was `vendor.browser.ts` file(in one folder with main.browser.ts) for importing old JS libraries for jquery/momentjs(with needed locale)/fullcelendar/something else. Current repository has no `vendor.browser.ts` and i'm not sure where i should put these js libraries.
Formally i can put these imports everywhere but i want to find best way to do it.

**Comment by gdi2290** [comment]
so when you say old JS libraries are you talking about importing libraries that have globals? if so then import them at the top of main.browser
