### ISSUE TITLE
[AOT bug] current project config can't load some fonts

### ISSUE THREAD

**Issue by vadjs** [AngularClass/angular-starter#1785]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Report bug.

* **What is the current behavior?**
Some fonts(woff, woff2, ttf, eot) can't be loaded with current settings after AOT build but can be loaded well without AOT.
If load all fonts through url-loader, here will be no errors but it's terible solution.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
- Clone this repo.
- Add font-awesome package, require it.
- Build AOT.
- See 404 in fonts requests.

* **What is the expected behavior?**
It's oblivious.

* **What is the motivation / use case for changing the behavior?**
Resolve the bug.

* **Please tell us about your environment:**

- Angular version: 4.1.2
- Browser: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by LuisUrrutia** [comment]
I added font-awesome with this instructions:
https://github.com/AngularClass/angular-starter/wiki/How-to-use-Bootstrap-4-and-Sass-(and-jQuery)#font-awesome

And it works in development, but in AOT build it doesn't works but i hadn't 404 errors

**Comment by vadjs** [comment]
@gdi2290 Any ideas how to fix it?

**Comment by gdi2290** [comment]
I'm going to redo the repo so if you run into the same error feel free to create another issue
