### ISSUE TITLE
I don't see any difference between prod build and aot build

### ISSUE THREAD

**Issue by creib** [AngularClass/angular-starter#1786]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository

* **What is the expected behavior?**
After updating to the latest version of angular-starter and building it once using "npm build:prod" and once using "npm build:aot" I do not see any difference in the resulting dist-folders. Is this as designed?

**Comment by vazham** [comment]
Yes, it is designed.
When you run `build:prod`, it builds static assets with JIT compilation. When you run `build:aot`, it builds static assets with AOT compilation.
In simple words: project with AOT compilation for programmer builds longer, but for user it works faster.

**Comment by creib** [comment]
Thank you for the answer. But I can not imagine, that both buildresults are 100% identically.

**Comment by vincent-cm** [comment]
have u compared the result files line by line?

**Comment by creib** [comment]
I did a binary compare with a tool.

**Comment by gdi2290** [comment]
I made some changes. can you check again. the difference is AoT vs JIT
