### ISSUE TITLE
npm run e2e:live fails to execute

### ISSUE THREAD

**Issue by reddy6ue** [AngularClass/angular-starter#1792]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
I want to report a bug with the e2e:live task in webpack

* **What is the current behavior?**
When I use the command "npm run e2e:live", it fails with the following error

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
Use the "npm run e2e:live" command

* **What is the expected behavior?**
To run the e2e:live command successfully

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 4.1.2
- Browser: [Chrome 59.0.3071.86]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
$ npm run e2e:live

> angular2-webpack-starter@6.0.0 e2e:live D:\Projects\xphase\angular-webpack-starter
> npm-run-all -p -r server:prod:ci protractor:live

> angular2-webpack-starter@6.0.0 server:prod:ci D:\Projects\xphase\angular-webpack-starter
> http-server dist -p 3000 -c-1 --cors

> angular2-webpack-starter@6.0.0 protractor:live D:\Projects\xphase\angular-webpack-starter
> protractor --elementExplorer

Starting up http-server, serving dist
Available on:
  http://10.0.0.31:3000
  http://127.0.0.1:3000
Hit CTRL-C to stop the server
[14:20:41] I/direct - Using ChromeDriver directly...
[14:20:43] E/launcher - TypeError: Unable to create a managed promise instance: the promise manager has been disabled by the SELENIUM_PROMISE_MANAGER environment variable: undefined
    at TypeError (native)
    at new ManagedPromise (D:\Projects\xphase\angular-webpack-starter\node_modules\selenium-webdriver\lib\pro

mise.js:1031:13)
    at new Deferred (D:\Projects\xphase\angular-webpack-starter\node_modules\selenium-webdriver\lib\promise.js:1408:20)
    at Object.defer (D:\Projects\xphase\angular-webpack-starter\node_modules\selenium-webdriver\lib\promise.js:1495:10)
    at DebugHelper.init_ (D:\Projects\xphase\angular-webpack-starter\node_modules\protractor\lib\debugger.ts:83:35)
    at DebugHelper.initBlocking (D:\Projects\xphase\angular-webpack-starter\node_modules\protractor\lib\debugger.ts:31:10)
    at ProtractorBrowser.explore (D:\Projects\xphase\angular-webpack-starter\node_modules\protractor\lib\browser.ts:1149:22)
    at ProtractorBrowser.enterRepl (D:\Projects\xphase\angular-webpack-starter\node_modules\protractor\lib\browser.ts:1113:17)
    at D:\Projects\xphase\angular-webpack-starter\node_modules\protractor\built\frameworks\explorer.js:17:13
    at Function.promise (D:\Projects\xphase\angular-webpack-starter\node_modules\protractor\node_modules\q\q.js:682:9)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor:live"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@6.0.0 protractor:live: `protractor --elementExplorer`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-webpack-starter@6.0.0 protractor:live script 'protractor --elementExplorer'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor --elementExplorer
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\xphase\angular-webpack-starter\npm-debug.log
ERROR: "protractor:live" exited with 1.

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "e2e:live"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@6.0.0 e2e:live: `npm-run-all -p -r server:prod:ci protractor:live`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-webpack-starter@6.0.0 e2e:live script 'npm-run-all -p -r server:prod:ci protractor:live'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all -p -r server:prod:ci protractor:live
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack-starter
npm ERR! Or if t

hat isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\xphase\angular-webpack-starter\npm-debug.log

**Comment by reddy6ue** [comment]
I am running it on Windows 10 64 bit inside a "git bash" window.

**Comment by karolmie1** [comment]
This is caused by my pull request: https://github.com/AngularClass/angular-starter/pull/1778
Obvious fix: revert. 

I'll try to find out why it does not work in this particular case.

**Comment by richarddavenport** [comment]
@karolmie1 Do you think we will be able to get this to work?

**Comment by karolmie1** [comment]
@richarddavenport I don't think I will be able to do that. I tried to find a fix back then, but I came up empty. I'm sorry 😞

**Comment by gdi2290** [comment]
depending on if I can get this to work again I might remove it and protractor all together in a refactor then we can write docs about adding it
