### ISSUE TITLE
In IE 11, SCRIPT5007: Unable to get property 'apply' of undefined or null reference

### ISSUE THREAD

**Issue by munavargit** [AngularClass/angular-starter#1803]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report

* **Do you want to request a *feature* or report a *bug*?**

Bug

* **What is the current behavior?**

When we run in IE 11, we get SCRIPT5007: Unable to get property 'apply' of undefined or null reference, error. After 4 or 5 attempt, it loads the application. However, it works in Chrome.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

It's difficult, it happens, after we upgrade our existing big angular 2.0 application.

* **What is the expected behavior?**

In IE 11, it should work, how it works in Chrome.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

Windows 7, IE 11 browser.

- Angular version: 4.1.2
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

In IE 11, we get **SCRIPT5007: Unable to get property 'apply' of undefined or null reference**. However, after several refresh, some time it loads.

**Comment by gdi2290** [comment]
add an Object.assign polyfill
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility

**Comment by we125182** [comment]
@munavargit I have the same issue, if you have resolve this problem , could you tell me how to?

**Comment by munavargit** [comment]
@Jiande, Resolved, by moving node_modules into vendor.bundle by removing
commented section in webpack.common.js as below,

  */
      new CommonsChunkPlugin({
        name: 'vendor',
        chunks: ['main'],
        minChunks: module => /node_modules/.test(module.resource)
      }),

and, also include the webpack manifest in index.html by adding,

      <% if (webpackConfig.htmlElements.headTags) { %>
  
  <%= webpackConfig.htmlElements.headTags %>
  <% } %>


  <%= htmlWebpackPlugin.files.webpackManifest %>

**Comment by we125182** [comment]
@munavargit thank you for your help. but the problem still exist. it occurs from vendor.chunk.js. maybe i should try something else. if you have another suggetion, please tell me. thank you.

**Comment by munavargit** [comment]
@Jiande, The polyfills i'm using is,

// TODO(gdi2290): switch to DLLs

/**
 * Polyfills
 */

/* import 'ie-shim'; *//* Internet Explorer 9 support */

/* import 'core-js/es6'; */

/**
 * Added parts of es6 which are necessary for your project or your browser
support requirements.
 */
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';
import 'core-js/es6/weak-map';
import 'core-js/es6/weak-set';
import 'core-js/es6/typed';
import 'core-js/es6/reflect';
/**
 * See issue
https://github.com/AngularClass/angular2-webpack-starter/issues/709
 */
 /* import 'core-js/es6/promise'; */

import 'core-js/es7/reflect';
import 'zone.js/dist/zone';

if ('production' === ENV) {
  // Production

} else {

  // Development
  Error.stackTraceLimit = Infinity;

  /* tslint:disable no-var-requires */
  require('zone.js/dist/long-stack-trace-zone');

}

**Comment by we125182** [comment]
@munavargit i cannot thank you enough. i follow your advise, and uncomment the 
/**
       * Specify the correct order the scripts will be injected in
       */
      new CommonsChunkPlugin({
        name: ['polyfills', 'vendor'].reverse()
      }),
and now it works in ie 11.

**Comment by munavargit** [comment]
@Jiande, no problem, happy that I could support.

**Comment by xMarkusSpringerx** [comment]
@we125182 in which file did you specify
```
/**
* Specify the correct order the scripts will be injected in
*/
new CommonsChunkPlugin({
name: ['polyfills', 'vendor'].reverse()
}),
```
