### ISSUE TITLE
It do not work in Chrome 47?

### ISSUE THREAD

**Issue by erichDuanET** [AngularClass/angular-starter#1805]
It has problem in chrome 47

ERROR Error: Uncaught (in promise): TypeError: Cannot set property style of [object Object] which has only a getter(…)

ERROR CONTEXT DebugContext_ {view: Object, nodeIndex: 4, nodeDef: Object, elDef: Object, elView: Object}

**Comment by gdi2290** [comment]
this might be the issue
https://github.com/angular/zone.js/issues/427

**Comment by Uter1007** [comment]
I think we can close this issue, I had the same error in the past.
