### ISSUE TITLE
AOT budles are having Compiled and non compiled code

### ISSUE THREAD

**Issue by nandhaaas** [AngularClass/angular-starter#1807]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
AOT build bundles are having both compiled and uncompiled code which ideally increases the bundle size. Attached a snapshot from bundle analyzer below 

![image](https://user-images.githubusercontent.com/20801446/27274162-e4359744-54ef-11e7-86ae-ba02f99924e4.png)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**
AOT bundle should have only compiled code 

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 4.1.3
- Browser: [all ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by M1strall** [comment]
Any update on this?

**Comment by gdi2290** [comment]
we need a way to remove the decorators but other then that it's by design
