### ISSUE TITLE
AoT vendor bundle still includes @angular/compiler

### ISSUE THREAD

**Issue by daniel-mcassey-tmsuk** [AngularClass/angular-starter#1808]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
On AoT builds the Angular compiler is still included in the vendor bundle.

* **What is the current behavior?**
![chrome_2017-06-19_16-56-45](https://user-images.githubusercontent.com/26789554/27294125-647821cc-5510-11e7-87b3-2ee85b1c55f5.png)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

I expect the AoT build to not have the Angular compiler.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 4.1.3
- Browser: [all]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by M1strall** [comment]
Any update on this issue?

**Comment by shlomiassaf** [comment]
I dont get this

![image](https://user-images.githubusercontent.com/5377501/28702214-357c847c-7364-11e7-976d-865400d7a12b.png)

**Comment by gdi2290** [comment]
running `npm run build:aot:prod` manually also removes the removes the compiler just to be sure via
https://github.com/AngularClass/angular-starter/commit/a839cbf7e5c6faef102c2b054916d1efe007a7a3
