### ISSUE TITLE
DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic

### ISSUE THREAD

**Issue by webmobiles** [AngularClass/angular-starter#1812]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
 .../webpack-dev-server/client/overlay.js
[at-loader] Using typescript@2.2.2 from typescript and "tsconfig.json" from /Users/cherdave/angular4/testrest/tsconfig.webpack.json (in a forked process).
                                                                                           10% building modules 4/7 modules 3 active .../webpack-dev-server/client/overlay.js(node:6147) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils. 10% building modules 7/11 modules 4 active ...ular4/testrest/src/app/environment.tswebpack: wait until bundle finished: /                                                   46% building modules 305/339 modules 34 active ...angular/router/@angular/router.es5.js================================== ng-router-loader ==================================

* **Please tell us about your environment:**

just i've cloned the repository,  npm install, OS  el capitan

**Comment by gdi2290** [comment]
this should be fixed
