### ISSUE TITLE
The generated index.html in prodection has a chance to break the page

### ISSUE THREAD

**Issue by rainbowland302** [AngularClass/angular-starter#1814]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[o] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
console:
`Uncaught reflect-metadata shim is required when using class  #decorators`

The injected bundle files orders as following:
`<script type="text/javascript" src="main.41dfd1a823018db040b3.bundle.js" async></script>`
`<script type="text/javascript" src="polyfills.f9cf3d6f35dbfe7c5f35.bundle.js"></script>`
`<script type="text/javascript" src="vendor.273ffe4dcf322be31b7e.bundle.js"></script>`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
Production mode: with npm run build:prod

* **What is the expected behavior?**
Although the main bundle is async. However the preload has been defined in the head which means that it has the chance that main bundle may be runed before polyfills.
The supposed order should be as following:
`<script type="text/javascript" src="polyfills.f9cf3d6f35dbfe7c5f35.bundle.js"></script>`
`<script type="text/javascript" src="vendor.273ffe4dcf322be31b7e.bundle.js"></script>`
`<script type="text/javascript" src="main.41dfd1a823018db040b3.bundle.js" async></script>`

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by antonovicha** [comment]
Here is fixaround: https://github.com/AngularClass/angular-starter/issues/353#issuecomment-312896857

**Comment by gdi2290** [comment]
I'm manually making sure it's always first now so should be fixed
https://github.com/AngularClass/angular-starter/commit/e0288480a072155aafe3266267369695f1ecaf94
