### ISSUE TITLE
Lazy load [+barrel][+detail] no working.

### ISSUE THREAD

**Issue by minhlunguyen** [AngularClass/angular-starter#1816]
I have a bug with  lazy load [+barrel][+detail]
core.es5.js:1084 ERROR Error: Uncaught (in promise): RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at RouterPreloader.processRoutes

**Comment by d3viant0ne** [comment]
`RangeError: Maximum call stack size exceeded ` is in most cases a lack of a root route.

There is an issue in your lazy loaded module somewhere but without da holistic view of the project, nobody is going to be able to tell you why. 

There is more than a page of information in google when searching that error and in any case, this is an implementation issue not a problem with the starter.
