### ISSUE TITLE
RFC: Use AutoDLL Webpack Plugin

### ISSUE THREAD

**Issue by d3viant0ne** [AngularClass/angular-starter#1817]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

Something worth considering. @asfktz has recently released https://github.com/asfktz/autodll-webpack-plugin

I've been playing around with it a bit and you can't argue with the development experience. 

Only thing that I can see it might be missing would be invalidation if you were developing a module locally but nothing really has that feature now so it's kind of a wash.

**Comment by gdi2290** [comment]
yeah I prefer that over the current way we're doing DLLs

**Comment by t-p-l-k** [comment]
Related PR: https://github.com/AngularClass/angular-starter/pull/1828
