### ISSUE TITLE
Bug AOT compilation with alias

### ISSUE THREAD

**Issue by larxenne** [AngularClass/angular-starter#1818]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**

I'm using aliases in webpack.common.js but when I compile in AOT (and only in AOT) I have the current error:

Error: Error encountered resolving symbol values statically. Could not resolve *alias name* relative to *path*/src/app/app.module.ts., resolving symbol AppModule in *path*/src/app/app.module.ts, resolving symbol AppModule in *path*/src/app/app.module.ts

**Example**

**webconfig.common.js**

`resolve: {
     ...
      alias: {
        Test: './../app/modules/public/team/team.component',
      },
    ...
    },`

**app.module.ts**

import { TeamComponent} from 'Test';

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all ]

**Comment by rkolec** [comment]
I'm getting the same error. Any update on that ?

**Comment by AnimaMundi** [comment]
I'm also getting this error, but I'm not using this project so this bug report is in the wrong place. Not sure exactly where it should go yet, but it could be related to Angular CLI or Webpack itself.

**Comment by gdi2290** [comment]
this is a problem with Angular. You need to also setup your tsconfig to work with the alias. If you did that then it's by design by angular and ngc should support this
