### ISSUE TITLE
TS2343: This syntax requires an imported helper

### ISSUE THREAD

**Issue by Martinspire** [AngularClass/angular-starter#1819]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
I just started using this starter seed and it gives me these 2 errors while compiling. Even though the code seems to be running fine.

```[at-loader] Checking finished with 2 errors
[at-loader] ..\somefile-component.ts:3:1
    TS2343: This syntax requires an imported helper named '__decorate',
but module 'tslib' has no exported member '__decorate'.

[at-loader] ..\somefile-component.ts:3:1
    TS2343: This syntax requires an imported helper named '__metadata',
but module 'tslib' has no exported member '__metadata'.
```

My tsconfig is currently this:

```"compilerOptions": {
        "target": "es5",
        "module": "es2015",
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "allowSyntheticDefaultImports": true,
        "sourceMap": true,
        "noEmit": true,
        "noEmitHelpers": true,
        "importHelpers": true,
        "strictNullChecks": false,
        "lib": [
            "es2015",
            "dom"
        ],
```

I haven't really changed much, but the error still pops up, even with an new component.

**Comment by salacis** [comment]
Same, using current Visual Studio Code on Mac OS.

**Comment by Martinspire** [comment]
@salacis do you have a similar tsconfig?

I'm also using the latest versions btw. Upgraded to Angular 4.2.6 now and also with the other packages.

**Comment by Martinspire** [comment]
Edit, it seems that if I remove these:
`
        "noEmit": true,
        "noEmitHelpers": true,
        "importHelpers": true,` from my tsconfig, it doesn't give me the error. Luckily I don't rely on these being there, but it could be problematic for others.

**Comment by tamohugues** [comment]
I have the same problem, know in my project I see 650 warning for this bug

**Comment by LizaVoskanyan** [comment]
Hi guys , How you did fix this ?

**Comment by Martinspire** [comment]
@LizaVoskanyan I stopped using those values in my config file and haven't really looked back since. I'm not sure if newer versions of various modules helpt fix the problem but I'm not able to check on the project where this specific issue came up

**Comment by BruneXX** [comment]
Hey, What's the proper solution for this? remove those configuration values? that doesn't will get in trouble with other configurations in the project in the future?

**Comment by jberall** [comment]
I just added "moduleResolution": "node"
In the tsconfig.app.json.
While it is redundant from the   "extends": "../tsconfig.json",
 it resolved the issue.
