### ISSUE TITLE
Routing doesn't work on lazyLoaded modules on production

### ISSUE THREAD

**Issue by maisnamraju** [AngularClass/angular-starter#1826]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ *] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
 I ran `npm build:prod` and then ran `npm run server:prod` The application loads fine on the root module and can actually move between routes when using the application but I can't access the application if I put in a direct route. So 
1) going to / and then to /route1 by clicking on the router link would work
2) going directly to /route1 will not work

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**
It should load all routes whether loading directly or not 

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: angular 4.1.2
- Browser: [all ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
I couldn't find any errors in the console as the dev build worked just fine.

**Comment by maisnamraju** [comment]
Fixed it by redirecting all routes on the server to the index.html.

**Comment by oleksaz** [comment]
Can you provide more details, how to do 'redirecting all routes on the server to the index.html'?

**Comment by maisnamraju** [comment]
I am using nginx now so this is what my server block looks like. I didn't want to spend time looking into the node server that is serving the application so this is the fastest way for me.

```
server {
        listen 80 default_server;
        server_name example.com;
        root /applocation/dist;

        index index.html index.htm;

        location / {
               try_files $uri /index.html;
        }

        
}
```
