### ISSUE TITLE
[SOLVED] Using of npm link lead to AoT build failure with "Error: Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported"

### ISSUE THREAD

**Issue by bobrosoft** [AngularClass/angular-starter#1834]
Hope that solution will help somebody:
add next into "compilerOptions" of tsconfig.webpack.json and tsconfig.json:
```
    "baseUrl": ".",
    "paths": {
      "@angular/*": ["node_modules/@angular/*"]
    }
```

References:
 - https://github.com/angular/angular-cli/issues/3854
 - https://github.com/trekhleb/angular-library-seed#using-yarn-link

**Comment by bobrosoft** [comment]
Will be closed tomorrow.

**Comment by gdi2290** [comment]
Thanks for figuring it out. Can you make a PR

**Comment by bobrosoft** [comment]
@gdi2290 ou, ye, even forgot about that :) Will do it later.

**Comment by bobrosoft** [comment]
- added PR #1835 
 - added reference links to first comment

**Comment by bobrosoft** [comment]
Thanks for merge 🐻

**Comment by gdi2290** [comment]
thanks for finding the fix

**Comment by qasimraza1979** [comment]
This does not solve my problem.....

Please advice should the error below considered as a different issue or its same. I am sure its the same..

Here below is the exact error message that I am receiving when try to link one of myCustom angular component library with my IonicProject.  I am using the following command.
`_ionic-app-scripts build --prod_`

**Error message** 
` Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider
            replacing the function or lambda with a reference to an exported function (position 756:18 in the original
            .ts file), resolving symbol Component in
            C:/Monsenso-Source/administration/node_modules/@monsenso/components/node_modules/@angular/core/core.d.ts,
            resolving symbol LoginComponent in
            C:/Monsenso-Source/administration/node_modules/@monsenso/components/lib/components/login/login.component.d.ts,
            resolving symbol LoginComponent in
            C:/Monsenso-Source/administration/node_modules/@monsenso/components/lib/components/login/login.component.d.ts`

It works when its with out `--prod`

**command that works**
`_ionic-app-scripts build_`

any pointer / advice ..

**Comment by bobrosoft** [comment]
@qasimraza1979 sounds as usual AoT issue, not related to that one. Search on internet, there are plenty of info on your issue.

**Comment by qasimraza1979** [comment]
@bobrosoft  i did a lot but haven't got a working solution.

**Comment by qasimraza1979** [comment]
I found the solution and will share here below

placed following two line into the tsConfig.json into the Angular CLI project (in my case my ionic project)

![image](https://user-images.githubusercontent.com/1721866/31439193-9d151952-ae8b-11e7-8352-468e12638bc9.png)

saved my life. It was a tough journey for a month now but nailed it ;-)

**Comment by alyssa19** [comment]
why mine is still not working? I tried all the given solution but still have same error.

**Comment by bobrosoft** [comment]
@qasimraza1979 how is that different to my first comment? :)
