### ISSUE TITLE
Update Webpack v2 to v3

### ISSUE THREAD

**Issue by alanhg** [AngularClass/angular-starter#1838]
webpack 3: Official Release!!
update webpack2 to 3,it can reduce bundle-size!
We don't need to modify conf file.
<img width="583" alt="qq20170724-205727 2x" src="https://user-images.githubusercontent.com/9245110/28524376-c83367f4-70b2-11e7-8d03-7558b1f7762f.png">

**Comment by gdi2290** [comment]
thanks, the repo has been updated to webpack 3
