### ISSUE TITLE
Can't resolve url(xx)'s in css when building AOT.

### ISSUE THREAD

**Issue by Bigless27** [AngularClass/angular-starter#1840]
* **I'm submitting a ...**
[ X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
report a bug

* **What is the current behavior?**
The current behavior is when I use an AOT build that includes any `url: (xx)` in css they get overlapped by the `styleUrls` in the component which loads the style sheets as well but not with the correct `url: (xx)` path. The ExtractTextPlugin resolves the `url:(xx)s` in the css to the correct path. My work around right now is to take all the `url:(xx)` I use in the css and put them in a separate folder outside of the `styleUrls` array. While this isn't ideal, I'm wondering if this is the correct behavior I should see when building AOT.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
To Reproduce the bug just simply add a background-image: `url:(xx)` to any css file that's linked to a style sheet to see this. Here is my use case: I want to use the class .image-add in the app.component.css.
```
html,
body {
    height: 100%;
    font-family: Arial, Helvetica, sans-serif
}

a.active {
    background-color: gray;
}

.image-add {
    background-image: url('src/assets/img/angular-logo.png');
    height: 100px;
    width: 100px;
}
```

* **What is the expected behavior?**
The expected behavior is the `styleUrls` either resolve the `url:(xx)` to the correct path or just have the ExtractTextPlugin do it.

* **What is the motivation/use case for changing the behavior?**
The motivation for changing this behavior is that it's not straight forward. I spent days trying to figure out what to do to get my css `url:(xx)'s` working. Also, I would want to encapsulate some of the `url:(xx)'s` instead of making them all global with the extract text plugin which is the current behavior. Lastly, I want to use the `background-size: cover` property on my image which when using an image tag is all hacky to try and implement the same functionality. 

* **Please tell us about your environment:**

- Angular version: ~4.3.1
- Browser: [all | Chrome Version 59.0.3071.115
- Webpack: ~2.6.1
- Extract-text-webpack-plugin: ~2.1.0
- Angular2-template-loader: ^0.6.2
- All other versions align with the current projects versions

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Here is my Webpack config file for prod:
```

function root(args) {
    args = Array.prototype.slice.call(arguments, 0);
    return path.join.apply(path, [__dirname].concat(args));
}

module.exports = {
    entry: {
        'app': './client/main.aot'
    },
    output: {
        path: root('/dist'),
        filename: '[name].bundle.js',
        publicPath: 'https:.....' //changed
    },
    devServer: {
        historyApiFallback: true,
        contentBase: path.join(__dirname, '/dist/')
    },
    module: {
        rules: [
            { test: /\.ts$/, loader: "awesome-typescript-loader?configFileName=tsconfig-aot.json!angular2-template-loader", exclude: [/\.(spec|e2e)\.ts$/] },
            { test: /\.(html)$/, loader: 'raw-loader' },
            {
                test: /\.css$/,
                loader: ExtractTextPlugin.extract({
                    fallback: "style-loader",
                    use: "css-loader"
                })
            },
            {
                test: /\.pug$/,
                loader: 'raw-loader!pug-html-loader'
            },
            {
                test: /\.js$/,
                loader: 'babel-loader',
                exclude: /node_modules/,
                query: {
                    presets: ['es2015']
                }
            },
            {
                test: /\.(png|jpe?g|svg|gif|woff|woff2|ttf|eot|ico)$/,
                loader: 'file-loader?name=assets/[name].[hash].[ext]'
            },
        ]
    },
    resolve: {
        extensions: ['.js', '.ts', '.json', '.css', '.scss', '.html']
    },
    plugins: [

        //adds app.bundle script tage to html
        new webpack.NoEmitOnErrorsPlugin(),
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false
            },
            output: {
                comments: false
            },
            sourceMap: false
        }),

        new webpack.DllReferencePlugin({
            context: process.cwd(),
            manifest: require(path.join(dllPath, '/vendor.json'))
        }),

        new HtmlWebpackPlugin({
            filename: 'index.html',
            inject: true,
            templateContent: templateContent()
        }),

        new webpack.DefinePlugin({
            'process.env': {
                'API_URL': JSON.stringify('https...'),
                ' NODE_ENV': JSON.stringify(process.env.NODE_ENV)
            },
        }),

        new webpack.ProvidePlugin({
            jQuery: 'jquery',
            $: 'jquery',
            jquery: 'jquery'
        }),

        new CleanWebpackPlugin(
            [
                './dist'
            ]
        ),

        new CopyWebpackPlugin([
            { from: dllPath, to: 'dist/', flatten: false }
        ]),

        new webpack.ContextReplacementPlugin(
            // The (\\|\/) piece accounts for path separators in *nix and Windows
            /angular(\\|\/)core(\\|\/)@angular/,
            root('./client'), // location of your src
            {}
        ),
        new ExtractTextPlugin({ "filename": "[name].css" })
    ]
};

```
Any help is greatly appreciated! You guys rule!

**Comment by gdi2290** [comment]
thanks for the detailed issue can you try `assets/img/angular-logo.png`? you might need to change `publicPath` in webpack's config

**Comment by Bigless27** [comment]
@gdi2290 Hey yeah, I don't know why I changed it from that. So that relative path works in Development, but not when running AOT. It's because the app.css version (which resolves correctly) get's overlapped by the `StyleUrls` version in the components.
