### ISSUE TITLE
Update ngc-webpack with it's AOT cleanup loader

### ISSUE THREAD

**Issue by shlomiassaf** [AngularClass/angular-starter#1841]
Version 3.1.0 of `ngc-webpack` comes with a loader that clean's up all decorator code when using AOT mode.

**I'll post more info in the next issue-comment.**

Using loaders for this job is not optimal but currently the only option  due to lack of readiness from TS transformers API.

Transformers version is ready but will not work in some scenarios (e.g. with ngrx-effects)

The loader is based on the same logic and code in `ngtools/webpack` and tested against the output they yield.

There are some differences since `ngtools/webpack` exports non-valid TS code in some scenarios which will fail in `awesome-typescript-loader`. It does not fail in `ngtools/webpack` since they own the transpilation process (not using a loader for that) which means they can silence these errors.

I'll post a PR for that.

> The loader requires opt-in and will not work by just upgrading the package.

**Comment by shlomiassaf** [comment]
### AOT Cleanup loader

The AOT cleanup loader is a an optional loader to be added to webpack that will remove angular decorators from the TypeScript source code.

As the name suggests, the loader should run **only** when compiling AOT, if you run it when the target is JIT the application will fail to run.

The **AOT cleanup loader** removes all angular decorators (e.g.  `NgModel`, `Component`, `Inject` etc...) from TypeScript code before the main TS loader kicks in (`ts-loader`, `awesome-typescript-loader`, etc...).
The decorators are not needed in AOT mode since the AOT compiler converts the metadata in them into code and saves it in `ngfactory.ts` files.

It is always recommended to run the **AOT cleanup loader** for AOT production build as it will:

  1. Reduces the bundle size
  2. Speeds up initial bootstrap time and any future `NgModule` lazy loading

The impact volume depends on the application size.
Bigger application = more decorators = more effect.

> Speed up in initial bootstrap is not significant and unnoticeable in most cases.

#### Loader options:
```ts
export interface AotCleanupLoaderOptions {
  /**
   * If false the plugin is a ghost, it will not perform any action.
   * This property can be used to trigger AOT on/off depending on your build target (prod, staging etc...)
   *
   * The state can not change after initializing the plugin.
   * @default true
   */
  disable?: false;

  /**
   * A path to a TSConfig file, optional if a plugin is supplied.
   * When both are available `tsConfigPath` wins.
   */
  tsConfigPath?: any;

  /**
   * Optional TS compiler options.
   *
   * > Some options set by the loader can not change.
   */
  compilerOptions?: any;
}
```

#### Loader VS TypeScript transformers
The **AOT cleanup loader** is a temporary solution to solve the cleanup problem. It is not the optimal one.

The optimal solution is to use the `Transformers API` in **TypeScript**.
The API is not complete nor stable which is why the loader approach is used.
**ngc-webpack** library has a transformer implementation ready and exposed but not documented yet since it will fail on certain use cases due to bugs in the transformers API.

#### Webpack config example:
```
{
  test: /\.ts$/,
  use: [
    {
      loader: 'awesome-typescript-loader',
      options: {
        configFileName: 'tsconfig.webpack.json',
      }
    },
    {
      loader: 'ngc-webpack',
      options: {
        disable: false,                   // SET TO TRUE ON NON AOT PROD BUILDS
      }
    },
    {
      loader: 'angular2-template-loader'
    }
  ]
}

// This setup assumes NgcWebpackPlugin is set in the plugins array.
```

#### Real time loader analysis

The following table displays an analysis of the bundling process with
and without the loader. The source is an Angular application (v 4.3.1)
with a total **177** angular decorators spread across 140,527 TypeScript lines
of code (42,796 net total of actual source LOC).

This a small to medium size application.

> Note that 177 decorators means a combination of all angular decorators, some emit more boilerplate then others (e.g. `@Component` vs `@Injectable`)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Non Minified**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Minified (UglifyJS)**

|                | Webpack compile time (sec) | Final Bundle Size (kb) |   | Webpack compile time (sec) | Final Bundle Size (kb) |
|----------------|:--------------------------:|:----------------------:|:-:|:--------------------------:|:----------------------:|
|   With Loader  |                        115 |                   1721 |   |                        138 |                    467 |
| Without Loader |                        118 |                   1848 |   |                        143 |                    491 |
|      Diff      |                          **3** |                    **127** |   |                          **5** |                     **24** |


##### Bundle Size
The bundle size is also reduces, around 7% for non minified and 5% for minified.
This is substantial and will increase over time.


> Initial bootstrap improvement was not measured, I don't think it is
noticeable.


##### Time
Time is not that interesting as bundle size since it's not effecting the
user but the results surprised me so I dag in.

We can see a small decrease of webpack runtime.
While we add an extra loader that does TS processing we reduce the
payload for following loaders and plugins. Decorators emit boilerplate
that they won't need to process.
The additional processing we add is less then we remove. It get stronger
When using UglifyJS, again, it has less data to minify.


##### Memory footprint (webpack)
The loader use's it's own TS compilation process, this is an additional
process that consumes memory. The compilation example ran with
`--max_old_space_size=4096`.

> Using `resourceOverride` plugin option has no effect when using the loader.

**Comment by gdi2290** [comment]
LGTM

**Comment by shlomiassaf** [comment]
![image](https://user-images.githubusercontent.com/5377501/28701451-07a7a748-735f-11e7-8bd3-85e01c09062e.png)

3.1.0 is now identical to `AotPlugin`

**Comment by gdi2290** [comment]
can you merge a PR with the update?

**Comment by shlomiassaf** [comment]
I have only one concern, the loader in `@ngtools/webpack` that works with the `AotPlugin` is running inside it's own compiler.

It emits JS code directly.

The loader in `ngc-webpack` is "typescript loader agnostic" so it does not emit JS but TS output.

Now, I used most of the code from `@ngtools/webpack` but they have some bugs that does not effect runtime but do effect type checking so I had to fix that. 

I tested it on a large app with a lot of goodies but I'm thinking if we can introduce this in phases?

Upgrade to 3.1.0, add the line for the loader but comment it out with an explanation.
Once we gather feedback we can remove the comment...

Again, I don't think it will error but it might so I want to be on the safe side.

**Comment by shlomiassaf** [comment]
BTW, once TypeScript **Transformers API** get's solid the loader will not be used, instead we can use a transformer sent as a parameter to `awesome-typescript-loader` which will make it a lot more safe and deterministic... part of the language.

I have it ready but it fails on edge cases that TS does not handle properly..

**Comment by gdi2290** [comment]
yeah I trust you with any changes with that 👍

**Comment by shlomiassaf** [comment]
Ok, I pushed a PR with the loader live, let's pray :)

PR #1842

**Comment by shlomiassaf** [comment]
BTW, can you tell me, running on your projects, what's the difference in bundle size?

**Comment by Koslun** [comment]
@shlomiassaf Your suspicions seems to have been correct, as adding the loader did break our project. As we use server side rendering I added them to the same place in the loader chain on both client and server bundles, as we other than the server-side rendering steps largely have the same setup webpack config as in this starter.

After the `Angular compilation done, starting webpack bundling` output we got a single error message: `Couldn't parse bundle asset ...`, where it finished by referencing our main bundle. 

The app in question has about 52k LOC with 114 components, 2 directives, 46 services and 13 pipes, so at least 175 angular decorators in our source code.

Did try building with the loader exclusively on the client and not on the server bundle, but regardless experienced the same crash during compilation.

Hopefully works for most other people.

**Comment by pglazkov** [comment]
I'm getting the following error:
```
Module build failed: TypeError: loaderUtils.getOptions is not a function                                                          
    at Object.aotCleanLoader (<project_path>\node_modules\src\aot-clean-transformer\loader\loader.ts:225:60)
```
The version of `loader-utils` is `0.2.17`.

**Comment by shlomiassaf** [comment]
Looks like I forgot to add that dependency
I'll do that for next version

Installing it will solve it for now

**Comment by pglazkov** [comment]
It is installed (because many other packages depend on it). I think the issue is with the version (`0.2.17`) -
 it doesn't contain the `getOptions` function.

**Comment by shlomiassaf** [comment]
Ok will check

**Comment by shlomiassaf** [comment]
@pglazkov It is installed by chance, that is installed because (as your described) some other package depends on it.

I just posted version 3.1.1 that requires it as a dependency, which should solve it.

I can only guess that it didn't fail in travis tests (and didn't fail in my local setup) due to npm/yarn/npm5 differences... :)

Travis script uses npm 5 and it does cache verify, prune and update which probably fixes it.

I cloned a clean repo and did install with npm, npm5 and yarn and all passed without issues since the global `loader-utils` modules selected was 1.1.0 and not 0.2.17.

So again, my guess is some kind of caching stuff that left the old 0.2.17 in place.

Once green keeper will detect the update i'll merge the PR

**Comment by shlomiassaf** [comment]
@Koslun Most of the issues I had during development of the AOT cleaner were type related, things that `awesome-typescript-loader` checker didn't like...

I have tested the loader on somewhat similar app but without server side rendering.
It had ngrx goodies in it and other stuff, works fine.

I guess it's something in the chain that breaks, maybe improper setup... hard to tell without more info
