### ISSUE TITLE
 loaderUtils.getOptions is not a function

### ISSUE THREAD

**Issue by vincent-cm** [AngularClass/angular-starter#1843]
After adding ngc-webpack loader in config file:

`
{
              loader: 'ngc-webpack',
              options: {
                disable: !AOT,
              }
            },
`
When start in momery or build as prod, the following error occur:

`
ERROR in ./src/main.browser.ts
Module build failed: TypeError: loaderUtils.getOptions is not a function
    at Object.aotCleanLoader (~/node_modules/src/aot-clean-transformer/loader/loader.ts:225:60)
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8888 ./src/main.browser.ts

ERROR in ./src/polyfills.browser.ts
Module build failed: TypeError: loaderUtils.getOptions is not a function
    at Object.aotCleanLoader (~/node_modules/src/aot-clean-transformer/loader/loader.ts:225:60)
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8888 ./src/polyfills.browser.ts

`

using     

    "ngc-webpack": "~3.1.0",

    "@types/webpack": "^3.0.5",
    "add-asset-html-webpack-plugin": "^2.0.1",
    "assets-webpack-plugin": "^3.5.1",
    "copy-webpack-plugin": "^4.0.1",
    "extract-text-webpack-plugin": "~3.0.0",
    "html-webpack-plugin": "^2.30.0",
    "inline-manifest-webpack-plugin": "^3.0.1",
    "karma-webpack": "^2.0.4",
    "preload-webpack-plugin": "^1.2.3",
    "script-ext-html-webpack-plugin": "^1.8.5",

    "webpack": "~3.4.1",
    "webpack-dev-middleware": "^1.11.0",
    "webpack-dev-server": "~2.6.1",
    "webpack-dll-bundles-plugin": "^1.0.0-beta.5",
    "webpack-merge": "~4.1.0"

**Comment by gdi2290** [comment]
this should be fixed already
