### ISSUE TITLE
Integration with Material Web Components

### ISSUE THREAD

**Issue by AKlaus** [AngularClass/angular-starter#1846]
**I'm submitting a ...**
- [x] feature request

Please provide an example on integrating the _angular-starter_ project with [Material Web Components](https://material.io/components/web/).

---

It looked that the best option would be to utilise [angular-mdc-web](https://github.com/trimox/angular-mdc-web)  (an Angular wrapper for [Material Web Components](https://material.io/components/web/)), but  I wasn't able to integrate it with the _angular-starter_ project due to the following issue:

```
File to import not found or unreadable: @material/animation/variables.
Parent style sheet: C:/Dev/WebUI/node_modules/@material/button/mdc-button.scss
```

Process Monitor showed me that WebPack is looking for the `_variables.scss` file in wrong folders - either `\node_modules\@material\button\@material\animation\` or `@material\animation\variables` of the project root, when the actual location is `\node_modules\@material\animation\`.

It looks more as an integration issue of the _Material Web Components_, but if you could give me some ideas on fixing the problem, it would be very appreciated.

P.S. It's a duplicate for a [corresponding issue](https://github.com/trimox/angular-mdc-web/issues/67) for [angular-mdc-web](https://github.com/trimox/angular-mdc-web)

**Comment by trimox** [comment]
If anyone else needs this in the future..

**Step 1**: Install glob in angular-starter 
Console: `npm i glob`

**Step 2**: Edit `angular-starter/config/webpack.dev.js`
Replace these lines
`
          test: /\.scss$/,
          use: ['style-loader', 'css-loader', 'sass-loader'],
          include: [helpers.root('src', 'styles')],
`

With these lines
`
          use: [
            'style-loader',
            'css-loader', {
              loader: 'sass-loader',
              options: {
                includePaths: ['../node_modules', '../node_modules/@material/*']
                  .map((d) => path.join(__dirname, d))
                  .map((g) => glob.sync(g))
                  .reduce((a, c) => a.concat(c), [])
              }
            },
          ]
`

**Step 3**: Create a `/src/app/styles/mdc.scss` file.
Add one line that imports the MDC styles.
```css
@import "material-components-web/material-components-web";
```

**Step 4**: Import Angular MDC and mdc.scss into `app.module.ts`
```ts
import { MaterialModule } from '@angular-mdc/web';
import '../styles/mdc.scss';
```

** Screengrab of [Angular MDC](https://github.com/trimox/angular-mdc-web) Button and Checkbox loaded in** [AngularClass/angular-starter](https://github.com/AngularClass/angular-starter)

![image](https://user-images.githubusercontent.com/11887843/28871734-e6664974-7753-11e7-9242-8a19bc8b8873.png)

**Comment by geoHeil** [comment]
Isn't it correct that according to https://github.com/trimox/angular-mdc-web/blob/master/docs/getting-started.md

```
/** <link> tags for a fonts **/
    { rel: 'stylesheet', href: 'https://fonts.googleapis.com/icon?family=Material+Icons' }
```

and setting
`  <body mdc-typography>`
is missing?

**Comment by AKlaus** [comment]
As trimox's response here has gathered more attention than on the [other thread](https://github.com/trimox/angular-mdc-web/issues/67), so, for completeness sake, I'll copy my addition to his answer here.

The [angular-starter](https://github.com/AngularClass/angular-starter) comes with a bunch `config/webpack.***.js` configurations, the answer above is fine for the `dev` and `test` files:
```
{
  test: /\.scss$/,
  use: ['style-loader',
           'css-loader',
           {
             loader: 'sass-loader',
             options: {
               /*
                * Handle Material Components styles
                */
                includePaths: ['../node_modules', '../node_modules/@material/*']
                      .map((d) => path.join(__dirname, d))
                      .map((g) => glob.sync(g))
                      .reduce((a, c) => a.concat(c), [])
             }
           }
         ],
  include: [helpers.root('src', 'styles')]
}
```
However, the `prod` configuration would be slightly different due to using `extract-text-webpack-plugin`:
```
{
  test: /\.scss$/,
  loader: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [{ loader: 'css-loader' },
          { loader: 'sass-loader',
            options: {
                /*
                * Handle Material Components styles
                */
                includePaths: ['../node_modules', '../node_modules/@material/*']
                  .map((d) => path.join(__dirname, d))
                  .map((g) => glob.sync(g))
                  .reduce((a, c) => a.concat(c), [])
              }
          }
          ],
  }),
  include: [helpers.root('src', 'styles')]
},
```

And on a different note, @geoHeil, I don't see how is your comment relevant to the subject. Usage of Material icons and declaratives aren't the problem posted in this thread.

**Comment by AKlaus** [comment]
## Bug
A follow-up issue on the `AngularClass/angular-starter + MDC-Web` integration.
The described above solution worked well at the time, but since a new version of [MDC](https://github.com/material-components) was released, it generates the following compilation error:
```
ERROR in ./~/css-loader!./~/sass-loader/lib/loader.js?{"includePaths":["C:/Users/AKlaus/Downloads/1/node_modules","C:/Users/AKlaus/Downloads/1/~/@material/animation","C:/Users/AKlaus/Downloads/1/~/@material/auto-init","C:/Users/AKlaus/Downloads/1/~/@material/base","C:/Users/AKlaus/Downloads/1/~/@material/button","C:/Users/AKlaus/Downloads/1/~/@material/card","C:/Users/AKlaus/Downloads/1/~/@material/checkbox","C:/Users/AKlaus/Downloads/1/~/@material/dialog","C:/Users/AKlaus/Downloads/1/~/@material/drawer","C:/Users/AKlaus/Downloads/1/~/@material/elevation","C:/Users/AKlaus/Downloads/1/~/@material/fab","C:/Users/AKlaus/Downloads/1/~/@material/form-field","C:/Users/AKlaus/Downloads/1/~/@material/grid-list","C:/Users/AKlaus/Downloads/1/~/@material/icon-toggle","C:/Users/AKlaus/Downloads/1/~/@material/layout-grid","C:/Users/AKlaus/Downloads/1/~/@material/linear-progress","C:/Users/AKlaus/Downloads/1/~/@material/list","C:/Users/AKlaus/Downloads/1/~/@material/menu","C:/Users/AKlaus/Downloads/1/~/@material/radio","C:/Users/AKlaus/Downloads/1/~/@material/ripple","C:/Users/AKlaus/Downloads/1/~/@material/rtl","C:/Users/AKlaus/Downloads/1/~/@material/select","C:/Users/AKlaus/Downloads/1/~/@material/selection-control","C:/Users/AKlaus/Downloads/1/~/@material/slider","C:/Users/AKlaus/Downloads/1/~/@material/snackbar","C:/Users/AKlaus/Downloads/1/~/@material/switch","C:/Users/AKlaus/Downloads/1/~/@material/tabs","C:/Users/AKlaus/Downloads/1/~/@material/textfield","C:/Users/AKlaus/Downloads/1/~/@material/theme","C:/Users/AKlaus/Downloads/1/~/@material/toolbar","C:/Users/AKlaus/Downloads/1/~/@material/typography"]}!./src/styles/styles.scss
Module build failed:
undefined
          ^
      Invalid style specified! Choose one of primary, accent, background, text-primary-on-primary, text-secondary-on-primary, text-hint-on-primary, text-disabled-on-primary, text-icon-on-primary, text-primary-on-accent, text-secondary-on-accent, text-hint-on-accent, text-disabled-on-accent, text-icon-on-accent, text-primary-on-background, text-secondary-on-background, text-hint-on-background, text-disabled-on-background, text-icon-on-background, text-primary-on-light, text-secondary-on-light, text-hint-on-light, text-disabled-on-light, text-icon-on-light, text-primary-on-dark, text-secondary-on-dark, text-hint-on-dark, text-disabled-on-dark, text-icon-on-dark
      in C:\Users\AKlaus\Downloads\1\node_modules\@material\theme\_mixins.scss (line 26, column 12)
 @ ./src/styles/styles.scss 4:14-134
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts
```

## Steps to reproduce

1. Have a clean `AngularClass/angular-starter`
1. Install  [material-components-web](https://github.com/material-components/material-components-web)
1. Apply the fix from the above.
1. Build

## Mitigation steps
An early version of the `node_modules/@material` folder (from 3 weeks ago or older) doesn't cause the problem. 
However, due to the `@material` folder gets installed implicitly by the `material-components-web` package, it can't be easily rolled back via the `package.json` file. Even worse, after clearly setting `material-components-web` to version `0.16`, I still get the new `@material` folder. :(
So the only workaround I've got is to manually replace the `node_modules/@material` folder with one I had locally from 3 weeks (or so) ago.

## Help neeeded
It's obviously a configuration issue, as it works in examples supplied by `MDC-Web` and `angular-mdc-web`. So would AngularClass experts mind give us advice on proper configuration?

**Comment by AKlaus** [comment]
Closing. MDC v0.19.0 resolves versioning problems.
