### ISSUE TITLE
Webpack 3 docs confused

### ISSUE THREAD

**Issue by talamaska** [AngularClass/angular-starter#1850]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ *] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Problems with dependencies requiring webpack 3, but despite the docs the package.json shows the project is build with webpack2.x

* **What is the current behavior?**

Here is what happens: Installing preload-webpack-plugin ^1.2.2 as set in package json, actually installs 1.2.3 which has a breaking change of having webpack 3.2 as peer dependency instead of webpack 2.x. 

* **What is the expected behavior?**

upgrade webpack to v3, or fix the version of preload-webpack-plugin

* **What is the motivation / use case for changing the behavior?**

webpack 2 is outdated and unsupported

* **Please tell us about your environment:**

- Angular version: 4.3
- Browser: not browser related

**Comment by gdi2290** [comment]
thanks, the repo has been updated to webpack 3
