### ISSUE TITLE
Why is the DLL config for webpack disabled/commented ?

### ISSUE THREAD

**Issue by fabm22** [AngularClass/angular-starter#1851]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[X] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

A feature, ie would like to know if DLL chunks can be used currently.

* **What is the current behavior?**

No  DLL config in webpack files. Those lines are commented see...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

...this line (on 03 august 2017) https://github.com/AngularClass/angular-starter/blob/master/config/webpack.dev.js#L145

Would this be related to the webpack-dll-bundles-plugin perhaps ?

**Comment by gdi2290** [comment]
I'll be adding auto dll soon
