### ISSUE TITLE
http://c/Users/Public/info... net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by hasan-assi** [AngularClass/angular-starter#1853]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[X ] bug report

* **Do you want to request a *feature* or report a *bug*?**

Report a bug

* **What is the current behavior?**

I got this error more than 10 time in console

GET http://c/Users/Public/info?t=1501942575415 net::ERR_NAME_NOT_RESOLVED

Other strange behavior is after run it "npm run server", it opens "http://c/Users/Public/" instead of "localhost:3000"

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via

Build the solution with a fresh clone of the repo. using master .
I'm using windows 10 and the error logged in chrome 

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by ltinyho** [comment]
@hasan-assi the reason is e1f25d9，when I delete them,this is work !

**Comment by hasan-assi** [comment]
@ltinyho thanks! yes it works after deleting these lines

**Comment by hasan-assi** [comment]
delete the added lines in  "https://github.com/AngularClass/angular-starter/commit/e1f25d9b208c4d64226b5792452b445fd6ec5020" 
solve the issue.

**Comment by brijesh3601** [comment]
Visit below stackoverflow discussion to resolve http://c/Users/Public/ issue on start of server

https://stackoverflow.com/questions/45641480/angular4-webpack-opens-file-location

**Comment by testacp** [comment]
.
