### ISSUE TITLE
Bootstrap components like tooltip, modal not being recognised

### ISSUE THREAD

**Issue by Abhijith-Nagaraja** [AngularClass/angular-starter#1854]
* **I'm submitting a ...**
[X] bug report

* **Do you want to request a *feature* or report a *bug*?**
Bug Report
Bootstrap Not Working Properly

* **What is the current behavior?**
Modal, tooltip and other functions which require jQuery is Not getting recognized.
We followed https://github.com/AngularClass/angular-starter/wiki/How-to-use-Bootstrap-4-and-Sass-(and-jQuery) to setup bootstrap and jQuery.

Error in browser console

ERROR TypeError: jQuery(...).modal is not a function
ERROR TypeError: jQuery(...).tooltip is not a function

jQuery itself is working. jQuery(some-selector) returns valid element.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://github.com/Abhijith-Nagaraja/Angular-WebPack-Starter-with-Bootstrap

* **What is the expected behavior?**
No errors should happen and modal or tooltip show be shown

* **Please tell us about your environment:**

- Angular version: 4.3.1
- Browser: [all]

**Comment by gdi2290** [comment]
you need to include your script after jquery and run them
