### ISSUE TITLE
No template specified for component TestComponent

### ISSUE THREAD

**Issue by bhanu7755** [AngularClass/angular-starter#1857]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
**bug**

* **What is the current behavior?**

When using template: require('./test.component.html') and trying to build using **AoT** throwing below error

Error: No template specified for component TestComponent

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

compilation complete without errors.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by RaphaelYan** [comment]
For AOT, use `templateUrl` :
```
  templateUrl: './test.component.html',
```

**Comment by bhanu7755** [comment]
Thank you for reply. But the problem is I'm publishing it as package. So, When I use **templateUrl** it is throwing error saying  **Template not found** in the other project where we are using this package. I thought it is trying to find the html in the src directory instead of node_modules.

**Comment by RaphaelYan** [comment]
Have you tried with inline templating like this lib ? https://github.com/valor-software/ngx-bootstrap/blob/development/src/accordion/accordion-group.component.ts

**Comment by bhanu7755** [comment]
Yes, inline templating works. I want to make it clean and more maintainable. Any thoughts on it?
