### ISSUE TITLE
Not suitable to use `process.env.PUBLIC` on Win

### ISSUE THREAD

**Issue by yuki-takei** [AngularClass/angular-starter#1859]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
    * Reporting a *bug*

* **What is the current behavior?**

1. Windows 10
1. clone master that is after [e1f25d9] (commited by @patricknazar )
1. `npm start` 

    * My browser try to open `c/Users/Public/` when exec `npm start`.
    * This comes from
        ```javascript
        const PUBLIC = process.env.PUBLIC || undefined;
        ```
        in `/config/webpack.dev.js`
        * https://github.com/AngularClass/angular-starter/blob/master/config/webpack.dev.js#L24

* **What is the expected behavior?**
    * Browser try to open `http://${HOST}:${PORT}`.

* **What is the motivation / use case for changing the behavior?**
    - Windows set the environment variable `PUBLIC=c:\Users\Public`
    - But most of windows users don't notice `process.env.PUBLIC` has already been set.
    - IMO, it's better to define the different env var instead of `PUBLIC`
        - e.g.
        ```javascript
        const PUBLIC = process.env.PUBLIC_DEV || undefined;
        ```

* **Please tell us about your environment:**
    - Angular version: ~4.3.1
    - angular-starter: [e1f25d9]
    - Browser: Firefox 52.3.0 (32 bit)

**Comment by patricknazar** [comment]
Fair point. Thoughts on this?

**Comment by reneszabo** [comment]
Same, i had to add PUBLIC=d:\Projects\Public to my .env

**Comment by artbelikov** [comment]
+1 Also have this issue

**Comment by Womballs** [comment]
Same, no fix yet ?

**Comment by gdi2290** [comment]
can someone make a PR for this?

**Comment by diegohdez90** [comment]
Hi. I have an issue like this. In my console show me this https://gist.github.com/diegohdez90/76d0b6a0a85e0bd796814822c8686eb8.
Check out in the line 12.
My application is running at `http://localhost:3000`

**Comment by ohadinho** [comment]
Same here.
