### ISSUE TITLE
TSLint: non-arrow functions are forbidden (only-arrow-functions)

### ISSUE THREAD

**Issue by tamtakoe** [AngularClass/angular-starter#1868]
I tryed to move my code into the AngularStarter project and seen great mistake highlighting in the WebStorm
`TSLint: non-arrow functions are forbidden (only-arrow-functions)`

The first think which I caught was "Guys, are you OK?". I hope it was stupid mistake which you missed. Change, please linter settings to more adequate :-)

AngularStarter 6.0.0

**Comment by tamtakoe** [comment]
Also
`TSLint: Expected property shorthand in object literal ('{headers}'). (object-literal-shorthand)`
`TSLint: Parentheses are required around the parameters of an arrow function definition (arrow-parens)`

This is strange situation if you allow shorthand in one place and disallow in other one

**Comment by tamtakoe** [comment]
Also
`TSLint: trailing whitespace (no-trailing-whitespace)`
can't be useful  because IDEAs adds spaces automatically when you create empty string

**Comment by tamtakoe** [comment]
`TSLint: block is empty (no-empty)`
`public ngOnInit() {}` can be empty or not?

**Comment by gdi2290** [comment]
fixed via https://github.com/AngularClass/angular-starter/commit/620f0218c733dea35bb365bcc51c0ff7797be6da
