### ISSUE TITLE
Since Angular 4.3.4 app.component.scss is ignored

### ISSUE THREAD

**Issue by gplume** [AngularClass/angular-starter#1870]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

Bug in Angular itself, what do you think?

* **What is the current behavior?**

Styles in `app.component.scss` are ignored since Angular version 4.3.4 ONLY in `build:dev` **not with AOT or JIT prod compiling.**

* **What is the expected behavior?**

It was ok until Angular 4.3.3 but maybe it is related to: [#18802](https://github.com/angular/angular/issues/18802?_pjax=%23js-repo-pjax-container) ?

* **Please tell us about your environment:**
- Webpack: 3.5.5
- Angular version: 4.3.4/4.3.5
- Browser: [ Chrome XX | Firefox XX  ]
- OS: Linux Ubuntu 16.04

**Comment by m98** [comment]
What's your build script?

**Comment by gdi2290** [comment]
it's just as you mention in that issue. you need to use a preprocessor to compile the scss into css before angular reads it or bypass angular from handling styles all together

**Comment by gplume** [comment]
> it's just as you mention in that issue. you need to use a preprocessor to compile the scss into css before angular reads it or bypass angular from handling styles all together
--

Of course my sccs is compiled first as it work with `build:aot` for example...
I just meant that with `build:dev` `app/component.scss` or `app.component.css` are not loaded when the app starts. My code has to be in `assets/style.scss` to be read before the app is loaded. And why does it has changed since Angular `4.3.4` ?
