### ISSUE TITLE
BrowserAnimationsModule + HMR = multiple <app> tags 

### ISSUE THREAD

**Issue by gr8den** [AngularClass/angular-starter#1873]
* **I'm submitting a ...**
[*] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
Previous `<app>` tag don't remove from DOM after HMR when use `BrowserAnimationsModule`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. add `import { BrowserAnimationsModule } from '@angular/platform-browser/animations';` to app.modules.ts
2. add `BrowserAnimationsModule` to @NgModule imports
3. `npm run server:dev:hmr`
4. use HMR

* **Please tell us about your environment:**
- Angular version: 4.3.1
- Browser: Chrome 60

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
_First run:_
![1](https://user-images.githubusercontent.com/19634251/29739397-68e87196-8a6f-11e7-8444-7bbad57d5c18.png)
_after HMR:_
![2](https://user-images.githubusercontent.com/19634251/29739396-68e68eb2-8a6f-11e7-9b4d-e5057b1a0d5c.png)

**Comment by mbonig** [comment]
Seeing same issue. Would like a resolution, cause the BrowserAnimationsModule is less important than a nice HMR setup in dev.

**Comment by gdi2290** [comment]
the hmr version was outdated. I'll push up the changes

**Comment by gdi2290** [comment]
fixed via https://github.com/AngularClass/angular-starter/commit/599b71fdbdbc790524985a409ac7a108b9bddb6b
