### ISSUE TITLE
npm run clean:install gives me Access is denied even with an admin command prompt

### ISSUE THREAD

**Issue by VictorioBerra** [AngularClass/angular-starter#1898]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
Running `npm run clean:install` gives me this:

```
> npm cache clean --force && npm run rimraf -- node_modules doc coverage dist compiled dll

npm WARN using --force I sure hope you know what you are doing.

> angular-starter@6.0.0 rimraf C:\Source\BBEEWT\iamm.web.site.easervicemanager\EaServiceManager.WebUI
> rimraf "node_modules" "doc" "coverage" "dist" "compiled" "dll"

Access is denied.
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
Windows 10, 64bit, admin command prompt

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by amumei** [comment]
Experienced similar behaviour. The reason being that rimraf (located in node_modules) will try to delete & unlink itself. This is a Windows issue as Unix filesystems do not have this limitation.
I found this [rimraf issue](https://github.com/isaacs/rimraf/issues/102) useful.
