### ISSUE TITLE
Add flex-layout

### ISSUE THREAD

**Issue by lmarcelocc** [AngularClass/angular-starter#1899]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
No errors are throw but ht flex-layout is not being ran.

* **What is the expected behavior?**
That flex-layout works.

* **Please tell us about your environment:**

- Angular version: 4.4.x-beta.X
- Browser: [at least Chrome]

Hi all,

I'm using [Angular Starter](https://github.com/AngularClass/angular-starter) and I'm trying to install flex-layout on it but without success.

This is my package.json
```
"dependencies": {
    "@angular/animations": "~4.4.x",
    "@angular/cdk": "github:angular/cdk-builds",
    "@angular/common": "~4.4.x",
    "@angular/compiler": "~4.4.x",
    "@angular/core": "~4.4.x",
    "@angular/flex-layout": "git+https://github.com/angular/flex-layout-builds.git",
    "@angular/forms": "~4.4.x",
    "@angular/http": "~4.4.x",
    "@angular/material": "github:angular/material2-builds",
    "@angular/platform-browser": "~4.4.x",
    "@angular/platform-browser-dynamic": "~4.4.x",
    "@angular/platform-server": "~4.4.x",
    "@angular/router": "~4.4.x",
    "@angularclass/hmr": "~2.1.3",
    "@angularclass/hmr-loader": "^3.0.4",
    "angular2-jwt": "^0.2.3",
    "core-js": "^2.4.1",
    "http-server": "^0.9.0",
    "ie-shim": "^0.1.0",
    "ngx-restangular": "^1.0.11",
    "reflect-metadata": "^0.1.10",
    "rxjs": "~5.0.2",
    "zone.js": "0.8.14"
  },
```

and this is part of my app.module.ts:
```
...
// @https://github.com/angular/flex-layout
import { FlexLayoutModule } from "@angular/flex-layout";

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    FlexLayoutModule // Import flex-layout
  ],
  providers: [],
  bootstrap: [AppComponent],
  entryComponents: []
})
export class AppModule { }
```

but when I use this example:
```
<div class="containerX">
    <div fxLayout="row wrap" class="colored box nopad" >
        <div fxFlex="none">     [flex="none"]       </div>
        <div fxFlex>            [flex]              </div>
        <div fxFlex="nogrow">   [flex="nogrow"]     </div>
        <div fxFlex="grow">     [flex="grow"]       </div>

        <div fxFlex="33.33%">   [flex="33.33%"]     </div>
        <div fxFlex="33.33%">   [flex="33.33%"]     </div>
        <div fxFlex="33.33%">   [flex="33.33%"]     </div>

    </div>          
</div>
```

what I get is:
<img width="686" alt="test" src="https://user-images.githubusercontent.com/6483007/31390331-8747a3e4-adcb-11e7-983f-88447f7a996e.png">

Thank you all for your help!

**Comment by PascalHonegger** [comment]
I'm currently using this started project together with `"@angular/material": "2.0.0-beta.12"` and `"@angular/flex-layout": "2.0.0-beta.9"` without any problems. Copying your example works as expected (except the colored background as I don't have the css for .containerX .colored .box .nopad). Maybe some part of your CSS is screwing with flexbox in general? If you debug your page withing e.g. Chrome you should be able to see if the flexbox-classes are applied.

**Comment by lmarcelocc** [comment]
Hi,

got what I've done wrong. I'm newbie on this. Since it was a new module, I need to re-import the flex layout on this module....dahh!

Thank you for you help.
