### ISSUE TITLE
Update Description 

### ISSUE THREAD

**Issue by itaditya** [AngularClass/angular-starter#1901]
The description of the repo says webpack v2 but the Readme says Webpack v3 please fix it

**Comment by gdi2290** [comment]
can you make a PR?

**Comment by bartholomej** [comment]
@gdi2290 We can't make a PR for this. Only you can change github repo description ;)

**Comment by gdi2290** [comment]
oops my bad. done

**Comment by itaditya** [comment]
Happy to help
