### ISSUE TITLE
karma + chrome

### ISSUE THREAD

**Issue by daniele-zurico** [AngularClass/angular-starter#275]
Hi guys,
first of all great job.. this starter kit is amazing.
I'm trying to run:
npm run watch:test
but I would to debug my code in chrome so what I've done is in karma.conf.js enable that:

``` es6
browsers: [
  'Chrome',
  'PhantomJS'
]
```

As expected chrome open a new window, I can press debug button, in the console it show the error but the problem is that is impossible to debug the code because it just load the spec-bundle.js.
There's a way to put a breakpoint in my code?
thanks

**Comment by gdi2290** [comment]
sorry about that, and I'm glad you like the starter :smiley: I haven't tried out the debug flow for testing so I would need to look into it more

**Comment by alvipeo** [comment]
Yeah, that would be great! (to debug tests)

**Comment by daniele-zurico** [comment]
No news about that one?

**Comment by sammichelson** [comment]
I agree debugging tests are impossible now

**Comment by gdi2290** [comment]
sorry this may sound super rule but I'm closing long standing issues and refactoring the codebase. If you run into this problem again feel free to open another issue
