### ISSUE TITLE
Improve coverage report

### ISSUE THREAD

**Issue by cschroeter** [AngularClass/angular-starter#286]
Is there any reason to include spec files into coverage results? 
I mean it is great to see that at least some files have 100% coverage but well yeah meh

How about:

```
preprocessors: {
  'src/**/!(*.spec).ts': ['coverage']
},
```

**Comment by alvipeo** [comment]
Yeah, that's actually bothers me too... Looks weird.

**Comment by cschroeter** [comment]
In addition, if a component don't have a corresponding spec file, it should appear within the result

**Comment by gdi2290** [comment]
@cschroeter can you make a pull-request?

**Comment by cschroeter** [comment]
I'm not that familiar with all the webpack magic, but I'll give it a shot

**Comment by gdi2290** [comment]
I think the change should be here 
https://github.com/AngularClass/angular2-webpack-starter/blob/71026ba56f696d184ddad6837863e7b55378db59/webpack.test.config.js#L62

**Comment by cschroeter** [comment]
It gets tricky if a component don't have a corresponding spec file since you include it in your Karma configuration, code get executed no matter what. 

I would suggest before executing test to run a plugin showing a warning for files not have a corresponding spec file.

@gdi2290 What is your opinion on that?

**Comment by gdi2290** [comment]
We can make a module that will earn the developer

**Comment by gdi2290** [comment]
sorry this may sound super rule but I'm closing long standing issues and refactoring the codebase. If you run into this problem again feel free to open another issue
