### ISSUE TITLE
Debugging unit tests

### ISSUE THREAD

**Issue by sumigoma** [AngularClass/angular-starter#361]
When trying to debug unit tests, the presence of instanbul and the coverage reporter causes the code to get minified as described here:
http://bahmutov.calepin.co/debugging-karma-unit-tests.html
https://github.com/karma-runner/karma/issues/630

Removing the istanbul-intrumenter loader postLoader from webpack.test.config.js "fixes" the issue, but it'd be nice to have a way of omitting the webpack postLoader and karma preprocessor/reporter for coverage when debugging, or conversely only applying these when a code coverage report is desired.

**Comment by abierbaum** [comment]
@sumigoma Have you found a good way around this yet?

What I would like to see is a way to pass a parameter into the build such that we could have a watch:test_nocoverage and test:nocoverage script.

**Comment by yjaaidi** [comment]
+1

**Comment by gdi2290** [comment]
sorry this may sound super rule but I'm closing long standing issues and refactoring the codebase. If you run into this problem again feel free to open another issue
