### ISSUE TITLE
Request: hit breakpoints in browser dev tools

### ISSUE THREAD

**Issue by BrainCrumbz** [AngularClass/angular-starter#425]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**
  When serving in development mode (`npm start`), one can open browser on `http://localhost:3000/`. When setting a breakpoint, e.g. in [home.ts](https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/app/home/home.ts#L30), and reloading page, execution should pause on that line.
- **What is the current behavior?**
  Breakpoint seems to be ignored. Execution proceeds beyond that. Client app runs normally, no particular errors.
- **What is the expected behavior?**
  Execution should pause on breakpoint set.
- **What is the motivation / use case for changing the behavior?**
  Debugging purposes.
- **Please tell us about your environment:**
- HEAD: https://github.com/AngularClass/angular2-webpack-starter/commit/9736a48019d92e7fb029e8af4667cd74492454be
- Angular version: 2.0.0-beta.9
- Browser: [Chrome 49.0.2623.87 m | Firefox 45.0]

**Comment by dvulanov** [comment]
+1 

Breakpoints don't work in constructors or event hooks (like OnInit, AfterViewInit, etc...).  For me, they do work during regular method callbacks.

(using beta 9 and Chrome dev tools)

**Comment by dvulanov** [comment]
+10!

Actually, now I can't hit any breakpoints?!  If anyone knows a solution, please share.  I imagine there must be a solution.  You can't develop without a debugger!

Thanks for any help

**Comment by samvloeberghs** [comment]
same here, using the new setup, my breakpoints are not working anymore. Perhaps something to do with the sourcemaps implementation used?

**Comment by BrainCrumbz** [comment]
We definitely found some differences with sourcemap. Initially we tried with `devtool: 'cheap-module-eval-source-map'`, that should be faster for development rebuilds. But breakpoints did not work with this.

Then we tried with (slower) `devtool: 'source-map'` and breakpoints are hit.

**Comment by samvloeberghs** [comment]
@BrainCrumbz : I can also confirm this

**Comment by largeDachshund** [comment]
Just to clarify, I used cheap-module-eval-source-map.  From Chrome Dev Tools, when I clicked in main.bundle.js to set a break point, I expected Chrome to open open my class (in typescript).  The break point would land on the ugly javascript in main.bundle.js.  But who can read this?  

I followed @BrainCrumbz suggestion.  I'm able to click in the javascript source and Chrome resolves the breakpoint in the respective typescript class.

Thanks, @BrainCrumbz !

**Comment by BrainCrumbz** [comment]
You're welcome! Happy to be helpful @largeDachshund

**Comment by phil-lgr** [comment]
@BrainCrumbz are you able to hit breakpoints with "sourcemap" when using HMR ? 
with I run with `server:dev:hmr` (which is `npm run server:dev -- --inline --hot`), hot module works but when it does the hot-reload I can't hit the same breakpoint.

Initial state after starting `server:dev:hmr`:

Breakpoint is set.

![image](https://cloud.githubusercontent.com/assets/9644867/19445718/868b10e4-9463-11e6-85b6-17df625bed13.png)

I add `console.log("hot")` to my code, and after the hot reload this happen:

![gif](https://cloud.githubusercontent.com/assets/9644867/19445946/77e6fcdc-9464-11e6-90d4-3f22ab4bd1ed.gif)

**Comment by BrainCrumbz** [comment]
Sorry, we're using this starter at the moment, and I've not checked back this issue recently. Maybe someone else more up-to-date with it can reply.

**Comment by gdi2290** [comment]
sorry this may sound super rule but I'm closing long standing issues and refactoring the codebase. If you run into this problem again feel free to open another issue
