### ISSUE TITLE
getting `Uncaught TypeError: Cannot read property 'location' of undefined` in 4.0.0

### ISSUE THREAD

**Issue by fxck** [AngularClass/angular-starter#457]
- **I'm submitting a ...**
  bug report
- **What is the current behavior?**
  after updating a file, this happens 

![image](https://cloud.githubusercontent.com/assets/1303561/13948557/f6e6c6ea-f020-11e5-8dbf-c85035f69a33.png)

and it doesn't reload

the line it points to is this - 

![image](https://cloud.githubusercontent.com/assets/1303561/13948596/298fc524-f021-11e5-8158-d6237cf45f33.png)

it might be happening only in my app, since I'm manually updating it.. but do you have any pointers what might be causing this?

**Comment by gdi2290** [comment]
can you elaborate more on what you meant by manually updating it?

**Comment by fxck** [comment]
That I looked at the latest commits and copy pasted the stuff that has changed, and I might have overlooked some change that's causing this, but I can't figure out what it is...

**Comment by gdi2290** [comment]
the code above is for hot module replacement. you can turn it off by using `npm run server:dev` rather than `npm run server:dev:hmr` which is the default task when using `npm start`

**Comment by fxck** [comment]
yea I do want hot module replacement.. guess I just go thru all the changes again and see if I didn't miss anything

**Comment by gdi2290** [comment]
you still get live reloading the other change is src/app/app.service.ts that is injecting WebpackState

**Comment by mburger81** [comment]
Same error for me

**Comment by gdi2290** [comment]
sorry this may sound super rule but I'm closing long standing issues and refactoring the codebase. If you run into this problem again feel free to open another issue
