### ISSUE TITLE
IE9 - pushState

### ISSUE THREAD

**Issue by sasidhar** [AngularClass/angular-starter#489]
This is a Bug
Browser : Internet Explorer 9
Operating System : Windows 7
Angular : 2 beta 13

After adding `shims_for_IE.js` from angular2 repository for missing `requestAnimationFrame`, now I am facing issue with `pushState`.

Because of this, I am not able to move to other pages and the URL is not updating with the hash.

![ie9-pushstate](https://cloud.githubusercontent.com/assets/897339/14195792/58e3d06a-f772-11e5-973a-1b61f6d4ff24.png)

**Comment by sasidhar** [comment]
Might be Angular 2 bug

https://github.com/angular/angular/issues/6506

**Comment by gdi2290** [comment]
@sasidhar thanks for taking the time to figure out all the bugs with IE9

**Comment by ristomattia** [comment]
This issue is still valid. I'm testing this using an otherwise unmodified version 5.1.1 of this starter. It has Angular 2.1.1 in its dependencies.

The only changes have been to disable hash routes in `app.module.ts`:
```javascript
RouterModule.forRoot(ROUTES, { useHash: false })
```
and to enable IE shims in `polyfills.browser.ts`:
```javascript
// Polyfills

import 'ie-shim'; // Internet Explorer 9 support
```

**Comment by sallar** [comment]
@ristomattia I guess for now you can do this:

``` js
RouterModule.forRoot(ROUTES, { useHash: Boolean(history.pushState) === false })
```

**Comment by ristomattia** [comment]
@sallar Brilliant! The issue seems to be gone based on my initial tests. Also the routing seems to work on browser reload. Thanks!

**Comment by gdi2290** [comment]
sorry this may sound super rule but I'm closing long standing issues and refactoring the codebase. If you run into this problem again feel free to open another issue

**Comment by gdi2290** [comment]
I added Boolean(history.pushState) === false
