### ISSUE TITLE
HowTo: get absolut path of required file

### ISSUE THREAD

**Issue by mburger81** [AngularClass/angular-starter#495]
As described in Wiki i need a howto:

How can I get a absolut final URL path of a required file?

`var Locomote = require('./assets/js/locomote.min.js');`

how can I get the absolut final path and filename of loaded file in require?

**Comment by samvloeberghs** [comment]
@mburger81 why do you need this is the first question that pops up in my mind?

**Comment by mburger81** [comment]
I need to create a component which lives alone, any file needed by this component should be copied into the component folders.

For example on this component I load a javascript which need to passing the SWF Player.

```
var Locomote = require('./assets/js/locomote.min.js');

@Component({
....
....

    ngOnInit() {
        this.locomote = new Locomote('player', './assets/swf/Player.swf');
....
....
```

in this example loading with require `./assets/js/locomote.min.js` works fine, the problem is on creating Locomote instance I need to pass the right place of the player, in this example
Locomote loads the Player from `http://localhost:3000/assets/swf/Player.swf` but that is wrong. I need to know where is my file to pass the absolute URL to Locomote, this and others does not work with relative URL paths.

I hope I explained it well.

**Comment by gdi2290** [comment]
sorry this may sound super rule but I'm closing long standing issues and refactoring the codebase. If you run into this problem again feel free to open another issue
