### ISSUE TITLE
Metadata portion defined in dev.js and prod.js does not make its way any further.

### ISSUE THREAD

**Issue by saldoukhov** [AngularClass/angular-starter#496]
- **I'm submitting a ...**
  [x ] bug report
- **What is the current behavior?**
  f.e. Include
  `<script>console.log('<%= webpackConfig.metadata.port %>');</script>
  `
  into index.html - it prints nothing.
  Because of this, 

```
  <% if (webpackConfig.metadata.ENV === 'development') { %>
  <!-- Webpack Dev Server reload -->
  <script src="/webpack-dev-server.js"></script>
  <% } %>

```

has no effect

I think metadata needs to be included for merging in both dev and prod configs, in addition to the common one.

**Comment by gdi2290** [comment]
sorry this may sound super rule but I'm closing long standing issues and refactoring the codebase. If you run into this problem again feel free to open another issue

**Comment by saevae** [comment]
the fuck dude

**Comment by gdi2290** [comment]
this was fixed awhile ago via
```
  <% if (htmlWebpackPlugin.options.metadata.isDevServer && htmlWebpackPlugin.options.metadata.HMR !== true) { %>
  <!-- Webpack Dev Server reload -->
  <script src="/webpack-dev-server.js"></script>
  <% } %>
```
