### ISSUE TITLE
getting 404 when loading images and fonts from node_modules

### ISSUE THREAD

**Issue by MurhafSousli** [AngularClass/angular-starter#508]
Hi,
I installed `font-awesome` and `jquery-ui` using npm, and I got problem integrating them in my project. 

images and fonts are not loading relatively to their parents, instead it's trying to get them from the root directory

I tried loading the styles from the **app.component.ts**

```
@Component({
  selector: 'app',
  encapsulation: ViewEncapsulation.None,
  styles: [
    require('font-awesome/css/font-awesome.css'),
    require('jquery-ui/themes/flick/jquery.ui.theme.css'),
    require('./app.scss'),
  ],
```

**Exceptions:**

```
GET http://localhost:3000/images/ui-bg_highlight-soft_100_f6f6f6_1x100.png 404 (Not Found)
GET http://localhost:3000/images/ui-icons_666666_256x240.png 404 (Not Found)
GET http://localhost:3000/images/ui-bg_glass_65_ffffff_1x400.png 404 (Not Found)
GET http://localhost:3000/fonts/fontawesome-webfont.woff2?v=4.5.0 
GET http://localhost:3000/fonts/fontawesome-webfont.woff?v=4.5.0 
GET http://localhost:3000/fonts/fontawesome-webfont.ttf?v=4.5.0 
```

I saw this [issue](https://github.com/AngularClass/angular2-webpack-starter/issues/402) and I followed what it says, I looked for `exclude: [ helpers.root('node_modules') ]` in _webpack.common.js_ to remove it but it's not there.

I thought about copying both folder from `node_modules` to `src/assets/css`  and tried to load them from there in *\* app.scss**

```
@import '../assets/css/font-awesome/css/font-awesome.min.css';
@import '../assets/css/themes/flick/theme.css';
```

same exceptions, it is still trying to load the images and the fonts from the root directory, how can I fix this and load them locally?

**Comment by ebeal** [comment]
The exceptions are from files referenced by the files you're including. The libraries assume they are still in the same location with their sub folders and so are requesting them based on that. I'd suggest rather than doing it this way include the libraries in your index file like you would normally since you're adding them to your app component anyways.

See : https://angular.io/docs/ts/latest/guide/component-styles.html#!#relative-urls

**Comment by gdi2290** [comment]
sorry this may sound super rule but I'm closing long standing issues and refactoring the codebase. If you run into this problem again feel free to open another issue
