### ISSUE TITLE
How would I use the framework for the $httpBackend?

### ISSUE THREAD

**Issue by pearljamik** [AngularClass/angular-starter#512]
This framework is great and all but it makes things a little darker.
I want to do similar thing like here:

```
myAppDev = angular.module('myAppDev', ['myApp', 'ngMockE2E']);
myAppDev.run(function($httpBackend) {
  phones = [{name: 'phone1'}, {name: 'phone2'}];

  // returns the current list of phones
  $httpBackend.whenGET('/phones').respond(phones);

  // adds a new phone to the phones array
  $httpBackend.whenPOST('/phones').respond(function(method, url, data) {
    var phone = angular.fromJson(data);
    phones.push(phone);
    return [200, phone, {}];
  });
  $httpBackend.whenGET(/^\/templates\//).passThrough();
  //...
});
```

How would I write the same thing, but using the framework (e2e tests protractor). Could someone give me the exact 1:1 matching so I could understand it better? This could be added to documentation.

**Comment by t0rrro** [comment]
https://www.npmjs.com/package/ng-mock-e2e

**Comment by gdi2290** [comment]
sorry this may sound super rule but I'm closing long standing issues and refactoring the codebase. If you run into this problem again feel free to open another issue
