### ISSUE TITLE
webDriverProxy does not work

### ISSUE THREAD

**Issue by pearljamik** [AngularClass/angular-starter#523]
When I added  webDriverProxy: 'http://localhost:3128', it does not use it, it still uses the base url.

**Comment by MarkPieszak** [comment]
Are you referring to web-dev-server (webpack) `proxy`?

**Comment by spock123** [comment]
If you're talking about the proxy setting for the webpack-dev-server, here is an example from my setup:

`devServer: {
        port: 7000,
        host: 'localhost',
        historyApiFallback: true,
        watchOptions: {
            aggregateTimeout: 300,
            poll: 1000
        },
         proxy: {
            '/api/*': {
                target: 'http://localhost:5000',
                secure: false
            }
        },
        outputPath: 'dist'
    },`

**Comment by gdi2290** [comment]
sorry this may sound super rule but I'm closing long standing issues and refactoring the codebase. If you run into this problem again feel free to open another issue
