### ISSUE TITLE
ExceptionHandler doesn't work if i try to add it before bootstrap(... comand

### ISSUE THREAD

**Issue by Somiks** [AngularClass/angular-starter#533]
ExceptionHandler doesn't work if i try to add it before bootstrap(... comand
- **I'm submitting a ...**
  [ ] bug report
- **What is the motivation / use case for changing the behavior?**
- **What is the current behavior?**
  I'm trying to make popup message for all errors and sent it to server.
- **Please tell us about your environment:**
- Angular version: 2.0.0-beta.13

**Comment by MarkPieszak** [comment]
There isn't a lot of information to work with here, you might want to try posting much more detail on Stackoverflow to get help with this one.

**Comment by gdi2290** [comment]
sorry this may sound super rule but I'm closing long standing issues and refactoring the codebase. If you run into this problem again feel free to open another issue
