### ISSUE TITLE
How's the service worker status?

### ISSUE THREAD

**Issue by naivefun** [AngularClass/angular-starter#557]
Any plan to release? Would be great for chrome hosted apps. Thanks.

**Comment by NekR** [comment]
@naivefun  I think you need this issue: https://github.com/AngularClass/angular2-webpack-starter/issues/728

**Comment by gdi2290** [comment]
sorry this may sound super rule but I'm closing long standing issues and refactoring the codebase. If you run into this problem again feel free to open another issue
