### ISSUE TITLE
Compiler errors don't stop tests

### ISSUE THREAD

**Issue by abierbaum** [AngularClass/angular-starter#568]
- **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
- **What is the current behavior?**

When running the tests using `npm run test` or `npm run watch:test` the test run will continue even if there are compiler errors. 
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via

Add a call to an unknown function name in any function in the application code.
- **What is the expected behavior?**

Compiler failure would hit and stop the rest of the build.
- **What is the motivation / use case for changing the behavior?**

In my case with a large test suite this is a pretty big problem because I just see the output from the test run, not the compiler issue.  This allows for silent compiler errors that I need to fix but I miss.
- **Please tell us about your environment:**
- Angular version: 2.0.0-rc.1
- Browser: [all]

**Comment by gdi2290** [comment]
sorry this may sound super rule but I'm closing long standing issues and refactoring the codebase. If you run into this problem again feel free to open another issue
