### ISSUE TITLE
Webpack + Angular2 require in template

### ISSUE THREAD

**Issue by galsch** [AngularClass/angular-starter#571]
Hi,

I ran your project and everything works fine. However, when I did a more simplified version of Webpack + Angular2 I got the following problem:

When defining a component with requiring html template like this: 

@Component({
selector: 'test',
template: require('./test.component.html')
})

I get the following error:

Error:(22, 12) TS2345: Argument of type '{ selector: string; template: {}; directives: Type[][]; }' is not assignable to parameter of type '{ selector?: string; inputs?: string[]; outputs?: string[]; properties?: string[]; events?: strin...'.
Types of property 'template' are incompatible.
Type '{}' is not assignable to type 'string'.

I fix it by using: 
@Component({
selector: 'test',
template: "" + require('./test.component.html') + ""
})

In your project you have home.component.ts configured like this and it works without warning.

How did you solve this issue as it works perfectly without warning in your project? 

Thanks

**Comment by gdi2290** [comment]
I can't reproduce the error. Do you have a link to your setup?

**Comment by justme1** [comment]
Issue resolved can close issue:

https://github.com/Microsoft/TypeScript/issues/8514
