### ISSUE TITLE
Angular2-webpack VS ng-cli

### ISSUE THREAD

**Issue by zigzag95** [AngularClass/angular-starter#586]
Guys,
We love what you did and what you are doing.
But now I think it's time to ask himself the question:
Continue with webpack or switch to ng-cli with system.js?

Could someone please help me with some pros and cons of both solutions?

**Comment by dsebastien** [comment]
That's a hard one for now I think :p
Personally I'd stick with Webpack for a while longer

**Comment by ebeal** [comment]
I think this actually helps settle some of the previous discussions about making this repo with less overhead, from what I've seen from using the cli it makes a pretty slim(comparatively) repo that is more tailored toward immediate, fast development. I think this repo can be more of an example app or teaching tool demonstrating different features like universal, css encapsulation, animations etc.

**Comment by gdi2290** [comment]
Eventually, this repo will turn into a few plugins for ng-cli.

**Comment by zigzag95** [comment]
in ng-conf pkozlowski invoked a new ng bundling reducing to less than 50k the bundle.js.
Also, I'm not sure new router will be compatible with webpack

**Comment by gdi2290** [comment]
The new router will be. Webpack is the way to go. Bundle size will be smaller with webpack 2

**Comment by zigzag95** [comment]
@gdi2299 Glad reading your last comment

**Comment by zigzag95** [comment]
All we are missing is a kinda yoeman templates.

**Comment by Krisa** [comment]
I see the value of using the cli with Systemjs good for prototyping. In one or two lines, you already have a base Angular2 application. Yet, System.js is way more limited compared to Webpack and I would be careful to use System.js over Webpack for any big application.

On another hand, for knowing Webpack since now a few months, it's "sometimes" a pain to configure correctly, but this project helps a lot to get started with and I would highly recommend it for any medium/large project.

Also regarding the new router: I've started an Angular2 project few weeks ago based on this repo and then customized Webpack and all the rest to my needs. No problem getting the new router to work, you just need to follow the guide https://angular.io/docs/ts/latest/guide/router.html or anything similar. It's very little about Webpack actually, much more about Angular2 itself.

**Comment by joaogarin** [comment]
I personally think also that webpack for production apps is the way to go. there is definitely value in the CLI but I thik there is a lot to gain with webpack like was already mentioned here, good things land on webpack from all the communities not just Angular and that is a a benefit just on its own.

That being said I am sure that webpack will eventually be supported in the cli project as well. While that does not happen I would stick with an approach like this project.

**Comment by joaogarin** [comment]
Personally the current starter as is its of no use to me as a starting point because there is just way too many stuff on it, but I do pick up on great ideas here to create my own starters or adapt my projects. So thanks @gdi2290 and all the other guys contributing for the project;)

**Comment by tapas4java** [comment]
@gdi2290 Why don't you start an angular-cli addon using webpack now. I am sure lot of people will help to make webpack part of ng cli.

**Comment by mrukas** [comment]
I have to agree with @joaogarin. The webpack approach seems to be more tailored towards building an production ready environment. For me webpack really offers everything i need for nearly every use case regarding web application development. Also don't forget that webpack 2 offers native support for loading es6 modules and even provides "tree-shaking" for creating even smaller builds. I doesn't know anything that systemjs can do, that webpack 2 doesn't.

But regarding Angular-CLI i have to say, that i like this approach for scaffolding web applications. Ember JS showed us how this needs to be done. So in my opinion a combination of angular cli and webpack would be the ultimate solution.

**Comment by joshuawilson** [comment]
I just saw that there is a webpack branch on Angular-cli. https://github.com/angular/angular-cli/tree/webpack

**Comment by Namek** [comment]
@joshuawilson Yeah but the webpack configuration file is hidden under the ng cli. Not sure how to add 3rd party dependencies in there right now.

**Comment by zigzag95** [comment]
I would like to use ng-cli but I'm afraid it would be a kind of jail since the webpack conf is in node_modules.
If they extract a user webpack conf and merge it on build it will be great.

**Comment by mvdcorput** [comment]
Configurability of webpack would make this a great success

**Comment by katallaxie** [comment]
@zigzag95 Regarding Yo, I have a generator for the Starter https://github.com/katallaxie/generator-angular2-webpack-class

**Comment by xinmeng1** [comment]
ng-cli has change to use webpack:

> Webpack update

> We changed the build system between beta.10 and beta.12, from SystemJS to Webpack. And with it comes a lot of benefits. To take advantage of these, your app built with the old beta will need to migrate.
> 
> You can update your beta.10 projects to beta.12 by following these instructions.

**Comment by albandaft** [comment]
ng-cli is very handy, good for quick start, good for class generation, it removes a lot of boilerplate, but it is hard to go through fine tuning in the configuration.

Webpack-Starter webpack based is good for managing configuration, loaders, assets at low level, I feel it is more stable and incredibly for the same project I get 2.17Mb of vendor.js where with ng-cli I get 3.7Mb of vendor.js.

I prefer the webpack for now, until ng-cli gets more stable

**Comment by dancancro** [comment]
angular-cli now has an "eject" feature that frees you up to configure your project as you wish https://github.com/angular/angular-cli/commit/7ac0d0562641bc862a3487084cd090bce40713b4

**Comment by gdi2290** [comment]
updates will go here
https://github.com/AngularClass/angular-starter/issues/1686
