### ISSUE TITLE
mobile-toolkit

### ISSUE THREAD

**Issue by BhaskaranR** [AngularClass/angular-starter#617]
can we have app-shell and mobile-toolkit implemention with this repo?

**Comment by gdi2290** [comment]
ya

**Comment by Luchillo** [comment]
@gdi2290 I've been digging into `app-shell` the last days and i can only imagine `app-shell` as using the root component and first route as the app-shell, then setting all other routes as lazy load, however at finish loading of the first route it should trigger a fetch for each other page so that it is cached by a service worker.

How would (if possible) trigger that fetch?

**Comment by gdi2290** [comment]
yup, I already made the module to trigger the fetches

**Comment by Luchillo** [comment]
Sooo.. it is as i imagined, the first page is the shell and all other pages are fetched afterwards, cool.

Btw where do you do the fetch? i'm scanning the code but can't figure out where that fetch happens.

**Comment by Luchillo** [comment]
Ah that's the `webpack-toolkit` package for, cool.

Soo... the new router is async by default and the `webpack-toolkit` takes care of the fetching?

**Comment by gdi2290** [comment]
it's a combination of webpack-toolkit, es6-promise-loader, and webpack

**Comment by Luchillo** [comment]
So adding web workers with sw-cache would create an offline app as it is, right?

**Comment by Luchillo** [comment]
@gdi2290 I've been testing the latest master repo about the thing i told you with fetching the async routes after `app-shell` finishes loading, and it doesn't fetch the async routes.

I tested like this, i open the home route which loads by default, then in chrome dev tools i disable the network (throttling to offline mode) after giving 1 sec to the "fetching" to happen, then i navigate to the `About` route which should have been fetched after the `app-shell` but an error arises where the component is not loaded and navigation breaks, i try to enable network again and it doesn't try to download the `About` chunk again.

Maybe we wasn't talking the same language when i said fetching all when the `app-shell` finished loading.
