### ISSUE TITLE
Production Deployment Guide

### ISSUE THREAD

**Issue by georanma** [AngularClass/angular-starter#630]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)
- **I'm submitting a ...**
  [ ] bug report
  [ x] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**
  Im requesting a feature
- **What is the current behavior?**
  Im having issues deploying my app with this framework to heroku. The container memory will max out and my port will not bind in time causing the app to crash. I believe it may be trying to run the dev environtment, but I believe it should be running production. 

2016-05-26T22:08:59.809830+00:00 heroku[web.1]: Process running mem=751M(146.7%)
2016-05-26T22:08:59.810022+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2016-05-26T22:09:21.397875+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
- **What is the expected behavior?**
  It would be nice to have a quick guide about deploying this to a server since it is meant to be a starter pack and I would guess that plenty of people here new to working with this stack. 
- **What is the motivation / use case for changing the behavior?**
  Better understanding of how to deploy the framework to a remote environment. 
- **Please tell us about your environment:**
- Angular version: 2.0.0-beta.11
- Browser: [all | Chrome  50.0.2661.102 m
  node version 4.4.1
  npm 3.8.0
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Thanks for entertaining my request.

**Comment by ebeal** [comment]
Is it more an issue you're having with the size limitations (if I had to guess I'm guessing you're including modules or typings and like you suspect trying to run the dev environment) or is it more that you're not sure you're doing other things correctly?

**Comment by georanma** [comment]
Hey Elle,

That sounds about right. Im not sure what all I can discard from the
project to make it light enough for my deployment to Heroku. Right now, the
only way I could get the project to start building on heroku, was to
include all dev dependencies at dependencies. If I dont, I get other
errors. When I dump all dev's into regular dependencies, I error memory
errors.

Any suggestions you have would be greatly appreciated. Im just building a
small contact form that is hooked up to a MongoDB. Should be pretty
lightweight when I clean up the excess functionality from the framework
(not that Im sure where Ill start on that either).

Thanks

**Comment by ebeal** [comment]
I'm still somewhat unclear at what point you're getting the errors. Is this during upload of the project or project build? Did you take a look at this already: [https://devcenter.heroku.com/articles/nodejs-support#build-behavior](https://devcenter.heroku.com/articles/nodejs-support#build-behavior)

**Comment by georanma** [comment]
It's during project build. I have not looked at that yet, but Im trying to see what I can do with a docker machine and aws in the mean time.

**Comment by mrowles** [comment]
@georanma We are getting the same issues and have tried the little things you have said you have tried also, to no avail. Any luck with Heroku, or did you go another way?

**Comment by georanma** [comment]
@mrowles What I ended up doing for the time being is running the build script locally and copying the dist files into a new repo folder to push to a separate heroku. Ive also started work with Digital Ocean for my wordpress dev and other small hosting needs, so Im going to play around with deploying and building there at some point. 

Ill have to check out your fix though. It would be nice to auto deploy to heroku on commits instead of my process.

Thanks

**Comment by cmckni3** [comment]
I would setup a CI service to build and deploy your Angular application. I used Travis CI and deployed to Heroku with their `dpl` tool. I had to use the [Heroku static buildpack](https://github.com/heroku/heroku-buildpack-static) to serve the application correctly.

**Comment by gdi2290** [comment]
for updates on this follow this issue. I'll have a section for deployment that everyone can help me with
https://github.com/AngularClass/angular-starter/issues/1686
