### ISSUE TITLE
Vendor.ts: How to prevent from being recompiled in Webpack-dev-server upon saving?

### ISSUE THREAD

**Issue by IAMtheIAM** [AngularClass/angular-starter#661]
Each time i edit any app component, webpack-dev-server recompiles the app components, plus all vendor.ts imports. This makes it slow.

How do I make WDS ignore vendor.ts when changing other files? Nothing inside vendor.ts changed so it shouldn't recompile.

**Comment by IAMtheIAM** [comment]
I see, that does work. I noticed that if I use bootstrap-loader, it adds 6 seconds to recompile time, even though nothing changes in that library. I import it into vendor.ts. How can I debug the cause of long recompile time from bootstrap loader.

**Comment by Luchillo** [comment]
Use [webpack-bundle-size-analyzer](https://github.com/robertknight/webpack-bundle-size-analyzer) to generate a json report about your compilation process.

Upload to [webpack analyse](https://webpack.github.io/analyse/) page to analyze your bundle process and get insight on errors, warnings and advise against slow bundling.
