### ISSUE TITLE
proxy configuration for npm test

### ISSUE THREAD

**Issue by shivagarwal08** [AngularClass/angular-starter#663]
I am using webpack-starter-angular2 project.
To make proxy for api i have used code as below
  devServer: {
....
proxy: {  
'/api/*': {     target: 'http://localhost:9090/',  secure: false   } }  
  },

Now I need to run npm test command so there urls are not redirecting to the proxy.
urls are like /api/v1/authenticate,
but i want urls should be like
'localhost:9090/api/v1/authenticate'

In which file do i need to set the proxy and what would be the code for that?
webpack.test.js or karma.config.js

Thank you.

**Comment by ebeal** [comment]
You should be able to set up the configuration in your protractor config file [See Selenium docs](https://https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities#proxy-json-objectgithub.com/SeleniumHQ/selenium/wiki/DesiredCapabilities#proxy-json-object)

It should look something like: 
```
capabilities: {
  browserName: 'firefox',
  proxy: {
     proxyType: 'manual',
     httpProxy: 'localhost:8443',
     sslProxy: 'localhost:8888'
  }
}
```
