### ISSUE TITLE
Anyone have sourcemaps working for karma stack traces?

### ISSUE THREAD

**Issue by abierbaum** [AngularClass/angular-starter#669]
- **I'm submitting a ...**
  [ ] bug report
  [X] feature request
  [ ] question about the decisions made in the repository
- **What is the current behavior?**

Currently when karma runs jasmine and a test fails, the stack trace will show the line number in the spec-bundle file instead of the original source.  The source maps exist that it should be possible to trace back.
- **What is the motivation / use case for changing the behavior?**

I think that the karma framework package: karma-source-map-support (https://www.npmjs.com/package/karma-source-map-support) should help with this but I can't get it up and running.

Has anyone else had any luck?

**Comment by Istenes** [comment]
I have the same issue, when using a breakpoint to debug tests we are only presented the compiled source and not the typescript source. Sourcemaps is enabled in chrome.
![no-sourcemaps-karma-webpack2](https://cloud.githubusercontent.com/assets/1083267/21305937/9d0f8d62-c5ce-11e6-9bed-907917ed50aa.PNG)

**Comment by jusefb** [comment]
Having the same problem. It seems like angualr-cli team have maanged to figure it out, would be great to know how
