### ISSUE TITLE
Strange behaviour running tests with karma --auto-watch

### ISSUE THREAD

**Issue by borntorun** [AngularClass/angular-starter#725]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**
  Report a possible bug.
- **What is the current behavior?**
  Running tests with karma auto-watch active (npm run watch:test) does not always trigger the correct results, as it seems something is not fetching the correct last version of the code.
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

Steps:
- clone the project
- npm install
- npm run watch:test
- \- the test are sucessfull
- change src/app.component.ts line 58 `url = 'https://twitter.com/AngularClass';` to `url = 'https://twitter.com/AngularClassXXXX'`
- the tests are **not sucessfull, which is correct**
- undo the change made on src/app.component.ts line 58
- the tests are **not sucessfull, which is incorrect**

So the **first change in code** after karma starts is always triggered, then the strange behaviour happens (cant find a pattern)
- subsequent changes are not trigger
- sometimes after a change in code, to trigger the correct behaviour I need to change a second file 

Seems something about karma-webpack-webpack-middleware is caching the old code or not syncing correctly.
- **What is the expected behavior?**
  Every last change in code reflected in the environment tests that are running with karma watch
- **Please tell us about your environment:**
- I used the last version of the repo (as today) 
- Browser: [ PhantomJS 2..0.1 | Chrome 51.0.2704.63 ]

**Comment by abdulhaq-e** [comment]
Exact same problem: https://github.com/AngularClass/angular2-webpack-starter/issues/718

I thought the problem was due to removing `fileGlob` but it turns out that it's not.

**Comment by abdulhaq-e** [comment]
As for me, the problem is recent.

**Comment by abdulhaq-e** [comment]
It seems to be a well known issue: https://github.com/karma-runner/karma/issues/1087 https://github.com/webpack/karma-webpack/issues/9

**Comment by borntorun** [comment]
I'v found some projects where there this bug does not exists: [angular2-starter](https://github.com/rangle/angular2-starter) or [angular2-webpack](https://github.com/preboot/angular2-webpack) 
But still could not find the differences that may be the cause the problem. Maybe some kind of buggy configuration around karma/webpack.

**Comment by borntorun** [comment]
@abdulhaq-e Before I submit this issue I tried the solution around `fileGlob` but with no success.

**Comment by abdulhaq-e** [comment]
Btw, are you using Atom?

**Comment by borntorun** [comment]
I tried with Atom, WebStorm and vi.
Always the same problem.

**Comment by abdulhaq-e** [comment]
I have just tested Karma 1.0.0, same issue.

**Comment by smitalm** [comment]
Have you resolved this issue? I am experiencing the same issue with typescript validation errors. If i restart task, errors are gone.

**Comment by borntorun** [comment]
With the actual version on master i'm not seeing this problem anymore.

**Comment by sakkelaaksonen** [comment]
Been having this issue since august. 
Touching (saving or other) files other than the actual specs triggers a rerun but specs are not updated.
