### ISSUE TITLE
async router bug: async route with multiple children throws exception if you page load with full url path to child route

### ISSUE THREAD

**Issue by ncfx** [AngularClass/angular-starter#751]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)
- **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**
  bug
- **What is the current behavior?**
  If you have an async route that has multiple children, and you attempt to load the page with the full URL (i.e. www.mydomain.com/route/childroute/params), an unhandled exception will be thrown for "ChildRoute component cannot be found". Execution continues, but the router reverts to the base href /.

Just to be clear, when I say async route with multiple children, let's say +detail's routes is this: 

``` es6
export const routes = {
  path: 'detail', component: Detail,
  children: [
    { path: '', component: Index },
    { path: 'hello', component: Hello},
    { path: 'world', component: World},
    { path: 'user/:id', component: User}
  ]
};
```

and I want to load the page at: `http://localhost:3000/detail/user/xyz123` this will throw the exception and the router reverts to /.
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
- **What is the expected behavior?**
  Router should not throw exception and a full URL path with child routes should be supported.
- **What is the motivation / use case for changing the behavior?**
  This is a standard feature of any router
- **Please tell us about your environment:**
  June 30th build of angular2-webpack-starter. Running on mac, Chrome 51.0.2704.106
- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by gdi2290** [comment]
this problem will be fixed in angular `rc.5`. For now, you have to manually create the async version of your routes

https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/app/app.routes.ts
```es6
export const routes: RouterConfig = [
  { path: '',      component: Home },
  { path: 'home',  component: Home },
  // make sure you match the component type string to the require in asyncRoutes
  { path: 'about', component: 'About',
    resolve: {
      'yourData': DataResolver
    }},
  // async components with children routes must use WebpackAsyncRoute
  { path: 'detail', component: 'Detail',
    canActivate: [ WebpackAsyncRoute ],
    children: [
      { path: '', component: 'Index' }  // must be included
    ]},
  { path: '**',    component: NoContent },
];
```
for you would be 
```es6
export const routes: RouterConfig = [
  { path: '',      component: Home },
  { path: 'home',  component: Home },
  // make sure you match the component type string to the require in asyncRoutes
  { path: 'about', component: 'About',
    resolve: {
      'yourData': DataResolver
    }},
  // async components with children routes must use WebpackAsyncRoute
  { path: 'detail', component: 'Detail',
    canActivate: [ WebpackAsyncRoute ],
    children: [
      { path: '', component: 'Index' },
      { path: 'hello', component: 'Hello'},
      { path: 'world', component: 'World'},
      { path: 'user/:id', component: 'User'}
    ]},
  { path: '**',    component: NoContent },
];
```
