### ISSUE TITLE
Karma unit tests serve compiled ts source files

### ISSUE THREAD

**Issue by rafalFurman** [AngularClass/angular-starter#779]
I believe its a bug in configuration of karma. Currently .ts files under tests are served to the browser in compiled form while tests themselves are nicely debuggable.

To reproduce this behavior:
execute karma start
in chrome browser launched by karma click debug button
launch developer tools F12
in sources tab navigate to webpack://->.->src/app->app.component.ts

In contrast to app.spec.ts file app.component.ts does not display typescript source code which is expected and required in order to debug classes under test. 

Could you provide some inside on how it should be configured to be able to debug classes under test?

**Comment by rintoj** [comment]
Tried many things, but no luck. Can someone help?

**Comment by mostsignificantbit** [comment]
I am also interested in a solution.
