### ISSUE TITLE
Webpack is not watching my changes in a new directory.

### ISSUE THREAD

**Issue by bfwg** [AngularClass/angular-starter#857]
I'm submitting a question about the decisions made in the repository

I create a new directory called `services` under app:

```
app/
    services/
        some-service.ts
        index.ts
```

Added to index.ts

```
export * from './services';
export * from './app.component';
export * from './app.service';
export * from './app.routes';

import { AppState } from './app.service';

// Application wide providers
export const APP_PROVIDERS = [
  AppState,
];
```

Every time I make a change in some-service.ts, webpack-dev-server will restart, but the changes will not get picked up.

Only compilation errors not updated on change. Like:

```
   Property 'callback' does not exist on type '{}'.
   Supplied parameters do not match any signature of call target.
```

I have to manually shutdown and restart dev-server to recompile.

**Comment by IAMtheIAM** [comment]
Post more of your typescript code as well as full error details for us to diagnose. It's not enough info to give an accurate answer yet. I was able to add a new services directory with no problem.

**Comment by bfwg** [comment]
Here is some more code:
```javascript
@Component({
  selector: 'test',
  providers: [
  ],
  directives: [],
  pipes: [],
  template: `
    <div class="abc">
       abc
    </div>
  `,
  styles: [
    .abc {
       width: '20%',
       margin: '10px'
    }
  ]
})
```
I worte the styles in a wrong way, and here are the errors.
```
[default] /Users/sss/code/asdfkj/src/test.component.ts:19:5
    Expression or comma exected.
[default] /Users/sss/code/asdfkj/src/test.component.ts:19:6
    Cannot find name 'abc'
[default] /Users/sss/code/asdfkj/src/test.component.ts:19:10
    ',' expected.

```
I correct it by changing the style to 
```
  styles: [`
    .abc {
      width: '20%';
      margin: '10px;
    }
  `]

```
Webpack pickup my change and reload. But the same errors appear again.
I only gose away if I `ctrl+c` stop webpack and restart it.
