### ISSUE TITLE
Question : how to include css and images from another 'node_module' ?

### ISSUE THREAD

**Issue by StefH** [AngularClass/angular-starter#887]
**I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] question about **webpack**

I'm trying to add functionality from https://github.com/primefaces/primeng-quickstart-webpack into this project. However I'm stuck on how to include the css and images defined by primeng.

In the original project, the css's are added to the _index.html_ like this:

``` html
    <link rel="stylesheet" type="text/css" href="node_modules/primeui/themes/omega/theme.css" />
    <link rel="stylesheet" type="text/css" href="app/resources/icons/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="node_modules/primeui/primeui-ng-all.min.css" />
```

But I guess I need to use the https://www.npmjs.com/package/copy-webpack-plugin to make sure the css and images are copied to '**assets**'.

I tried this code, however I cannot not get it to work, probably miss something.

``` js
new CopyWebpackPlugin([
      {
        from: 'src/assets',
        to: 'assets'
      },
      {
        from: 'node_modules/primeui/themes/omega/**/*',
        to: 'assets'
      },
      {
        from: 'node_modules/primeui/**/*.css',
        to: 'assets'
      }
    ]),
```

Can you please help me ?

**Comment by DzmitryShylovich** [comment]
```
new CopyWebpackPlugin([
      {
        from: 'src/assets',
        to: 'assets'
      },
      {
        from: 'node_modules/primeui',
        to: 'assets/primeui'
      }
    ]),
```

```
    <link rel="stylesheet" type="text/css" href="assets/primeui/themes/omega/theme.css" />
    <link rel="stylesheet" type="text/css" href="assets/primeui/primeui-ng-all.min.css" />
```

**Comment by StefH** [comment]
Clear.

However, is adding links directly inside the _index.html_ common practice, or should I add these links into the **head-config.common.js** file ?

**Comment by DzmitryShylovich** [comment]
it is a matter of personal preference. both options are effectively the same.

**Comment by StefH** [comment]
Can someone from the team also comment on this?

**Comment by IAMtheIAM** [comment]
The `head-config.common.js` is just a programmatic way to construct `index.html`. You can add them directly in the index.html, or through head-config.common.js and it outputs the exact same thing.

Personally I do not load vendor libaries that way because you have webpack at your command. Rather that making all those network requests, just bundle the library into your `vendor.ts` webpack bundle.

Here an example of how I imported Materialize CSS and KendoUI Grid to the app inside vendor.ts

(partial file)
```
/** Materialize CSS - JS require()  */
require('materialize-css/dist/js/materialize.js'); // main js file
/** Materialize CSS - SCSS require() must come before KendoUI for css specificity to be   */
require('materialize-css/sass/materialize.scss'); // main scss file

/** KendoUI Professional */
require('./lib/kendoui/styles/kendo.common.min.css');
// require('lib/kendoui/styles/kendo.material.min.css');
require('./lib/kendoui/styles/kendo.default.min.css');
require('./lib/kendoui/js/kendo.web.min.js');
require('./lib/kendoui/js/kendo.core.min.js');
require('script-loader!./lib/kendoui/js/kendo.grid.min.js'); // must be passed through webpack "script-loader"
```

**Comment by gilhanan** [comment]
@IAMtheIAM how do you configure webpack in order to loading these CSS files to index?

**Comment by IAMtheIAM** [comment]
@gilhanan See my post above. You just require() them as I have shown in your vendors.ts file, then in your index.html you add the vendors.ts script as a normal `<script src="vendors.ts" type="text/javascript">` tag before the closing </body> tag.

**Comment by evgd** [comment]
@StefH did you manage to integrate with PrimeNG?

**Comment by StefH** [comment]
@evgd 
I tried to merge the latest changes into my branch, however there are too many PR + changes, so I decided to fork this project again and add my PrimeNG stuff to it.

However, now I'm stuck at some errors like:
`Error: Unexpected value 'CategoryGridODataComponent' declared by the module 'CarModule'`

The code is located at : 
https://github.com/StefH/angular2-webpack-starter/tree/_stef_dev
Maybe somebody can help me ?

**Comment by StefH** [comment]
**Update**
All is fixed now, I forgot a `@` in `@Component`, see [this](https://github.com/StefH/angular2-webpack-starter/tree/_stef_dev).

PrimeNG Grids looks like:
![primeng-grid](https://cloud.githubusercontent.com/assets/249938/23959252/fe45318a-09a4-11e7-878b-c52411cab37e.png)

**Comment by simonmcl** [comment]
Having the same issue with leaflet maps css and its images and can't understand how its suppose to work. The vendor.ts file is now gone and can't see any instructions, wiki's, posts or issues explaining the new process. Only thing i've seen is people saying "It won't cause any differences in your code" ... clearly not.

@IAMtheIAM did you face this issue? Do you know where / how to move your `require()`'s? I can only get it to work at the minute by doing the copy and then calling it in the index.html, which is not ideal.


<br/>
<br/>

**Code for googler's**
```
// Webpack common
new CopyWebpackPlugin([
    { from: 'src/assets', to: 'assets' },
    { from: 'src/meta'},
    { from: 'node_modules/leaflet/dist/leaflet.css', to: 'assets/leaflet'},
    { from: 'node_modules/leaflet/dist/images', to: 'assets/leaflet/images'},
    { from: 'node_modules/leaflet.markercluster/dist/MarkerCluster.css', to: 'assets/leaflet'},
    { from: 'node_modules/leaflet.markercluster/dist/MarkerCluster.Default.css', to: 'assets/leaflet'},
]),


// index.html
<link rel="stylesheet" type="text/css" href="assets/leaflet/leaflet.css" />
<link rel="stylesheet" type="text/css" href="assets/leaflet/MarkerCluster.css" />
<link rel="stylesheet" type="text/css" href="assets/leaflet/MarkerCluster.Default.css" />
```
