### ISSUE TITLE
[Question] ng-semantic integration

### ISSUE THREAD

**Issue by DjolePetrovic** [AngularClass/angular-starter#897]
Hey,

How can I integrate [ng-semantic](https://github.com/vladotesanovic/ngSemantic) with this starter pack?

Thanks in advance

**Comment by IAMtheIAM** [comment]
Semanic UI is a jQuery library, so you'll need to add this code inside your component.ts file :

```
const $ = require('jquery');
const jQuery = $;
```
You'll need to redeclare the jQuery constant inside each component that will use jQuery. There are other ways to expose jQuery on an appwide level, but I haven't been successful. It's support to work with `expose-loader`, however I found this method of importing directly in each component to be easy and reliable.

You also need to add `"jquery": "^3.1.0",` as a dependency in package.json

Now you should be able to use your Semanic UI jquery code in your components.
