### ISSUE TITLE
use class for config generation

### ISSUE THREAD

**Issue by fxck** [AngularClass/angular-starter#910]
https://github.com/angular/angular-cli/blob/master/addon/ng2/models/webpack-config.ts 
https://github.com/angular/angular-cli/blob/master/addon/ng2/models/webpack-build-common.ts
https://github.com/angular/angular-cli/blob/master/addon/ng2/models/webpack-build-development.ts
https://github.com/angular/angular-cli/blob/master/addon/ng2/models/webpack-build-production.ts

looks kinda neat and clean, doesn't it?

**Comment by katallaxie** [comment]
See [v6](https://github.com/AngularClass/angular2-webpack-starter/tree/v6)

**Comment by fxck** [comment]
What's missing @katallaxie ?

**Comment by fxck** [comment]
There's a problem with those DLLs @katallaxie, when you have a vendor script that extends something like rxjs Subject(like @ngrx/store), and you don't put it inside the "rxjs" dll array, none of the added operators are gonna work on it. Perhaps it's just a naming / documentation problem though.

**Comment by katallaxie** [comment]
@fxck that's a feature 😄 . yep, but that is how it works, because all `deps` are then linked

**Comment by fxck** [comment]
Yeah, but given that it's called 

```
// RxJS
export function rxjs(env?: any) { }
```

I automatically assumed it's rxjs operators only, but in fact, it's for every lib that's using rxjs :)

**Comment by katallaxie** [comment]
@fxck you could simply move everything to `vendor`, if you like.
