### ISSUE TITLE
Type X is part of the declarations of 2 modules: AppModule and AsyncModule

### ISSUE THREAD

**Issue by orlov-vo** [AngularClass/angular-starter#921]
```
Type ContentComponent is part of the declarations of 2 modules: AppModule and AsyncModule
```

I have 2 modules:
- `AppModule` - root module
- `AsyncModule` - module which is loaded asynchronously (as Detail component - async routing)

These modules use the same component `ContentComponent`. And on RC-4 it's ok... But on RC-5 I have this problem...

**Comment by gaurav2887** [comment]
@orlov-vo : Do you have this component declared in both the modules?. If you just declare in AppModule then you don't have to declare it again in AsyncModule . It will be available for the entire app.

**Comment by daominhsangvn** [comment]
Same issue. The directives declared in AppModule not working on Lazyload module. Directive host listener not working on lazyload module for specific

**Comment by daominhsangvn** [comment]
Turn all of them into modules to make it work.

**Comment by hdung912** [comment]
using @IonicPage({
  name: 'login-page'
})
and this.nav.push('login-page')
