### ISSUE TITLE
Using bootstrap 4 mixins with angular2

### ISSUE THREAD

**Issue by regenrek** [AngularClass/angular-starter#924]
Hi,

don't know if its the right place to ask here but I'm 
trying to get this repo work with bootstrap 4 mixins.

I followed the wiki bootstrap 4 guide and everything
looks good.

But if I have an component for instance 

**home.component.ts**

```
@Component({
  selector: 'home',
  styleUrls: ['./home.style.scss'],
  templateUrl: './home.template.html'
})
```

and **home.style.scss**

`@include media-breakpoint-up(md) {
    .dosomething {
         padding: 0px;
    }
}`

I get 'No mixin named media-breakpoint-up'.

If i add the following line to **home.style.scss**
it works. But I don't know it it's the right thing todo.

```
@import "./node_modules/bootstrap/scss/_variables.scss";
@import "./node_modules/bootstrap/scss/mixins/_breakpoints.scss";
```

So is it possible to inject _breakpoints.scss (mixins) and _variables.scss 
global or if its needed? Shouldn't webpack handle this case?

Regards

**Comment by jshamley** [comment]
I got this to work by importing `@import "../../../node_modules/bootstrap/scss/bootstrap-grid.scss";` instead of the breakpoints directly. The Bootstrap-Grid file does include the breakpoints along with other pieces.

**Comment by regenrek** [comment]
@jshamley True. Thank you. bootstrap-grid.scss looks better. But you need still manually import the scss files right? Where do you import the scss - in every component where you need the mixins or globally (maybe in app.styles?)

Regards

**Comment by jshamley** [comment]
@regenrek I have been importing them per component SCSS file. I have only needed those mixins a couple times so far so I didn't take the time to import globally.

**Comment by katallaxie** [comment]
A bit off topic: but you can use all the `import` Sass files with module syntax by prefixing it with `~` `import "~boostrap/scss/bootstrap-grid.scss`.

**Comment by regenrek** [comment]
@katallaxie That would be great but I'll get
`Cannot find module "~bootstrap/scss/bootstrap-grid.scss"`

**Comment by katallaxie** [comment]
@regenrek check the path, this was just an example.

https://github.com/jtangelder/sass-loader#imports

**Comment by regenrek** [comment]
@katallaxie yes. tried to include it in the home.component.ts. Works so far.

home.style.scss
`@import "~bootstrap/scss/bootstrap-grid.scss";`

**Comment by codespicelabs** [comment]
@regenrek have you seen https://ng-bootstrap.github.io/ ? It uses the latest RC.6 and it possible just to import one like any other new ngModules

ps: IMO ng-bootstrap is the subject for some new webpack-starter branch of this repo ?

**Comment by alvipeo** [comment]
+1 for ng-bootstrap branch

**Comment by katallaxie** [comment]
I think should be sufficient to have this in `README`. @regenrek could you do that and do a PR?

**Comment by stamminator** [comment]
⚠⚠⚠
`@import "../../../node_modules/bootstrap/scss/bootstrap-grid.scss";` is _not_ a good solution! This is causing Bootstrap's grid CSS to be regenerated every place you use this import. You only want the mixins, which by themselves don't add to any generated CSS output. [Here is the best solution.](https://github.com/angular/angular-cli/issues/1261#issuecomment-347973328)
