### ISSUE TITLE
Property 'includes' does not exist on type 'string[]'.

### ISSUE THREAD

**Issue by monad98** [AngularClass/angular-starter#931]
- **I'm submitting a ...**
  [*] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**
  report a bug
- **What is the current behavior?**
  I got following error.
  Property 'includes' does not exist on type 'string[]'.
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
  After [this commit](https://github.com/AngularClass/angular2-webpack-starter/commit/746d2e97ee7e33720a6d63264d43c1c2e10e869d), when I use 'Array.prototype.includes()' I got above error.
- **What is the expected behavior?**
  No errors.
- **Please tell us about your environment:**
  Angular version: 2.0.0-rc5
  Node v6.2.2
  NPM v 3.9.5

**Comment by rvalimaki** [comment]
I can confirm this problem. Obviously this affects to all Arrays, eg. "Property 'includes' does not exist on type 'number[]'."

I tried to change the ES target to ES6 with no success.

**Comment by rvalimaki** [comment]
Okay, to overcome the issue, I needed to set tsconfig.json compilerOptions.lib from "es6" to "es7" as follows:

    "lib": [
      "dom",
      "es7"
    ],

I'm not sure if this causes other problems, though. "includes" is implemented for 'string' (not Array<string>) in ES6, and for arrays only in ES7.

**Comment by KhaledElAnsari** [comment]
any updates on this?

**Comment by rvalimaki** [comment]
@KhaledElAnsari 

I don't think any updates are needed for this, since if you want to use ES7 features on your code, you have to set the "lib" version in tsconfig.json (and tsconfig.webpack.json) to "es7".

So I can't see any issues on Angular2 webpack starter or Angular2 itself regarding this. Just set the library version you want, and you are good to go.

**Comment by karkokat** [comment]
What worked for me was just declare array with also its datatype like as:  let array = []; instead of just let array; where is its datatype undefined.

**Comment by jamesbrobb** [comment]
I'm still seeing this issue and none of the suggested fixes appear to work

**Comment by leotm** [comment]
@rvalimaki 's suggestion worked for me, just had to remember to *Reload Window* for the changes to take effect.
