### ISSUE TITLE
"npm install" fails on Windows 10

### ISSUE THREAD

**Issue by crchemist** [AngularClass/angular-starter#945]
- **I'm submitting a ...**
  [ x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**
  report a bug
- **What is the current behavior?**
  `npm install` command fails with traceback.
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
- Run `npm install` command at Windows10
- **What is the expected behavior?**
  Dependencies should be installed.
- **What is the motivation / use case for changing the behavior?**
  Not able to start app.
- **Please tell us about your environment:**
- Angular version: 2.0.0-rc.6
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
  This bug appear after next commit fad28acfd89b63ea1b4e7534289ded99e3432448 . Here is an error:

```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mkharech\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! fsevents@1.0.14 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
```

**Comment by k-zakhariy** [comment]
I have the same issue...

**Comment by zigzag95** [comment]
Check npm --version should be > 3
Check node --version should be > 4
Install c++ redistributable 
Run npm install then you should see some C compilation logs

**Comment by k-zakhariy** [comment]
node 6.3.1
npm version 3.3.1
c++ redistributable is installed

The first error message after npm install :
```
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@6.3.1 (node-v48 ABI) (falling back to source compile with node-gyp)
```
then
```
npm ERR! Failed at the fsevents@1.0.14 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
```

**Comment by zigzag95** [comment]
Try with admin rights

**Comment by crchemist** [comment]
@zigzag95 it is normal that fsevents build fails on windows. Issue occurs because for some reason fsevents became required(before it was optional)

**Comment by k-zakhariy** [comment]
@zigzag95 I tried, no success

**Comment by alvipeo** [comment]
Hm, I don't have any issue on Windows 10.

**Comment by IAMtheIAM** [comment]
You need to install [Python v2.7](https://www.python.org/download/releases/2.7/) for node-gyp to build successfully.
