### ISSUE TITLE
New package.json script to start server and protractor concurrently

### ISSUE THREAD

**Issue by workasr** [AngularClass/angular-starter#950]
- **I'm submitting a ...**
  [ ] bug report
  [x ] feature request
  [ ] question about the decisions made in the repository
- **What is the current behavior?**
  Currently you have to start the app server and protractor from separate terminals.
  This makes it difficult to run the protractor tests from a Maven build.
- **What is the desired behavior?**
  Have the server and protractor started from Maven directly.
- **What is the motivation / use case for changing the behavior?**
  Run CI tests directly from Maven in an integration server, e.g. Jenkins.
- **Please tell us about your environment:**
  Latest version of this project as of 2016/09/02.
  Using Maven Plugin:

```
            <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
            </plugin>
```

CI is run under Linux, development is under Windows.
- **Other information**

I found an npm package called concurrently [https://www.npmjs.com/package/concurrently](url).
I added the following to package.json:

```
    "e2e": "concurrently -s first --names \"appserver,protractor\" -p \"{name}--{pid}\" -k \"npm run server\" \"npm run protractor\"",


   "concurrently": "^2.0.0",

```

Works like a charm!!

**Comment by IAMtheIAM** [comment]
That is a good one. Another way on Windows environment is to prefix any command with `start`

Example: `start npm run appserver && start npm run protractor`

This will launch both programs in a new console window, on a different thread that isn't connected to each other. Works for free without any extra packages :-)
