### ISSUE TITLE
Support o multiapplications to share code between projects

### ISSUE THREAD

**Issue by netstart** [AngularClass/angular-starter#960]
How can I share components between projects?

Below dashboard example should be use components of the eye project, and nose project.

src
├─ eye
│ ├── components
│ │ ├── eye.component.html
│ │ ├── eye.component.ts
│ │ ├── eye.component.css
├─ nose
│ ├── components
│ │ ├── nose.component.html
│ │ ├── nose.component.ts
│ │ ├── nose.component.css
├─ dashboard
│ ├── components
│ │ ├── dashboard.component.html
│ │ ├── dashboard.component.ts
│ │ ├── dashboard.component.css
Other example, to ilustrate
In the structure below, commonaplication need share eye.component and nose.component with bodyaplication and dashboardaplication.
src
├── commonaplication
│ ├── components
│ │ ├── eye.component.ts
│ │ ├── nose.component.ts
├── bodyaplication
│ ├── components
│ │ ├── head.component.ts
├── dashboardaplication
│ ├── components
│ │ ├── dashboard.component.ts

**Comment by katallaxie** [comment]
There is the approach to have a `core` folder/component with these shared parts. Our you use a structure with `components`, `services` etc. I am using this for some client projects.
