### ISSUE TITLE
cannot access node native modules

### ISSUE THREAD

**Issue by naivefun** [AngularClass/angular-starter#961]
I'm trying to use this repo with electron.

It runs without a problem until I need use http module. When I do `let http = require('http')` it returns a partial object without most of the functions and I got `http.createServer is not a function` error. How can I fix this? Thanks.

**Comment by naivefun** [comment]
Now I use `target: "electron"` and set:
```
node: {
        global: 'window',
        crypto: 'empty',
        fs: true,
        http: true,
        process: true,
        module: false,
        clearImmediate: false,
        setImmediate: false
    }
```
it throws new exception:
```
vendor.bundle.js:77976 Uncaught SyntaxError: Unexpected token :
main.bundle.js:2 Uncaught ReferenceError: exports is not defined
```
<img width="602" alt="screenshot 2016-09-05 12 15 29" src="https://cloud.githubusercontent.com/assets/10683378/18237329/81c38504-7362-11e6-8634-f7c6034c4070.png">

**Comment by naivefun** [comment]
If I add `DEBUG` to process.env manually, the error becomes:
```
node.js:122Uncaught ReferenceError: Invalid left-hand side in assignment
main.bundle.js:2Uncaught ReferenceError: exports is not defined
```
<img width="576" alt="screenshot 2016-09-05 12 27 02" src="https://cloud.githubusercontent.com/assets/10683378/18237449/2d66ef94-7364-11e6-8423-22101db20b24.png">

Now I really don't know what to do ...

**Comment by G-Ray** [comment]
Hi @naivefun , I spent some hours to finally find a solution, in case you, or others are still searching:

Use `target: 'electron-renderer'` and thanks to https://github.com/visionmedia/debug/issues/301, change https://github.com/AngularClass/angular2-webpack-starter/blob/master/config/webpack.dev.js#L137 to:

```
'process.env.ENV': JSON.stringify(METADATA.ENV),
'process.env.NODE_ENV': JSON.stringify(METADATA.ENV),
'process.env.HMR': METADATA.HMR
```

Should we open a PR for this ? (it applies only if you want to use electron/node)

**Comment by a-maldet** [comment]
@G-Ray: Thanks for your help, but it did not fully solve this problem for me still getting the errors
```
node.js:143Uncaught ReferenceError: Invalid left-hand side in assignment
vendor.bundle.js:1Uncaught ReferenceError: exports is not defined(anonymous function)
main.bundle.js:2Uncaught ReferenceError: exports is not defined
```

**Comment by germanamz** [comment]
My issue was only when importing electron like this: 
`import * as electron from 'electron';`
Or
`import { ipcRenderer } from 'electron';`

To fix it i used the node require function like this:
`import electron = require('electron');`

And accesing to the ipcRenderer like this:
`electron.ipcRenderer;`
