### ISSUE TITLE
Dashes instead of %20 in Urls

### ISSUE THREAD

**Issue by timojokinen** [AngularClass/angular-starter#969]
I have a question:

Is it possible to use dashes instead of %20 blank space seperator in urls?

I want to have friendly Urls, with the title of a project and its ID

`[routerLink]="['/project', project.Description]`

Url looks like this at the moment: project/enterprise%20apps%20team%20developer
and I want it to look like this: project/enterprise-apps-team-developer-208
where 208 is the ID

**Comment by IAMtheIAM** [comment]
You need to handle `project.Description` assuming that's where "enterprise-apps-team-developer" is coming from. Type it with dashes. Its only doing %20 because you used spaces in the description somewhere.

**Comment by katallaxie** [comment]
You could to a [replace()](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/String/replace) on your description.
