### ISSUE TITLE
Include cucumber BDD/SBE tests in the project

### ISSUE THREAD

**Issue by pete2014** [AngularClass/angular-starter#983]
- **I'm submitting a ...**
  [x] feature request
- **What is the current behavior?**
  Only unit and UI tests currently exist.
- **What is the expected behavior?**
  Would like to see cucumber included in the projects. The cucumber steps should be in typescript to allow for neater development and debugging.
- **What is the motivation / use case for changing the behavior?**
  In my case I have a typescript library that does some custom calculations. This 'library' would then be consumed by the Angular2 UI. SBE/BDD tests are the best way of testing these type of calculations. I am already using cucumber in an old browserify stack but would like to move it into the angular2/webpack domain.
- **Please tell us about your environment:**
- Windows
- Visual Studio/VS Code/Notepad
- Angular version: 2 RC6
- Browser: any/all
- Typescript 1.8+ (can use 2+)

**Comment by samvloeberghs** [comment]
Check my repo's, I've have an example setup
