### ISSUE TITLE
e2e test are stopped working - issue with selenium-webdriver 

### ISSUE THREAD

**Issue by fazanki** [AngularClass/angular-starter#990]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)
- **I'm submitting a ...**
  [ x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**

BUG REPORT
- **What is the current behavior?**

e2e is not running 
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

npm run e2e
- **What is the expected behavior?**

it should run functional tests 
- **What is the motivation / use case for changing the behavior?**

/angular2-webpack-starter/node_modules/selenium-webdriver/error.js:27
    super(opt_error);
    ^
SessionNotCreatedError: session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"17948.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=54.0.2840.16)
- **Please tell us about your environment:**
  node version 6.5
  Chrome Version 54.0.2840.16 beta (64-bit)
- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome Version 54.0.2840.16 beta (64-bit) | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
  have tried to update webdriwer by running:
  npm i webdriver-manager update --chromedriver
  npm run e2e stopped working

**Comment by ecozoic** [comment]
See my comments: [here](https://github.com/angular/angular-cli/issues/2176)
