### ISSUE TITLE
'(dependencies:any) => void' is not assignable to parameter type ....

### ISSUE THREAD

**Issue by YeomansIII** [AngularClass/angular-starter#991]
- **I'm submitting a ...**
  [*] bug report
- **What is the current behavior?**

When running build:prod or the development server, I am returned with the following error:

```
[default] /home/jason/dev/Git/ptone-admin/src/main.browser.ts:27:26 
    Argument of type '(dependencies: any) => void' is not assignable to parameter of type 'string | string[]'.
  Type '(dependencies: any) => void' is not assignable to type 'string[]'.
    Property 'push' is missing in type '(dependencies: any) => void'.
[default] Checking finished with 1 errors
```

The file that the error is referencing is the default Angular Class provided main.browser.ts.  Oddly enough, that file is only 16 lines long, so I'm not sure how this error is occurring on line 27.

```
import {platformBrowserDynamic} from "@angular/platform-browser-dynamic";
import {AppModule} from "./app/app.module";
import { bootloader } from '@angularclass/hmr';

export function main(): Promise<any> {
  return platformBrowserDynamic()
    .bootstrapModule(AppModule)
    .catch(err => console.error(err));
}

bootloader(main);
```
- **What is the expected behavior?**
  This error should not be returned.
- **Please tell us about your environment:**
- Angular version: 2.0.0-rc.6
- Browser: all
- Node: 5
- Typescript 2.0.0
- Webpack 2.1.0-beta.21

**Comment by runtheyards** [comment]
FYI the line number are different as the error is being reported from the compiled js versions so will be different from the typescript version.

**Comment by clementprevot** [comment]
Hi!

I'm having the same error while running the live server...
The odd thing is that everything is working fine (so far), but this error still appears at each startup

**Comment by nikolaymatrosov** [comment]
Hi!
These errors are produced by autogenerated code appended by HMR-plugin. I've already made pull request to fix the problem, but it hasn't been approved yet. https://github.com/AngularClass/angular2-hmr-loader/pull/3

As a temporary fix you can apply the same changes to the file in your `node_modules`.

**Comment by wachri** [comment]
I referred to you repo and commit in my package.json but the error still occurs.

**Comment by ASK83** [comment]
I had the same problem which made the whole hmr failed to hot reload my app and @AlexYankee fixed my problem. Thanks
